Screenful.Loc={
  ready: "Fertig.",
  find: "Finden",
  reload: "Neu laden",
  cancel: "Abbrechen",
  more: "Mehr",
  new: "Neu",
  edit: "Bearbeiten",
  save: "Speichern",
  delete: "Löschen",
  listing: "Liste abrufen...",
  listingFailed: "Liste kann nicht abgerufen werden.",
  reading: "Element abrufen...",
  readingFailed: "Kein solches Element gefunden.",
  saving: "Speichern...",
  savingFailed: "Speichern fehlgeschlagen.",
  deleting: "Löschen...",
  deletingFailed: "Löschen fehlgeschlagen.",
  deleteConfirm: "Jetzt Vorsicht! Sind Sie sicher?",
  username: "E-Mail-Adresse",
  password: "Passwort",
  login: "Login",
  loginError: "Falsche E-Mail-Adresse oder falsches Passwort.",
  logout: "Logout",
  anonymous: "anonymer Benutzer",
  home: "Home",
  title: "Titel",
  titleEmpty: "Der Titel sollte nicht leer sein.",
  url: "URL",
  urlEmpty: "Die URL sollte nicht leer sein.",
  urlShort: "Die URL sollte mindestens drei Zeichen lang sein.",
  urlInvalid: "Die URL sollte keine anderen Zeichen als a-z, A-Z, 0-9 und Bindestriche enthalten.",
  urlTaken: "Diese URL ist bereits vergeben.",
  template: "Template",
  create: "Erstellen",
  finished: "Fertig",
  changePwd: "Passwort ändern",
  signup: "Konto einrichten",
  forgotPwd: "Passwort vergessen?",
  signupEmail: "Um ein Konto zu erhalten, senden Sie eine E-Mail an",
  newPassword: "Neues Passwort",
  change: "Ändern",
  passwordChanged: "Ihr Passwort wurde geändert!",
  passwordEmpty: "Das Passwort sollte nicht leer sein.",
  passwordShort: "Das Passwort sollte mindestens sechs Zeichen lang sein.",
  passwordWhitespace: "Das Passwort darf nicht mit einem Leerzeichen beginnen oder enden.",
  ok: "OK",
  currentUrl: "Aktuelle URL",
  newUrl: "Neue URL",
  upload: "Hochladen",
  uploadPurge: "Vor dem Hochladen bereinigen",
  uploadFail: "Der Upload ist fehlgeschlagen.",
  uploadSuccess: "Der Upload war erfolgreich.",
  history: "Historie",
  version: "Version",
  clone: "Klonen",
  sourceCode: "Quellcode",
  invalidSourceCode: "Ungültiger Quellcode",
  unsavedConfirm: "Sie haben nicht gespeicherte Änderungen. Sind Sie sicher, dass Sie diese verlieren wollen?",
  doItLater: "Später erledigen",
  badEmailError: "Falsche E-Mail Adresse.",
  forgotPwdEmail: "Wenn Sie Ihr Passwort vergessen haben, geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen eine Anleitung zu, wie Sie ein neues Passwort anlegen können.",
  recoverPwd: "Neues Passwort anfordern",
  tokenSent: "Wir haben Ihnen eine E-Mail mit einer Anleitung zum Zurücksetzen Ihres Passworts geschickt.",
  recoverPwdMsg: "Sie können Ihr Passwort jetzt ändern.",
  changePwdMsg: "Hier können Sie Ihr Passwort ändern.",
  invalidToken: "Dieser Link zum Zurücksetzen des Passworts ist ungültig. Er ist möglicherweise abgelaufen oder wurde bereits verwendet.",
  signupInfoEmail: "Um ein neues Konto einzurichten, geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen Anweisungen zu.",
  signupButton: "Neues Konto erstellen",
  signupTokenSent: "Wir haben Ihnen eine E-Mail mit Anweisungen zum Erstellen eines neuen Kontos geschickt.",
  invalidSignupToken: "Dieser Anmeldelink ist ungültig. Er ist möglicherweise abgelaufen oder wurde bereits verwendet.",
  setPwdMsg: "Bitte setzen Sie jetzt Ihr Passwort.",
  accountCreated: "Wir haben Ihr Konto erstellt. Sie können sich jetzt mit Ihrer E-Mail-Adresse und Ihrem Passwort anmelden.",
  autosave: "Autosave",
  flagging: "Flagging...",
  flaggingFailed: "Der Eintrag konnte nicht markiert werden.",
  exactMatches: "Exakte Übereinstimmungen",
  partialMatches: "Teilweise Übereinstimmungen",
  comments: "Kommentare",
  newComment: "neuer Kommentar",
  revive: "Wiederbeleben",
  addToWorklist: "Zur Arbeitsliste hinzufügen",
  worklist: "ARBEITSLISTE",
  action: "Aktion",
  purgeWorklist: "Alle aus der Arbeitsliste entfernen",
  extranet: "EXTRANET",
  doingBatch: "Batch-Bearbeitung durchführen...",
  batchFailed: "Batch-Bearbeitung konnte nicht durchgeführt werden.",
  printable: "Druckerfreundliche Version",
  printableOff: "Zurück",
  batchConfirm: "Jetzt Vorsicht! Diese Änderung wird an allen hier aufgeführten Einträgen vorgenommen (insgesamt $X). Sind Sie sicher?",
  narrow: "Schmaler Bildschirm",
  narrowList: "LISTE",
  narrowEditor: "VIEWER/EDITOR",
  emailInUseError: "Diese E-Mail-Adresse wird bereits verwendet.",
  perPage: "Einträge pro Seite",
};
