//Swedish translation by Henrik Nilsson https://www.researchgate.net/profile/Henrik_Nilsson
Screenful.Loc={
  ready: "Klar.",
  find: "Sök",
  reload: "Ladda om",
  cancel: "Avbryt",
  more: "Mer",
  new: "Ny",
  edit: "Redigera",
  save: "Spara",
  delete: "Radera",
  listing: "Hämtar lista...",
  listingFailed: "Kunde inte hämta lista.",
  reading: "Hämtar post...",
  readingFailed: "Det finns ingen sådan post.",
  saving: "Sparar...",
  savingFailed: "Kunde inte spara.",
  deleting: "Raderar...",
  deletingFailed: "Kunde inte radera.",
  deleteConfirm: "Obs! Är du säker?",
  username: "E-postadress",
  password: "Lösenord",
  login: "Logga in",
  loginError: "Felaktig e-postadress eller felaktigt lösenord.",
  logout: "Logga ut",
  anonymous: "anonym användare",
  home: "Hem",
  title: "Titel",
  titleEmpty: "Titel",
  url: "URL",
  urlEmpty: "URL-fältet får inte vara tomt.",
  urlShort: "URL:en måste vara minst tre tecken lång.",
  urlInvalid: "URL:en får inte innehålla andra tecken än a–z, A–Z, 0–9 och bindestreck.",
  urlTaken: "Denna URL används redan.",
  template: "Mall",
  create: "Skapa",
  finished: "Klar",
  changePwd: "Ändra lösenord",
  signup: "Skaffa ett konto",
  forgotPwd: "Glömt ditt lösenord?",
  signupEmail: "För att skaffa ett konto: skicka ett e-brev till",
  newPassword: "Nytt lösenord",
  change: "Ändra",
  passwordChanged: "Ditt lösenord har ändrats.",
  passwordEmpty: "Lösenordsfältet får inte vara tomt.",
  passwordShort: "Lösenordet måste vara minst sex tecken långt.",
  passwordWhitespace: "Lösenordet får inte börja eller sluta med mellanrum.",
  ok: "OK",
  currentUrl: "Nuvarande URL",
  newUrl: "Ny URL",
  upload: "Ladda upp",
  uploadPurge: "Rensa före uppladdning",
  uploadFail: "Uppladdningen misslyckades.",
  uploadSuccess: "Uppladdningen lyckades.",
  history: "Historik",
  version: "Version",
  clone: "Kopiera begreppspost",
  sourceCode: "Källkod",
  invalidSourceCode: "Ogiltig källkod",
  unsavedConfirm: "Du har gjort ändringar som inte sparats. Vill du verkligen förlora dem?",
  doItLater: "Gör detta senare",
  badEmailError: "Felaktig e-postadress",
  forgotPwdEmail: "Skriv in din e-postadress om du har glömt ditt lösenord så skickar vi instruktioner för hur du kan skapa ett nytt.",
  recoverPwd: "Skaffa ett nytt lösenord",
  tokenSent: "Vi har skickat ett e-brev med instruktioner om hur kan återställa ditt lösenord.",
  recoverPwdMsg: "Nu kan du ändra ditt lösenord.",
  changePwdMsg: "Här kan du ändra ditt lösenord.",
  invalidToken: "Denna lösenordslänk gäller inte längre. Den kan ha gått ut eller ha använts tidigare.",
  signupInfoEmail: "Skriv in din e-postadress så skickar vi instruktioner för hur du kan skaffa ett nytt konto.",
  signupButton: "Skapa nytt konto",
  signupTokenSent: "Vi har skickat ett e-brev med instruktioner om hur du kan skapa ett nytt konto.",
  invalidSignupToken: "Denna inloggningslänk är ogiltig. Den kan ha gått ut eller ha använts tidigare.",
  setPwdMsg: "Ange ditt lösenord nu.",
  accountCreated: "Vi har skapat ditt konto. Du kan nu logga in med din e-postadress och ditt valda lösenord.",
  autosave: "Spara automatiskt",
  flagging: "Flaggar...",
  flaggingFailed: "Kunde inte flagga begreppsposten.",
  exactMatches: "Exakta träffar",
  partialMatches: "Delträffar",
  comments: "Kommentarer",
  newComment: "Ny kommentar",
  revive: "Återskapa",
  addToWorklist: "Lägg till i arbetsurval",
  worklist: "ARBETSURVAL",
  action: "Åtgärd",
  purgeWorklist: "Ta bort alla från arbetslistan",
  extranet: "EXTRANÄT",
  doingBatch: "Redigerar satsvis ...",
  batchFailed: "Satsvis redigering misslyckades.",
  printable: "Utskriftsvänlig version",
  printableOff: "Tillbaka",
  batchConfirm: "Obs! Denna ändring kommer att göras i alla begreppsposter som listas här (totalt $X). Är du säker?",
  narrow: "Smal skärm",
  narrowList: "LISTVY",
  narrowEditor: "LÄSVY/REDIGERINGSVY",
  emailInUseError: "Denna e-postadress används redan.",
  perPage: "begreppsposter per sida",
};
