Screenful.Loc={
  ready: "Hazır.",
  find: "Bul",
  reload: "Yeniden yükle",
  cancel: "Vazgeç",
  more: "Daha fazla",
  new: "Yeni",
  edit: "Düzenle",
  save: "Kaydet",
  delete: "Sil",
  listing: "Listeyi getir...",
  listingFailed: "Liste getirilemiyor.",
  reading: "Elemanı çağır...",
  readingFailed: "Böyle bir eleman bulunamadı.",
  saving: "Kaydediliyor...",
  savingFailed: "Kaydedilemedi.",
  deleting: "Siliniyor...",
  deletingFailed: "Silinemedi.",
  deleteConfirm: "Şimdi dikkat! Emin misiniz?",
  username: "E-Posta adresi",
  password: "Şifre",
  login: "Giriş",
  loginError: "Hatalı E-Posta Adresi veya hatalı şifre.",
  logout: "Çıkış",
  anonymous: "anonim kullanıcı",
  home: "Ana sayfa",
  title: "Başlık",
  titleEmpty: "Başlık alanı boş olamaz.",
  url: "URL",
  urlEmpty: "URL alanı boş olamaz.",
  urlShort: "URL en az üç karakter içermeli.",
  urlInvalid: "URL yalnızca a-z, A-Z, 0-9 ve tire içerebilir (Türkçe'ye özgü harfler kullanmayın)",
  urlTaken: "Bu URL daha önce kullanılmış.",
  template: "Şablon",
  create: "Oluştur",
  finished: "Hazır",
  changePwd: "Şifreyi değiştir",
  signup: "Hesap oluştur",
  forgotPwd: "Şifreni mi unuttun?",
  signupEmail: "Hesap oluşturmak için bir E-Posta gönderin:",
  newPassword: "Yeni şifre",
  change: "Değiştir",
  passwordChanged: "Şifreniz değiştirildi!",
  passwordEmpty: "Şifre alanı boş olamaz.",
  passwordShort: "Şifre en az altı karakter içermeli.",
  passwordWhitespace: "Şifre boşluk karakteriyle başlayamaz veya bitemez.",
  ok: "TMM",
  currentUrl: "Geçerli URL",
  newUrl: "Yeni URL",
  upload: "Yükle",
  uploadPurge: "Yüklemeden önce temizle",
  uploadFail: "Yükleme başarısız.",
  uploadSuccess: "Yükleme başarılı.",
  history: "Geçmiş",
  version: "Sürüm",
  clone: "Klonla",
  sourceCode: "Kaynak kodu",
  invalidSourceCode: "Geçersiz kaynak kodu",
  unsavedConfirm: "Yaptığınız değişiklikleri kaydetmediniz. Bunları kaydetmek istemediğinizden emin misiniz?",
  doItLater: "Daha sonra hallet",
  badEmailError: "Hatalı E-Poste adresi.",
  forgotPwdEmail: "Şifrenizi unuttuysanız buraya gireceğiniz E-Posta adresinize bir ileti göndererek yeni şifrenizi nasıl oluşturacağınızı açıklayacağız.",
  recoverPwd: "Yeni şifre iste",
  tokenSent: "Size şifrenizi nasıl sıfırlayacağınız anlatan bir E-Posta gönderdik.",
  recoverPwdMsg: "Şifrenizi şimdi değiştirebilirsiniz.",
  changePwdMsg: "Burada şifrenizi değiştirebilirsiniz.",
  invalidToken: "Şifrenizi sıfırlayacağınız bu bağlantı hatalı. Bu bağlantının süresi dolmuş ya da daha önce kullanılmış.",
  signupInfoEmail: "Yeni bir hesap oluşturmak için buraya gireceğiniz E-Posta adresinize gerekli bilgileri göndereceğiz",
  signupButton: "Yeni hesap oluşturma",
  signupTokenSent: "Yeni bir hesap oluşturmak için gerekli bilgileri içeren bir E-Posta gönderildi.",
  invalidSignupToken: "Bu kayıt bağlantısı geçerli değil. Bu bağlantının süresi dolmuş ya da daha önce kullanılmış.",
  setPwdMsg: "Lütfen şimdi şifrenizi belirleyin.",
  accountCreated: "Hesabınızı oluşturduk. Şimdi E-Posta adresiniz ve şifrenizle giriş yapabilirsiniz.",
  autosave: "OtoKayıt",
  flagging: "İşaretleme...",
  flaggingFailed: "Kayıt işaretlenemiyor.",
  exactMatches: "Tam eşleşme",
  partialMatches: "Kısmi eşleşme",
  comments: "Yorumlar",
  newComment: "Yeni yorum",
  revive: "Kurtarma",
  addToWorklist: "Çalışma listesine ekleme",
  worklist: "ÇALIŞMA LİSTESİ",
  action: "Etkinlik",
  purgeWorklist: "Çalışma listesini boşalt",
  extranet: "DIŞ AĞ",
  doingBatch: "Toplu düzenleme gerçekleştirme...",
  batchFailed: "Toplu düzenleme gerçekleştirilemedi.",
  printable: "Yazdırma dostu görüntüleme",
  printableOff: "Geri",
  batchConfirm: "Şimdi dikkat! Bu değişiklik burada listelenen bütün kayıtlar için uygulanacak (toplam $X). Emin misiniz?",
  narrow: "dar ekran",
  narrowList: "LİSTE",
  narrowEditor: "OKUR/EDİTÖR",
  emailInUseError: "Bu E-Posta adresi daha önce kullanılmış.",
  perPage: "Bir sayfadaki kayıt sayısı",
};
