Screenful.Loc={
  ready: "Klar.",
  find: "Søk",
  reload: "Last på nytt",
  cancel: "Avbryt",
  more: "Mer",
  new: "Ny",
  edit: "Rediger",
  save: "Lagre",
  delete: "Fjern",
  listing: "Henter listen...",
  listingFailed: "Listehenting feilet.",
  reading: "Henter posten...",
  readingFailed: "Ingen slik post.",
  saving: "Lagring pågår...",
  savingFailed: "Lagring feilet.",
  deleting: "Fjerner...",
  deletingFailed: "Fjerning feilet.",
  deleteConfirm: "Forsiktig! Er du sikker?",
  username: "E-postadresse",
  password: "Passord",
  login: "Logg inn",
  loginError: "E-postadresse eller passord var feil.",
  logout: "Logg ut",
  anonymous: "anonym bruker",
  home: "Hjem",
  title: "Tittel",
  titleEmpty: "Tittelen bør ikke være tom.",
  url: "URL",
  urlEmpty: "URL-en bør ikke være tom.",
  urlShort: "Det bør være minst tre tegn i URL-en.",
  urlInvalid: "Tillatte tegn i URL-en er kun a-z, A-Z, 0-9 og bindestrek.",
  urlTaken: "Denne URL-en er allerede i bruk.",
  template: "Mal",
  create: "Opprett",
  finished: "Ferdig",
  changePwd: "Endre passordet ditt",
  signup: "Opprett en brukerkonto",
  forgotPwd: "Har du glemt passordet ditt?",
  signupEmail: "For å få en brukerkonto, send e-post til",
  newPassword: "Nytt passord",
  change: "Endre",
  passwordChanged: "Passordet ditt ble endret.",
  passwordEmpty: "Passordet skal ikke være tomt.",
  passwordShort: "Det bør være minst seks tegn i passordet.",
  passwordWhitespace: "Passordet kan ikke starte eller slutte med et mellomrom.",
  ok: "OK",
  currentUrl: "Nåværende URL",
  newUrl: "Ny URL",
  upload: "Last opp",
  uploadPurge: "Rens før opplastingen",
  uploadFail: "Opplasting feilet.",
  uploadSuccess: "Vellykket opplasting.",
  history: "Historie",
  version: "Versjon",
  clone: "Klone",
  sourceCode: "Kildekode",
  invalidSourceCode: "Ugyldig kildekode",
  unsavedConfirm: "Du har endringer som ikke er blitt lagret. Er du sikker på at du vil miste dem?",
  doItLater: "Gjør senere",
  badEmailError: "Ugyldig e-postadresse.",
  forgotPwdEmail: "Hvis du har glemt passordet ditt, skriv e-postadressen din så at vi kan sende deg informasjon om hvordan du lager et nytt.",
  recoverPwd: "Få et nytt passord",
  tokenSent: "Vi har sent deg en e-post med informasjon om hvordan du kan nullstille passordet ditt.",
  recoverPwdMsg: "Du kan endre passordet ditt nå.",
  changePwdMsg: "Du kan endre passordet ditt her.",
  invalidToken: "Denne lenken til å nullstille passordet er ikke gyldig. Lenken har kanskje forfalt eller blitt brukt tidligere.",
  signupInfoEmail: "Skriv e-postadressen din så at vi kan sende deg instrukser til å få en ny konto.",
  signupButton: "Opprett en ny konto",
  signupTokenSent: "Vi har sent deg en e-post med instruks om hvordan du oppretter en ny konto.",
  invalidSignupToken: "Denne påmeldingslenken er ikke gyldig. Lenken har kanskje forfalt eller blitt brukt tidligere.",
  setPwdMsg: "Vennligst opprett ditt passord.",
  accountCreated: "Din konto er blitt opprettet. Du kan nå logge inn ved å bruke din e-postadresse og ditt passord.",
  autosave: "Automatisk lagring",
  flagging: "Merker med flagg...",
  flaggingFailed: "Flagging av oppføringen mislykket.",
  exactMatches: "Nøyaktige treff",
  partialMatches: "Delvise treff",
  comments: "Kommentarer",
  newComment: "ny kommentar",
  revive: "Oppdater",
  addToWorklist: "Legg til i oppgavelisten",
  worklist: "OPPGAVELISTE",
  action: "Aksjon",
  purgeWorklist: "Fjern alt fra oppgavelisten",
  extranet: "EKSTRANETT",
  doingBatch: "Redigerer i batch...",
  batchFailed: "Redigering i batch feilet.",
  printable: "Utskriftsvennlig versjon",
  printableOff: "Gå tilbake",
  batchConfirm: "Forsiktig! Denne endringen utføres på alle oppføringer som står opplistet her (sammenlagt $X stk.). Er du sikker på dette?",
  narrow: "Smal skjerm",
  narrowList: "LISTE",
  narrowEditor: "VISNING/EDITOR",
  emailInUseError: "Denne e-postaddressen er allerede i bruk.",
  perPage: "oppføringer per side",
};
