Screenful.Loc={
  ready: "Pasiruošęs.",
  find: "Ieškokite",
  reload: "Perkraukite",
  cancel: "Panaikinkite",
  more: "Daugiau",
  new: "Naujas",
  edit: "Redaguokite",
  save: "Išsaugokite",
  delete: "Trinkite",
  listing: "Įkeliamas sąrašas...",
  listingFailed: "Nepavyko įkelti sąrašo.",
  reading: "Įkeliamas elementas...",
  readingFailed: "Nėra tokio elemento.",
  saving: "Saugoma...",
  savingFailed: "Nepavyko išsaugoti.",
  deleting: "Trinama...",
  deletingFailed: "Nepavyko ištrinti.",
  deleteConfirm: "Atsargiai! Ar tikrai to norite?",
  username: "El. pašto adresas",
  password: "Slaptažodis",
  login: "Prisijunkite",
  loginError: "Neteisingas el. pašto adresas arba slaptažodis.",
  logout: "Atsijunkite",
  anonymous: "anoniminis vartotojas",
  home: "Pradžia",
  title: "Pavadinimas",
  titleEmpty: "Pavadinimas negali būti tuščias.",
  url: "Adreso nuoroda",
  urlEmpty: "Adreso nuoroda negali būti tuščia.",
  urlShort: "Adreso nuorodą turi sudaryti mažiausiai trys simboliai.",
  urlInvalid: "Adreso nuorodoje negali būti kitokių simbolių nei a−z, A−Z, 0−9 ir brūkšneliai.",
  urlTaken: "Ši adreso nuoroda jau pasirinkta.",
  template: "Šablonas",
  create: "Sukurkite",
  finished: "Baigta",
  changePwd: "Pakeiskite savo slaptažodį",
  signup: "Gaukite paskyrą",
  forgotPwd: "Pamiršote savo slaptažodį?",
  signupEmail: "Norėdami gauti paskyrą išsiųskite el. laišką į",
  newPassword: "Naujas slaptažodis",
  change: "Pakeiskite",
  passwordChanged: "Jūsų slaptažodis buvo pakeistas.",
  passwordEmpty: "Slaptažodžio laukelis negali būti tuščias.",
  passwordShort: "Slaptažodį turi sudaryti mažiausiai 7 simboliai.",
  passwordWhitespace: "Slaptažodis negali prasidėti ir baigtis tarpu.",
  ok: "Gerai",
  currentUrl: "Dabartinė adreso nuoroda",
  newUrl: "Nauja adreso nuoroda",
  upload: "Įkelkite",
  uploadPurge: "Išvalykite prieš įkėlimą",
  uploadFail: "Įkėlimas nepavyko.",
  uploadSuccess: "Įkėlimas pavyko sėkmingai.",
  history: "Istorija",
  version: "Versija",
  clone: "Dubliuokite",
  sourceCode: "Pirminis kodas",
  invalidSourceCode: "Klaidingas pirminis kodas",
  unsavedConfirm: "Jūs turite neišsaugotų pakeitimų. Ar tikrai norite juos prarasti?",
  doItLater: "Padarykite tai vėliau",
  badEmailError: "Neteisingas el. pašto adresas.",
  forgotPwdEmail: "Jei pamiršote savo slaptažodį, įveskite el. pašto adresą ir mes atsiųsime instrukcijas, kaip susikurti naują.",
  recoverPwd: "Gaukite naują slaptažodį",
  tokenSent: "Mes išsiuntėme jums elektroninį laišką su instrukcijomis, kaip pasikeisti savo slaptažodį.",
  recoverPwdMsg: "Dabar galite pasikeisti savo slaptažodį.",
  changePwdMsg: "Čia galite pasikeisti savo slaptažodį.",
  invalidToken: "Ši slaptažodžio pakeitimo nuoroda yra klaidinga. Ji nebegalioja arba buvo naudota anksčiau.",
  signupInfoEmail: "Norėdami gauti naują paskyrą, įveskite savo el. pašto adresą ir mes atsiųsime jums instrukcijas.",
  signupButton: "Sukurkite naują paskyrą",
  signupTokenSent: "Mes išsiuntėme jums elektroninį laišką su instrukcijomis, kaip sukurti naują paskyrą.",
  invalidSignupToken: "Prisijungimo nuoroda yra klaidinga. Ji nebegalioja arba buvo naudota anksčiau.",
  setPwdMsg: "Dabar nustatykite savo slaptažodį.",
  accountCreated: "Mes sukūrėme jūsų paskyrą. Dabar galite prisijungti su savo el. pašto adresu ir slaptažodžiu.",
  autosave: "Automatinis saugojimas",
  flagging: "Vyksta žymėjimas...",
  flaggingFailed: "Nepavyko pažymėti įrašo.",
  exactMatches: "Tikslūs sutapimai",
  partialMatches: "Daliniai sutapimai",
  comments: "Komentarai",
  newComment: "naujas komentaras",
  revive: "Atkurkite",
  addToWorklist: "Pridėkite prie darbinio sąrašo",
  worklist: "DARBINIS SĄRAŠAS",
  action: "Veiksmai",
  purgeWorklist: "Viską pašalinkite iš darbinio sąrašo",
  extranet: "EKSTRANETAS",
  doingBatch: "Vyksta paketo redagavimas...",
  batchFailed: "Nepavyko atlikti paketo redagavimo.",
  printable: "Spausdinimo versija",
  printableOff: "Atgal",
  batchConfirm: "Dabar atsargiai! Šis pakeitimas bus padarytas visiems čia išvardytiems įrašams (iš viso - $X). Ar tikrai to norite?",
  narrow: "Siauras ekranas",
  narrowList: "SĄRAŠAS",
  narrowEditor: "ŽIŪRYKLĖ / REDAKTORIUS",
  emailInUseError: "Šis el. adresas jau yra naudojamas.",
  perPage: "įrašai puslapyje",
};
