Screenful.Loc={
  ready: "Prest.",
  find: "Aurkitu",
  reload: "Berriz kargatu",
  cancel: "Deuseztatu",
  more: "Gehiago",
  new: "Berria",
  edit: "Editatu",
  save: "Gorde",
  delete: "Ezabatu",
  listing: "Zerrenda eskuratzen...",
  listingFailed: "Ezin izan da zerrenda eskuratu.",
  reading: "Elementua eskuratzen...",
  readingFailed: "Ez dago horrelako elementurik.",
  saving: "Gordetzen...",
  savingFailed: "Ezin izan da gorde.",
  deleting: "Ezabatzen...",
  deletingFailed: "Ezin izan da ezabatu.",
  deleteConfirm: "Adi! Ziur zaude?",
  username: "Helbide elektronikoa",
  password: "Pasahitza",
  login: "Sartu",
  loginError: "Helbide elektroniko edo pasahitza okerra.",
  logout: "Irten",
  anonymous: "erabiltzaile anonimoa",
  home: "Hasiera",
  title: "Izenburua",
  titleEmpty: "Izenburua ezin da hutsik egon.",
  url: "URL",
  urlEmpty: "URLa ezin da hutsik egon.",
  urlShort: "URLak hiru karaktere izan behar ditu gutxienez.",
  urlInvalid: "URLak ez ditu a-z, A-Z, 0-9 eta marratxoak ez diren karaktererik.",
  urlTaken: "URL hau dagoeneko hartuta dago.",
  template: "Txantiloia",
  create: "Sortu",
  finished: "Amaituta",
  changePwd: "Zure pasahitza aldatu.",
  signup: "Kontu bat lortu.",
  forgotPwd: "Pasahitza ahaztu duzu?",
  signupEmail: "Kontu bat lortzeko mezu elektroniko bat bidali … -ra",
  newPassword: "Pasahitza berria",
  change: "Aldatu",
  passwordChanged: "Zure pasahitza aldatu da.",
  passwordEmpty: "Pasahitza ezin da hutsik egon.",
  passwordShort: "Pasahitzak sei karaktere izan behar ditu gutxienez.",
  passwordWhitespace: "Pasahitzak ez luke zuriune batekin hasi edo amaitu behar.",
  ok: "Ados",
  currentUrl: "Uneko URLa",
  newUrl: "URL berria",
  upload: "Igo",
  uploadPurge: "Purgatu igo aurretik",
  uploadFail: "Igoerak huts egin du.",
  uploadSuccess: "Igoerak arrakasta izan du.",
  history: "Historia",
  version: "Bertsio",
  clone: "Klon",
  sourceCode: "Iturburu-kodea",
  invalidSourceCode: "Iturburu-kodea ez da baliozkoa",
  unsavedConfirm: "Gorde gabeko aldaketak dituzu. Ziur galdu nahi dituzula?",
  doItLater: "Egin ezazu geroago",
  badEmailError: "Helbide elektroniko okerra.",
  forgotPwdEmail: "Pasahitza ahaztu baduzu, sartu zure helbide elektronikoa eta berri bat sortzeko argibideak bidaliko dizkizugu.",
  recoverPwd: "Lortu pasahitz berri bat",
  tokenSent: "Mezu elektroniko bat bidali dizugu zure pasahitza berrezartzeko argibideekin.",
  recoverPwdMsg: "Orain pasahitza alda dezakezu.",
  changePwdMsg: "Hemen pasahitza alda dezakezu.",
  invalidToken: "Pasahitza berrezartzeko esteka hau baliogabea da. Baliteke iraungita egotea edo aurretik erabili izana.",
  signupInfoEmail: "Kontu berri bat lortzeko, sartu zure helbide elektronikoa eta argibideak bidaliko dizkizugu.",
  signupButton: "Sortu kontu berria",
  signupTokenSent: "Mezu elektroniko bat bidali dizugu kontu berri bat sortzeko argibideekin.",
  invalidSignupToken: "Erregistratzeko esteka hau baliogabea da. Baliteke iraungita egotea edo aurretik erabili izana.",
  setPwdMsg: "Mesedez, konfiguratu zure pasahitza orain.",
  accountCreated: "Zure kontua sortu dugu. Orain zure helbide elektronikoa eta pasahitzarekin saioa has dezakezu.",
  autosave: "Gorde automatikoki",
  flagging: "Markatzen...",
  flaggingFailed: "Ezin izan da sarrera markatu.",
  exactMatches: "Bateragarritasun zehatzak",
  partialMatches: "Bateragarritasun partziala",
  comments: "Iruzkinak",
  newComment: "iruzkin berria",
  revive: "Berrabiarazi",
  addToWorklist: "Lan zerrendara gehitu",
  worklist: "LAN ZERRENDA",
  action: "Ekintza",
  purgeWorklist: "Kendu guztiak lan zerrendatik",
  extranet: "EXTRANET",
  doingBatch: "Sortakako edizioa egiten...",
  batchFailed: "Ezin izan da multzoka editatu.",
  printable: "Inprimatzeko moduko bertsioa",
  printableOff: "Itzuli",
  batchConfirm: "Adi! Aldaketa hau hemen zerrendatutako sarrera guztietan egingo da ($X guztira). Ziur zaude?",
  narrow: "Pantaila estua",
  narrowList: "ZERRENDA",
  narrowEditor: "IKUSLE/EDITORE",
  emailInUseError: "Helbide elektroniko hau dagoeneko erabileran dago.",
  perPage: "orrialde bakoitzeko sarrerak",
};
