Screenful.Loc={
  ready: "Klaar.",
  find: "Zoeken",
  reload: "Herladen",
  cancel: "Annuleren",
  more: "Meer",
  new: "Nieuw",
  edit: "Bewerken",
  save: "Opslaan",
  delete: "Verwijderen",
  listing: "Lijst maken...",
  listingFailed: "Geen lijst gevonden.",
  reading: "Zoeken naar item...",
  readingFailed: "Geen item gevonden.",
  saving: "Opslaan...",
  savingFailed: "Opslaan mislukt.",
  deleting: "Verwijderen...",
  deletingFailed: "Verwijderen mislukt.",
  deleteConfirm: "Opgelet! Bent u zeker?",
  username: "E-mailadres",
  password: "Wachtwoord",
  login: "Aanmelden",
  loginError: "Onjuist e-mailadres of wachtwoord.",
  logout: "Uitloggen",
  anonymous: "anonieme gebruiker",
  home: "Home",
  title: "Titel",
  titleEmpty: "De titel mag niet leeg zijn.",
  url: "URL",
  urlEmpty: "De URL mag niet leeg zijn.",
  urlShort: "De URL moet minstens drie karakters lang zijn.",
  urlInvalid: "De URL mag geen andere tekens bevatten dan a-z, A-Z, 0-9 en koppeltekens.",
  urlTaken: "Deze URL is al gebruikt.",
  template: "Sjabloon",
  create: "Creëren",
  finished: "Voltooid",
  changePwd: "Uw wachtwoord wijzigen",
  signup: "Een account aanmaken",
  forgotPwd: "Bent u uw wachtwoord vergeten?",
  signupEmail: "Om een account te krijgen stuur een e-mail naar",
  newPassword: "Nieuw wachtwoord",
  change: "Veranderen",
  passwordChanged: "Uw wachtwoord is gewijzigd.",
  passwordEmpty: "Het wachtwoord mag niet leeg zijn.",
  passwordShort: "Het wachtwoord moet minstens zes tekens lang zijn.",
  passwordWhitespace: "Het wachtwoord mag niet beginnen of eindigen met een spatie.",
  ok: "OK",
  currentUrl: "Huidige URL",
  newUrl: "Nieuwe URL",
  upload: "Uploaden",
  uploadPurge: "Verwijderen voor het uploaden",
  uploadFail: "De upload is mislukt.",
  uploadSuccess: "De upload is geslaagd.",
  history: "Geschiedenis",
  version: "Versie",
  clone: "Kloon",
  sourceCode: "Broncode",
  invalidSourceCode: "Ongeldige broncode",
  unsavedConfirm: "U hebt niet-opgeslagen veranderingen. Bent u zeker dat u ze wilt verliezen?",
  doItLater: "Doe het later",
  badEmailError: "Onjuist e-mailadres.",
  forgotPwdEmail: "Als u uw wachtwoord bent vergeten, vul dan uw e-mailadres in zodat wij u de instructies kunnen doorsturen om een nieuw wachtwoord in te stellen.",
  recoverPwd: "Krijg een nieuw wachtwoord",
  tokenSent: "We hebben u een e-mail gestuurd met instructies voor het resetten van uw wachtwoord.",
  recoverPwdMsg: "U kunt nu uw wachtwoord wijzigen.",
  changePwdMsg: "U kunt hier uw wachtwoord wijzigen.",
  invalidToken: "Deze link om uw wachtwoord te resetten is ongeldig. Het kan zijn dat het verlopen is of dat het al gebruikt is.",
  signupInfoEmail: "Om een nieuw account te krijgen, gelieve uw e-mailadres in te vullen zodat wij u instructies kunnen doorsturen.",
  signupButton: "Een nieuw account aanmaken",
  signupTokenSent: "We hebben u een e-mail gestuurd met instructies voor het aanmaken van een nieuw account.",
  invalidSignupToken: "Deze link om een nieuw account aan te maken is ongeldig. Het kan zijn dat het verlopen is of dat het al gebruikt is.",
  setPwdMsg: "Stel nu uw wachtwoord in.",
  accountCreated: "We hebben uw account aangemaakt. U kunt nu inloggen met uw e-mailadres en wachtwoord.",
  autosave: "Automatisch opslaan",
  flagging: "Met vlaggen markeren...",
  flaggingFailed: "Markeren van het fiche is mislukt.",
  exactMatches: "Exacte matches",
  partialMatches: "Gedeeltelijke matches",
  comments: "Opmerkingen",
  newComment: "nieuwe opmerking",
  revive: "Herstellen",
  addToWorklist: "Toevoegen aan werklijst",
  worklist: "WERKLIJST",
  action: "Actie",
  purgeWorklist: "Alles van de werklijst verwijderen",
  extranet: "EXTRANET",
  doingBatch: "Uitvoeren van batch-bewerking..",
  batchFailed: "Geen batch-bewerking uitgevoerd.",
  printable: "Printervriendelijke versie",
  printableOff: "Terug",
  batchConfirm: "Opgelet! Deze wijziging zal worden aangebracht op alle fiches die hier vermeld zijn ($X in totaal). Bent u zeker?",
  narrow: "Smal scherm",
  narrowList: "LIJST",
  narrowEditor: "KIJKER/EDITOR",
  emailInUseError: "Dit e-mailadres is al in gebruik.",
  perPage: "translation required",
};
