Screenful.Loc={
  ready: "Listo.",
  find: "Encontrar",
  reload: "Volver a cargar",
  cancel: "Cancelar",
  more: "Más",
  new: "Nuevo",
  edit: "Editar",
  save: "Guardar",
  delete: "Eliminar",
  listing: "Obteniendo listado...",
  listingFailed: "No se pudo obtener el listado.",
  reading: "Obteniendo elemento...",
  readingFailed: "No existe tal elemento.",
  saving: "Guardando...",
  savingFailed: "No se pudo guardar.",
  deleting: "Eliminando...",
  deletingFailed: "No se pudo eliminar.",
  deleteConfirm: "¡Cuidado! ¿Estás seguro/a?",
  username: "Dirección de correo electrónico",
  password: "Contraseña",
  login: "Iniciar sesión",
  loginError: "Dirección de correo electrónico o contraseña incorrectos.",
  logout: "Cerrar sesión",
  anonymous: "Usuario/a anónimo/a",
  home: "Página de inicio",
  title: "Título",
  titleEmpty: "El título no puede quedar vacío.",
  url: "Dirección URL",
  urlEmpty: "La dirección URL no puede quedar vacía.",
  urlShort: "La dirección URL ha de tener un mínimo de tres caracteres.",
  urlInvalid: "La dirección URL no puede contener otros caracteres que no sean a-z, A-Z, 0-9 o guiones.",
  urlTaken: "Esta dirección URL ya existe.",
  template: "Plantilla",
  create: "Crear",
  finished: "Finalizado",
  changePwd: "Cambia tu contraseña",
  signup: "Crea una cuenta",
  forgotPwd: "¿Olvidaste la contraseña?",
  signupEmail: "Para crear una cuenta manda un correo a",
  newPassword: "Nueva contraseña",
  change: "Cambiar",
  passwordChanged: "La contraseña se ha cambiado con éxito.",
  passwordEmpty: "La contraseña no puede quedar vacía.",
  passwordShort: "La contraseña ha de tener un mínimo de seis caracteres.",
  passwordWhitespace: "La contraseña no puede empezar o terminar con un espacio.",
  ok: "OK",
  currentUrl: "Dirección URL actual",
  newUrl: "Nueva dirección URL",
  upload: "Subir",
  uploadPurge: "Vaciar antes de subir",
  uploadFail: "Error al subir archivo.",
  uploadSuccess: "El archivo se ha subido con éxito.",
  history: "Historial",
  version: "Versión",
  clone: "Clonar",
  sourceCode: "Código fuente",
  invalidSourceCode: "Código fuente inválido",
  unsavedConfirm: "Se perderán los cambios sin guardar. ¿Deseas descartarlos?",
  doItLater: "Hacerlo más tarde",
  badEmailError: "Dirección de correo electrónico incorrecta.",
  forgotPwdEmail: "Si has olvidado la contraseña, escribe tu dirección de correo electrónico y te enviaremos las instrucciones para establecer una nueva.",
  recoverPwd: "Establecer nueva contraseña",
  tokenSent: "Te hemos enviado un correo electrónico con las instrucciones para restablecer la contraseña.",
  recoverPwdMsg: "Ya puedes cambiar la contraseña.",
  changePwdMsg: "Aquí puedes cambiar la contraseña.",
  invalidToken: "El enlace para restablecer la contraseña no es válido porque ha caducado o ya se ha usado con anterioridad.",
  signupInfoEmail: "Para abrir una cuenta nueva, escribe tu dirección de correo electrónico y te enviaremos las instrucciones.",
  signupButton: "Crear cuenta nueva",
  signupTokenSent: "Te hemos enviado un correo electrónico con las instrucciones para crear una cuenta nueva.",
  invalidSignupToken: "El enlace para crear una cuenta nueva no es válido porque ha caducado o ya se ha usado con anterioridad.",
  setPwdMsg: "Ahora elige tu contraseña, por favor.",
  accountCreated: "Hemos creado tu cuenta. Ahora puedes iniciar sesión con tu dirección correo electrónico y contraseña.",
  autosave: "Autoguardado",
  flagging: "Marcando...",
  flaggingFailed: "No se pudo marcar la entrada.",
  exactMatches: "Coincidencias exactas",
  partialMatches: "Coincidencias parcialesя",
  comments: "Comentarios",
  newComment: "Nuevo comentario",
  revive: "Recuperar",
  addToWorklist: "Añadir a la lista de tareas",
  worklist: "LISTA DE TAREAS",
  action: "Acción",
  purgeWorklist: "Vaciar la lista de tareas",
  extranet: "EXTRANET",
  doingBatch: "Realizando edición por lotes...",
  batchFailed: "No se pudo realizar la edición por lotes.",
  printable: "Versión para imprimir",
  printableOff: "Atrás",
  batchConfirm: "¡Cuidado! Este cambio afectará a todo el listado de entradas ($X en total). ¿Estás seguro/a?",
  narrow: "Estrechar pantalla",
  narrowList: "LISTADO",
  narrowEditor: "VISTA/EDICIÓN",
  emailInUseError: "Esta dirección de correo electrónico ya está en uso.",
  perPage: "entradas por página",
};
