Screenful.Loc={
  ready: "Yn barod.",
  find: "Chwilio",
  reload: "Ail-lwytho",
  cancel: "Canslo",
  more: "Mwy",
  new: "Newydd",
  edit: "Golygu",
  save: "Arbed",
  delete: "Dileu",
  listing: "Wrthi'n adalw'r rhestr...",
  listingFailed: "Methwyd adalw'r rhestr.",
  reading: "Wrthi'n adalw'r eitem...",
  readingFailed: "Nid yw'r eitem yn bodoli.",
  saving: "Wrthi'n arbed...",
  savingFailed: "Methwyd arbed.",
  deleting: "Wrthi'n dileu...",
  deletingFailed: "Methwyd dileu.",
  deleteConfirm: "Gofal! Ydych chi'n siŵr?",
  username: "Cyfeiriad e-bost",
  password: "Cyfrinair",
  login: "Mewngofnodi",
  loginError: "E-bost neu gyfrinair anghywir.",
  logout: "Allgofnodi",
  anonymous: "defnyddiwr di-enw",
  home: "Hafan",
  title: "Teitl",
  titleEmpty: "Ni ddylai'r teitl fod yn wag.",
  url: "URL",
  urlEmpty: "Ni ddylai'r URL fod yn wag.",
  urlShort: "Dylia'r URL fod o leiaf tri nod o hyd.",
  urlInvalid: "Ni ddylai'r URL gynnwys nodau heblaw a-z, A-Z, 0-9 a chysylltnodau.",
  urlTaken: "Defnyddiwyd yr URL hwn eisoes.",
  template: "Templed",
  create: "Creu",
  finished: "Wedi gorffen",
  changePwd: "Newidiwch eich cyfrinair",
  signup: "Mynnwch gyfrif",
  forgotPwd: "Wedi anghofio eich cyfrinair?",
  signupEmail: "Er mwyn cael cyfrif, e-bostiwch",
  newPassword: "Cyfrinair newydd",
  change: "Newid",
  passwordChanged: "Newidiwyd eich cyfrinair.",
  passwordEmpty: "Ni ddylai'r cyfrinair fod yn wag.",
  passwordShort: "Dylai'r cyfrinair fod o leiaf chwe nod o hyd.",
  passwordWhitespace: "Ni ddylai'r cyfrinair gychwyn na gorffen â bwlch.",
  ok: "Iawn",
  currentUrl: "URL cyfredol",
  newUrl: "URL newydd",
  upload: "Uwchlwytho",
  uploadPurge: "Clirio cyn uwchlwytho",
  uploadFail: "Methodd yr uwchlwytho.",
  uploadSuccess: "Roedd yr uwchlwytho'n llwyddiannus.",
  history: "Hanes",
  version: "Fersiwn",
  clone: "Dyblygu",
  sourceCode: "Cod ffynhonnell",
  invalidSourceCode: "Cod ffynhonnell annilys",
  unsavedConfirm: "Mae gennych newidiadau heb eu harbed. Ydych chi'n siŵr eich bod am eu colli?",
  doItLater: "Gwneud hyn rywbryd eto",
  badEmailError: "Cyfeiriad e-bost anghywir.",
  forgotPwdEmail: "Os ydych chi wedi anghofio'ch cyfrinair, rhowch eich cyfeiriad e-bost ac fe anfonwn gyfarwyddiadau sut i greu un newydd atoch.",
  recoverPwd: "Mynnu cyfrinair newydd",
  tokenSent: "Anfonwyd e-bost atoch yn cynnwys cyfarwyddiadau sut i ailosod eich cyfrinair.",
  recoverPwdMsg: "Gallwch newid eich cyfrinair nawr.",
  changePwdMsg: "Gallwch newid eich cyfrinair yma.",
  invalidToken: "Mae'r ddolen ailosod cyfrinair yma'n annilys. Efallai ei fod wedi darfod neu ei fod wedi cael ei ddefnyddio eisoes.",
  signupInfoEmail: "I gael cyfrif newydd, mewnbynnwch eich cyfeiriad e-bost ac fe anfonwn gyfarwyddiadau atoch.",
  signupButton: "Creu cyfrif newydd",
  signupTokenSent: "Anfonwyd e-bost atoch yn cynnwys cyfarwyddiadau sut i greu cyfrif newydd.",
  invalidSignupToken: "Mae'r ddolen gofrestru yma'n annilys. Efallai ei fod wedi darfod neu ei fod wedi cael ei ddefnyddio eisoes.",
  setPwdMsg: "Gosodwch eich cyfrinair os gwelwch yn dda.",
  accountCreated: "Crëwyd eich cyfrif. Gallwch fewngofnodi gan ddefnyddio'ch cyfeiriad e-bost a'ch cyfrinair.",
  autosave: "Arbed yn awtomatig",
  flagging: "Wrthi'n  clustnodi...",
  flaggingFailed: "Methwyd clustnodi'r cofnod.",
  exactMatches: "Cyfatebiaethau union",
  partialMatches: "Cyfatebiaethau rhannol",
  comments: "Sylwadau",
  newComment: "sylw newydd",
  revive: "Adfer",
  addToWorklist: "Ychwanegu i'r rhestr waith",
  worklist: "RHESTR WAITH",
  action: "Gweithred",
  purgeWorklist: "Tynnu'r cyfan o'r rhestr waith",
  extranet: "ALLRWYD",
  doingBatch: "Wrthi'n gweithredu'r sypyn newidiadau...",
  batchFailed: "Methwyd gweithredu'r sypyn newidiadau.",
  printable: "Fersiwn ar gyfer argraffu",
  printableOff: "Yn ôl",
  batchConfirm: "Gofal! Caiff y newid hwn ei wneud ar yr holl gofnodion a restrir yma ($X ohonynt). Ydych chi'n siŵr?",
  narrow: "Sgrin gul",
  narrowList: "RHESTR",
  narrowEditor: "SYLLWR/GOLYGYDD",
  emailInUseError: "Mae'r cyfeiriad e-bost hwn eisoes yn cael ei ddefnyddio.",
};
