Screenful.Loc={
  ready: "Spremno.",
  find: "Traži",
  reload: "Ponovno učitaj",
  cancel: "Odustani",
  more: "Više",
  new: "Novo",
  edit: "Uredi",
  save: "Spremi",
  delete: "Izbriši",
  listing: "Dohvaćanje popisa...",
  listingFailed: "Dohvaćanje popisa nije uspjelo.",
  reading: "Dohvaćanje stavke...",
  readingFailed: "Nema takve stavke.",
  saving: "Spremanje...",
  savingFailed: "Spremanje nije uspjelo.",
  deleting: "Brisanje...",
  deletingFailed: "Brisanje nije uspjelo.",
  deleteConfirm: "Oprez! Jeste li sigurni?",
  username: "Adresa e-pošte",
  password: "Lozinka",
  login: "Prijava",
  loginError: "Netočna adresa e-pošte ili lozinka.",
  logout: "Odjava",
  anonymous: "anonimni korisnik",
  home: "Početna stranica",
  title: "Naslov",
  titleEmpty: "Naslov ne smije biti prazan.",
  url: "URL",
  urlEmpty: "URL ne smije biti prazan.",
  urlShort: "URL treba imati najmanje tri znaka.",
  urlInvalid: "URL ne smije sadržavati znakove osim a-z, A-Z, 0-9 i spojnice.",
  urlTaken: "Ovaj URL već postoji.",
  template: "Predložak",
  create: "Izradi",
  finished: "Dovršeno",
  changePwd: "Promijenite lozinku",
  signup: "Otvorite korisnički račun",
  forgotPwd: "Zaboravili ste lozinku?",
  signupEmail: "Da biste otvorili račun, pošaljite e-poštu na",
  newPassword: "Nova lozinka",
  change: "Promijeni",
  passwordChanged: "Vaša lozinka je promijenjena.",
  passwordEmpty: "Lozinka ne smije biti prazna.",
  passwordShort: "Lozinka bi trebala imati najmanje šest znakova.",
  passwordWhitespace: "Lozinka ne smije počinjati ili završavati razmakom.",
  ok: "OK",
  currentUrl: "Trenutni URL",
  newUrl: "Novi URL",
  upload: "Prenesi",
  uploadPurge: "Očisti prije prijenosa",
  uploadFail: "Prijenos nije uspio.",
  uploadSuccess: "Prijenos je uspješno završen.",
  history: "Povijest",
  version: "Verzija",
  clone: "Klon",
  sourceCode: "Izvorni kod",
  invalidSourceCode: "Nevažeći izvorni kod",
  unsavedConfirm: "Ima promjena koje nisu spremljene. Jeste li sigurni da ih želite izgubiti?",
  doItLater: "Učinite to kasnije",
  badEmailError: "Netočna adresa e-pošte.",
  forgotPwdEmail: "Ako ste zaboravili lozinku, unesite svoju adresu e-pošte i poslat ćemo vam upute kako izraditi novu.",
  recoverPwd: "Izradite novu lozinkua",
  tokenSent: "Poslali smo vam e-poštu s uputama kako ponovno postaviti lozinku.",
  recoverPwdMsg: "Sada možete promijeniti lozinku.",
  changePwdMsg: "Ovdje možete promijeniti lozinku.",
  invalidToken: "Ova veza za ponovno postavljanje lozinke je nevažeća. Možda je istekla ili je već korištena.",
  signupInfoEmail: "Da biste izradili novi račun, unesite svoju adresu e-pošte i poslat ćemo vam upute.",
  signupButton: "Izradite novi račun",
  signupTokenSent: "Poslali smo vam e-poštu s uputama kako ponovno izraditi račun.",
  invalidSignupToken: "Ova poveznica za registraciju je nevažeća. Možda je istekla ili je već korištena.",
  setPwdMsg: "Molimo da sada postavite svoju lozinku.",
  accountCreated: "Izradili smo vaš račun. Sada se možete prijaviti s adresom e-pošte i lozinkom.",
  autosave: "Automatsko spremanje",
  flagging: "Označavanje...",
  flaggingFailed: "Označavanje natuknice nije uspjelo.",
  exactMatches: "Točna podudaranja",
  partialMatches: "Djelomična podudaranja",
  comments: "Komentari",
  newComment: "novi komentar",
  revive: "Obnovi",
  addToWorklist: "Dodaj na radni popis",
  worklist: "RADNI POPIS",
  action: "Radnja",
  purgeWorklist: "Ukloni sve s radnog popisa",
  extranet: "EKSTRANET",
  doingBatch: "Grupno uređivanje...",
  batchFailed: "Grupno uređivanje nije uspjelo.",
  printable: "Verzija prilagođena pisaču",
  printableOff: "Natrag",
  batchConfirm: "Oprez! Ova promjena odrazit će se na sve ovdje navedene natuknice (ukupno $X). Jeste li sigurni?",
  narrow: "Suzi zaslon",
  narrowList: "POPIS",
  narrowEditor: "GLEDATELJ/UREDNIK",
  emailInUseError: "Ova adresa e-pošte već je u upotrebi.",
  perPage: "broj natuknica po stranici",
};
