Screenful.Loc={
  ready: "Prêt.",
  find: "Trouver",
  reload: "Actualiser",
  cancel: "Annuler",
  more: "Plus",
  new: "Ajouter",
  edit: "Éditer",
  save: "Enregistrer",
  delete: "Supprimer",
  listing: "Chargement de la liste en cours…",
  listingFailed: "Le chargement de la liste a échoué.",
  reading: "Chargement de l’élément en cours…",
  readingFailed: "L’élément demandé n’existe pas.",
  saving: "Enregistrement en cours…",
  savingFailed: "L’enregistrement a échoué.",
  deleting: "Suppression en cours…",
  deletingFailed: "La suppression a échoué.",
  deleteConfirm: "Attention! Est-ce bien ce que vous voulez?",
  username: "Adresse courriel",
  password: "Mot de passe",
  login: "Se connecter",
  loginError: "Adresse courriel ou mot de passe incorrects.",
  logout: "Se déconnecter",
  anonymous: "utilisateur anonyme",
  home: "Page d’accueil",
  title: "Nom de la base terminologique",
  titleEmpty: "Vous devez donner un nom à votre base terminologique.",
  url: "Adresse URL",
  urlEmpty: "Vous devez entrer une adresse URL.",
  urlShort: "L’adresse URL doit comporter au moins trois caractères.",
  urlInvalid: "L'URL doit contenir uniquement des minuscules ou majuscules (de A à Z), des chiffres (de 0 à 9) et des traits d'union.",
  urlTaken: "Cette adresse URL est déjà prise.",
  template: "Modèle",
  create: "Créer",
  finished: "Processus terminé",
  changePwd: "Modifier le mot de passe",
  signup: "Créer un compte",
  forgotPwd: "Mot de passe oublié?",
  signupEmail: "Pour obtenir un compte, écrivez-nous à",
  newPassword: "Nouveau mot de passe",
  change: "Confirmer",
  passwordChanged: "Votre mot de passe a été modifié avec succès.",
  passwordEmpty: "Vous devez entrer un mot de passe.",
  passwordShort: "Le mot de passe doit comporter au moins six caractères.",
  passwordWhitespace: "Le mot de passe ne doit ni commencer ni se terminer par une espace.",
  ok: "OK",
  currentUrl: "Adresse URL actuelle",
  newUrl: "Nouvelle adresse URL",
  upload: "Téléverser",
  uploadPurge: "Vider avant de téléverser.",
  uploadFail: "Le téléversement a échoué.",
  uploadSuccess: "Le téléversement a été effectué avec succès.",
  history: "Historique",
  version: "Version",
  clone: "Dupliquer",
  sourceCode: "Code source",
  invalidSourceCode: "Code source invalide",
  unsavedConfirm: "Vos modifications n’ont pas été enregistrées. Souhaitez-vous vraiment les abandonner?",
  doItLater: "Le faire plus tard",
  badEmailError: "Cette adresse courriel n’est pas valide.",
  forgotPwdEmail: "Si vous avez oublié votre mot de passe, saisissez votre adresse courriel. Nous vous y enverrons la marche à suivre pour en créer un nouveau.",
  recoverPwd: "Obtenir un nouveau mot de passe",
  tokenSent: "Nous vous avons envoyé un courriel contenant la marche à suivre pour réinitialiser votre mot de passe.",
  recoverPwdMsg: "Vous pouvez maintenant modifier votre mot de passe.",
  changePwdMsg: "Vous pouvez modifier votre mot de passe.",
  invalidToken: "Ce lien destiné à la réinitialisation du mot de passe n’est plus valide. Il se peut qu’il soit périmé ou qu’il ait déjà été utilisé.",
  signupInfoEmail: "Pour créer un compte, saisissez votre adresse courriel. Nous vous enverrons la marche à suivre à cette adresse.",
  signupButton: "Créer un compte",
  signupTokenSent: "Nous vous avons envoyé un courriel contenant la marche à suivre pour créer votre compte.",
  invalidSignupToken: "Ce lien destiné à la création d'un compte Terminologue n’est plus valide. Il se peut qu’il soit périmé ou qu’il ait déjà été utilisé.",
  setPwdMsg: "Veuillez choisir un mot de passe.",
  accountCreated: "Nous avons créé votre compte. Vous pouvez désormais vous y connecter en saisissant votre adresse courriel et votre mot de passe.",
  autosave: "Enregistrement automatique",
  flagging: "Signalement d'une fiche en cours…",
  flaggingFailed: "Le signalement de la fiche a échoué.",
  exactMatches: "Correspondances exactes",
  partialMatches: "Correspondances partielles",
  comments: "Commentaires",
  newComment: "nouveau commentaire",
  revive: "Restaurer",
  addToWorklist: "Ajouter à la liste de travail",
  worklist: "LISTE DE TRAVAIL",
  action: "Actions",
  purgeWorklist: "Retirer toutes les fiches de la liste de travail",
  extranet: "EXTRANET",
  doingBatch: "Modification des fiches en cours…",
  batchFailed: "La modification des fiches a échoué.",
  printable: "Version imprimable",
  printableOff: "Retour",
  batchConfirm: "Attention! Cette modification s’appliquera à toutes les fiches affichées ci-dessous ($X fiches au total). Est-ce bien ce que vous voulez?",
  narrow: "Agrandir l'écran",
  narrowList: "LISTE DES FICHES",
  narrowEditor: "VISUALISATION ET ÉDITION",
  emailInUseError: "Cette adresse courriel est déjà associée à un compte.",
  perPage: "fiches par page",
};
