Screenful.Loc={
  ready: "Pasiruošęs.",
  find: "Ieškokite",
  reload: "Perkraukte",
  cancel: "Panaikinkite",
  more: "Daugiau",
  new: "Naujas",
  edit: "Redaguokite",
  save: "Saugokte",
  delete: "Trinkite",
  listing: "Gaunamas sąrašas...",
  listingFailed: "Nepavyko gauti sąrašo.",
  reading: "Gaunamas elementas...",
  readingFailed: "Nėra tokio elemento.",
  saving: "Saugojama...",
  savingFailed: "Nepavyko užsaugoti.",
  deleting: "Trinama...",
  deletingFailed: "Nepavyko ištrinti.",
  deleteConfirm: "Atsargiai! Ar tikrai to norite?",
  username: "El. pašto adresas",
  password: "Slaptažodis",
  login: "Prisijunkite",
  loginError: "Neteisingas el. pašto adresas arba slaptažodis.",
  logout: "Atsijunkite",
  anonymous: "anoniminis vartotojas",
  home: "Pradžia",
  title: "Pavadinimas",
  titleEmpty: "Pavadinimas negali būti tuščias",
  url: "Adreso nuoroda",
  urlEmpty: "Adreso nuoroda negali būti tuščia",
  urlShort: "Adreso nuorodą turi sudaryti mažiausiai trys simboliai.",
  urlInvalid: "Adreso nuorodoje negali būti kitų simbolių nei a-z, A-Z, 0-9 ir brūkšneliai.",
  urlTaken: "Ši adreso nuoroda jau pasirinkta.",
  template: "Šablonas",
  create: "Sukurkite",
  finished: "Baigė",
  changePwd: "Pakeiskite savo slaptažodį",
  signup: "Gaukite paskyrą",
  forgotPwd: "Ar užmiršai savo slaptažodį?",
  signupEmail: "Norėdami gauti paskyrą išsiųskite el. laišką į",
  newPassword: "Naujas slaptažodis",
  change: "Pakeiskite",
  passwordChanged: "Jūsų slaptažodis buvo pakeistas.",
  passwordEmpty: "Slaptažodžio laukelis negali būti tuščias.",
  passwordShort: "Slaptažodį turi sudaryti mažiausiai 7 simboliai.",
  passwordWhitespace: "Slaptažodis negali prasidėti ir baigtis tarpu.",
  ok: "Gerai",
  currentUrl: "Dabartinė nuoroda",
  newUrl: "Nauja nuoroda",
  upload: "Įkelkite",
  uploadPurge: "Išvalykite prieš įkėlimą",
  uploadFail: "Įkėlimas nepavyko.",
  uploadSuccess: "Įkėlimas sėkmingas.",
  history: "Istorija",
  version: "Versija",
  clone: "Klonas",
  sourceCode: "Pirminis kodas",
  invalidSourceCode: "Klaidingas pirminis kodas",
  unsavedConfirm: "Jūs turite neužsaugotų pakeitumų. Ar tikrai norite juos prarasti?",
  doItLater: "Padarykite tai vėliau.",
  badEmailError: "Neteisingas el. pašto adresas.",
  forgotPwdEmail: "Jei pamiršote savo slaptažodį, įveskite el. pašto adresą ir mes atsiųsime instrukcijas, kaip susikurti naują.",
  recoverPwd: "Gaukite naują slaptažodį",
  tokenSent: "Mes išsiuntėme jums elektroninį laišką su instrukcijomis kaip pasikeisti savo slaptažodį.",
  recoverPwdMsg: "Dabar galite pasikeisti savo slaptažodį.",
  changePwdMsg: "Čia galite pasikeisti savo slaptažodį.",
  invalidToken: "Ši slaptažodžio pasikeitimo nuoroda yra klaidinga. Ji negalioja arba buvo panaudota anksčiau.",
  signupInfoEmail: "Tam, kad gautumėte naują paskyrą, įveskite saovo el. pašto adresą ir mes atsiųsime jums instrukcijas.",
  signupButton: "Sukurkite naują paskyrą",
  signupTokenSent: "Mes išsiuntėme jums elektroninį laišką su instrukcijomis kaip susikurti naują paskyrą.",
  invalidSignupToken: "Prisijungimo nuoroda yra klaidinga. Ji negalioja arba buvo panaudota anksčiau.",
  setPwdMsg: "Dabar nustatykite savo slaptažodį.",
  accountCreated: "Mes sukurėme Jūsų paskyrą. Dabar Jūs galite prisijungti su savo el. pašto adresu ir slaptažodžiu.",
  autosave: "Automatinis saugojimas",
  flagging: "Vyksta žymėjimas...",
  flaggingFailed: "Nepavyko pažymėti įrašo.",
  exactMatches: "Tikslūs sutapimai",
  partialMatches: "Daliniai sutapimai",
  comments: "Komentarai",
  newComment: "naujas komentaras",
  revive: "Atgaivinkite",
  addToWorklist: "Pridėkite prie darbinio sąrašo",
  worklist: "DARBINIS SĄRAŠAS",
  action: "Veiksmas",
  purgeWorklist: "Viską pašalinkite iš darbinio sąrašo",
  extranet: "EKSTRANETAS",
  doingBatch: "Vyksta paketinis redagavimas...",
  batchFailed: "Nepavyko atlikti paketinio redagavimo.",
  printable: "Spausdintuvo versija",
  printableOff: "Atgal",
  batchConfirm: "Dabar atsargiai! Šis pakeitimas bus padarytas visiems čia išvardintiems įrašams (iš viso - $X). Ar tikrai to norite?",
  narrow: "Siauras ekranas",
  narrowList: "SĄRAŠAS",
  narrowEditor: "ŽIŪRYKLĖ/REDAKTORIUS",
  emailInUseError: "Šis el. adresas jau yra naudojamas.",
  perPage: "įrašai puslapyje",
};
