Screenful.Loc={
  ready: "Valmis.",
  find: "Etsi",
  reload: "Lataa uudelleen",
  cancel: "Peruuta",
  more: "Lisää",
  new: "Uusi",
  edit: "Muokkaa",
  save: "Tallenna",
  delete: "Poista",
  listing: "Haetaan listaa...",
  listingFailed: "Listan haku epäonnistui.",
  reading: "Haetaan termiä...",
  readingFailed: "Termiä ei löytynyt.",
  saving: "Tallennetaan...",
  savingFailed: "Tallennus epäonnistui.",
  deleting: "Poistetaan...",
  deletingFailed: "Poisto epäonnistui.",
  deleteConfirm: "Huomio! Oletko varma?",
  username: "Sähköpostiosoite",
  password: "Salasana",
  login: "Kirjaudu sisään",
  loginError: "Väärä sähköpostiosoite tai salasana.",
  logout: "Kirjaudu ulos",
  anonymous: "anonyymi käyttäjä",
  home: "Etusivu",
  title: "Otsikko",
  titleEmpty: "Otsikko vaaditaan.",
  url: "URL",
  urlEmpty: "URL vaaditaan.",
  urlShort: "URL:ssa täytyy olla vähintään kolme merkkiä .",
  urlInvalid: "URL ei voi sisältää muita merkkejä kuin a-z, A-Z, 0-9 ja tavuviivoja.",
  urlTaken: "Tämä URL on jo käytössä.",
  template: "Malli",
  create: "Luo",
  finished: "Valmis",
  changePwd: "Vaihda salasana",
  signup: "Luo käyttäjätili",
  forgotPwd: "Unohditko salasanasi?",
  signupEmail: "Käyttäjätilin luomista varten, lähetä sähköpostia osoitteeseen:",
  newPassword: "Uusi salasana",
  change: "Vaihda",
  passwordChanged: "Salasanasi on vaihdettu.",
  passwordEmpty: "Salasana vaaditaan.",
  passwordShort: "Salasanassa tulee olla vähintään kuusi merkkiä.",
  passwordWhitespace: "Salasana ei voi alkaa tai loppua välilyönnillä.",
  ok: "OK",
  currentUrl: "Nykyinen URL",
  newUrl: "Uusi URL",
  upload: "Lisää",
  uploadPurge: "Tyhjennä ennen lisäämistä",
  uploadFail: "Lisäys epäonnistui.",
  uploadSuccess: "Lisäys onnistui.",
  history: "Historia",
  version: "Versio",
  clone: "Kloonaa",
  sourceCode: "Lähdekoodi",
  invalidSourceCode: "Virheellinen lähdekoodi",
  unsavedConfirm: "Et ole tallentanut muutoksia. Haluatko menettää muutokset?",
  doItLater: "Tee myöhemmin",
  badEmailError: "Väärä sähköpostiosoite",
  forgotPwdEmail: "Jos olet unohtanut salasanasi, kirjoita sähköpostiosoitteesi, niin voimme lähettää sinulle ohjeet uuden salasanan luomiseen.",
  recoverPwd: "Hanki uusi salasana",
  tokenSent: "Olemme lähettäneet sinulle sähköpostilla ohjeet salasanan nollaamiseen.",
  recoverPwdMsg: "Nyt voit vaihtaa salasanasi.",
  changePwdMsg: "Voit vaihtaa salasanasi tässä.",
  invalidToken: "Virheellinen salasanan nollauslinkki. Se on saattanut vanhentua tai sitä on jo käytetty.",
  signupInfoEmail: "Luodaksesi uuden käyttäjätilin, kirjoita sähköpostiosoitteesi, niin lähetämme sinulle ohjeet.",
  signupButton: "Luo uusi käyttäjätili.",
  signupTokenSent: "Olemme lähettäneet sinulle ohjeet, kuinka luoda uusi käyttäjätili.",
  invalidSignupToken: "Virheellinen kirjautumislinkki. Se on saattanut vanhentua tai sitä on jo käytetty.",
  setPwdMsg: "Valitse salasana.",
  accountCreated: "Olemme luoneet käyttäjätilisi. Nyt voit kirjautua sisään sähköpostiosoitteellasi ja salasanallasi.",
  autosave: "Automaattinen tallennus",
  flagging: "Merkitään...",
  flaggingFailed: "Tietueen merkitseminen epäonnistui.",
  exactMatches: "Täysi vastaavuus",
  partialMatches: "Osittainen vastaavuus",
  comments: "Kommentit",
  newComment: "Uusi kommentti",
  revive: "Elvytä",
  addToWorklist: "Lisää tehtävälistaan",
  worklist: "TEHTÄVÄLISTA",
  action: "Toiminto",
  purgeWorklist: "Tyhjennä tehtävälista",
  extranet: "EKSTRANETTI",
  doingBatch: "Suoritetaan joukkomuokkausta...",
  batchFailed: "Joukkomuokkaus epäonnistui.",
  printable: "Tulostettava versio",
  printableOff: "Takaisin",
  batchConfirm: "Huomio! Tämä muutos tehdään jokaiseen tässä listattuun termitietueeseen ($X yhteensä). Oletko varma?",
  narrow: "Kapea näyttö",
  narrowList: "LISTA",
  narrowEditor: "KATSELU/MUOKKAUS",
  emailInUseError: "Tämä sähköpostiosoite on jo käytössä.",
  perPage: "translation required",
};
