Screenful.Loc={
  ready: "Llest.",
  find: "Encontrar",
  reload: "Recarregar",
  cancel: "Cancelar",
  more: "Més",
  new: "Nou",
  edit: "Editar",
  save: "Guardar",
  delete: "Esborrar",
  listing: "Obtenint la llista...",
  listingFailed: "No s'ha pogut obtenir la llista.",
  reading: "Obtenint l'element...",
  readingFailed: "No s'ha trobat l'element.",
  saving: "Guardant...",
  savingFailed: "No s'ha pogut desar.",
  deleting: "Esborrant...",
  deletingFailed: "No s'ha pogut esborrar.",
  deleteConfirm: "Atenció! Segur que vols continuar?",
  username: "Adreça de correu electrònic",
  password: "Contrasenya",
  login: "Iniciar sessió",
  loginError: "Adreça de correu electrònic o contrasenya incorrectes.",
  logout: "Finalitzar sessió",
  anonymous: "Usuari/a anònim/a",
  home: "Inici",
  title: "Títol",
  titleEmpty: "El títol no pot estar buit.",
  url: "URL",
  urlEmpty: "La URL no pot estar buida.",
  urlShort: "La URL ha de tenir com a mínim tres caràcters.",
  urlInvalid: "La URL no pot contenir altres caràcters que no siguin a-z, A-Z, 0-9 i guions.",
  urlTaken: "Aquesta URL ja està en ús.",
  template: "Plantilla",
  create: "Crear",
  finished: "Finalitzat",
  changePwd: "Canviar la contrasenya",
  signup: "Obtenir un compte",
  forgotPwd: "Has oblidat la teva contrasenya?",
  signupEmail: "Per obtenir un compte envia un correu electrònic a",
  newPassword: "Nova contrasenya",
  change: "Canviar",
  passwordChanged: "S'ha modificat la teva contrasenya.",
  passwordEmpty: "La contrasenya no pot estar buida.",
  passwordShort: "La contrasenya ha de tenir com a mínim sis caràcters.",
  passwordWhitespace: "La contrasenya no pot començar ni acabar amb un espai.",
  ok: "D'acord",
  currentUrl: "URL actual",
  newUrl: "Nova URL",
  upload: "Penjar",
  uploadPurge: "Netejar abans de penjar",
  uploadFail: "La càrrega ha fallat.",
  uploadSuccess: "La càrrega ha sigut exitosa.",
  history: "Història",
  version: "Versió",
  clone: "Clonar",
  sourceCode: "Codi font",
  invalidSourceCode: "Codi font no vàlid",
  unsavedConfirm: "Tens canvis sense desar. Segur que els vols perdre?",
  doItLater: "Fer-ho més tard",
  badEmailError: "Adreça de correu electrònic incorrecta.",
  forgotPwdEmail: "Si has oblidat la teva contrasenya, introdueix la teva adreça de correu electrònic i t'enviarem instruccions sobre com crear-ne una de nova.",
  recoverPwd: "Obtenir una nova contrasenya",
  tokenSent: "T'hem enviat un correu electrònic amb instruccions sobre com restablir la teva contrasenya.",
  recoverPwdMsg: "Ara pots canviar la teva contrasenya.",
  changePwdMsg: "Pots canviar la teva contrasenya aquí.",
  invalidToken: "Aquest enllaç de restabliment de contrasenya no és vàlid. Pot ser que hagi caducat o que ja s'hagi utilitzat abans.",
  signupInfoEmail: "Per obtenir un compte nou, introdueix la teva adreça de correu electrònic i t'enviarem instruccions.",
  signupButton: "Crear un compte nou",
  signupTokenSent: "T'hem enviat un correu electrònic amb instruccions sobre com crear un compte nou.",
  invalidSignupToken: "Aquest enllaç de registre no és vàlid. Pot ser que hagi caducat o que ja s'hagi utilitzat abans.",
  setPwdMsg: "Estableix ara la teva contrasenya.",
  accountCreated: "Hem creat el teu compte. Ara pots iniciar sessió amb la teva adreça de correu electrònic i la teva contrasenya.",
  autosave: "Desat automàtic",
  flagging: "Marcant...",
  flaggingFailed: "No s'ha pogut marcar l'entrada.",
  exactMatches: "Coincidències exactes",
  partialMatches: "Coincidències parcials",
  comments: "Comentaris",
  newComment: "nou comentari",
  revive: "Recuperar",
  addToWorklist: "Afegir a la llista de tasques",
  worklist: "LLISTA DE TASQUES",
  action: "Acció",
  purgeWorklist: "Eliminar tot de la llista de tasques",
  extranet: "EXTRANET",
  doingBatch: "Realitzant l'edició per lots...",
  batchFailed: "No s'ha pogut realitzar l'edició per lots.",
  printable: "Versió apta per imprimir",
  printableOff: "Enrere",
  batchConfirm: "Atenció! Aquest canvi es fará a totes les entrades que es mostren aquí ($X en total). Segur que vols continuar?",
  narrow: "Reduir pantalla",
  narrowList: "LLISTA",
  narrowEditor: "VISUALITZADOR/EDITOR",
  emailInUseError: "Aquesta adreça de correu electrònic ja està en ús.",
  perPage: "entrades per pàgina",
};
