Screenful.Loc={
  ready: "Réidh.",
  find: "Aimsigh",
  reload: "Athlódáil",
  cancel: "Cealaigh",
  more: "Tuilleadh",
  new: "Nua",
  edit: "Athraigh",
  save: "Sábháil",
  delete: "Scrios",
  listing: "Liosta á fháil...",
  listingFailed: "Níor éirigh liom liosta a fháil.",
  reading: "Sonraí á bhfáil...",
  readingFailed: "Ní ann don iontráil.",
  saving: "Á shábháil...",
  savingFailed: "Níor éirigh liom na sonraí a shábháil.",
  deleting: "Á scrios...",
  deletingFailed: "Níor éirigh liom na sonraí a scrios.",
  deleteConfirm: "Cúramach anois! An bhfuil tú cinnte?",
  username: "Seoladh ríomhphoist",
  password: "Pasfhocal",
  login: "Logáil isteach",
  loginError: "Seoladh ríomhphoist mícheart nó pasfhocal mícheart.",
  logout: "Logáil amach",
  anonymous: "úsáideoir anaithnid",
  home: "Baile",
  title: "Teideal",
  titleEmpty: "Ní cheadaítear an teideal a bheith folamh.",
  url: "URL",
  urlEmpty: "Ní cheadaítear an URL a bheith folamh.",
  urlShort: "Ba cheart trí charachtar, ar a laghad, a bheith sa URL.",
  urlInvalid: "Ní cheadaítear sa URL ach na carachtair a-z, A-Z, 0-9 agus fleiscín.",
  urlTaken: "Tá an URL seo in úsáid cheana.",
  template: "Teimpléad",
  create: "Cruthaigh",
  finished: "Críochnaithe",
  changePwd: "Athraigh do phasfhocal",
  signup: "Faigh cuntas duit féin",
  forgotPwd: "Pasfhocal dearmadta",
  signupEmail: "Chun cuntas a iarraidh, cuir ríomhphost chuig",
  newPassword: "Pasfhocal nua",
  change: "Athraigh",
  passwordChanged: "Tá do phasfhocal athraithe.",
  passwordEmpty: "Ní cheadaítear an pasfhocal a bheith folamh.",
  passwordShort: "Ba cheart sé charachtar, ar a laghad, a bheith sa phasfhocal.",
  passwordWhitespace: "Ní cheart spás a bheith ag tús ná ag deireadh an phasfhocail.",
  ok: "OK",
  currentUrl: "URL reatha",
  newUrl: "URL nua",
  upload: "Uaslódáil",
  uploadPurge: "Folmhaigh roimh an uaslódáil",
  uploadFail: "Theip ar an uaslódáil.",
  uploadSuccess: "D'éirigh leis an uaslódáil.",
  history: "Stair",
  version: "Leagan",
  clone: "Clónáil",
  sourceCode: "Cód foinseach",
  invalidSourceCode: "Cód foinseach neamhbhailí",
  unsavedConfirm: "Tá athruithe déanta agat nach bhfuil sábháilte go fóill. An cuma leat go gcaillfear iad?",
  doItLater: "Déan níos déanaí é",
  badEmailError: "Seoladh ríomhphoist mícheart.",
  forgotPwdEmail: "Má tá do phasfhocal dearmadta agat, cuir do sheoladh ríomhphoist isteach anseo. Cuirfidh muidne treoracha chugat maidir leis an dóigh chun do phasfhocal a athrú.",
  recoverPwd: "Faigh pasfhocal nua",
  tokenSent: "Tá treoracha seolta againn chugat maidir leis an dóigh chun do phasfhocal a athrú.",
  recoverPwdMsg: "Is féidir leat do phasfhocal a athrú anois.",
  changePwdMsg: "Is féidir leat do phasfhocal a athrú anseo.",
  invalidToken: "Níl an nasc seo bailí. Seans go bhfuil sé imithe in éag, nó b'fhéidir gur baineadh úsáid as cheana.",
  signupInfoEmail: "Chun cuntas nua a fháil, cuir do sheoladh ríomhphoist isteach anseo. Cuirfidh muidne treoracha chugat maidir leis an dóigh chun do chuntas a chruthú.",
  signupButton: "Cruthaigh cuntas",
  signupTokenSent: "Tá treoracha seolta againn chugat maidir leis an dóigh chun do chuntas a chruthú.",
  invalidSignupToken: "Níl an nasc seo bailí. Seans go bhfuil sé imithe in éag, nó b'fhéidir gur baineadh úsáid as cheana.",
  setPwdMsg: "Cruthaigh pasfhocal duit féin anois, le do thoil.",
  accountCreated: "Tá do chuntas cruthaithe. Is féidir leat logáil isteach anois.",
  autosave: "Sábháil uathoibríoch",
  flagging: "Flagging...",
  flaggingFailed: "Failed to flag the entry.",
  exactMatches: "Torthaí beachta",
  partialMatches: "Torthaí gaolmhara",
  comments: "Nótaí tráchta",
  newComment: "nóta tráchta nua",
  revive: "Tabhair ar ais",
  addToWorklist: "Cuir ar liosta oibre",
  worklist: "LIOSTA OIBRE",
  action: "Gníomh",
  purgeWorklist: "Folmhaigh an liosta oibre",
  extranet: "EISLÍON",
  doingBatch: "Iontrálacha á n-athrú...",
  batchFailed: "Níor éirigh liom na hiontrálacha a athrú.",
  printable: "Leagan oiriúnach le priontáil",
  printableOff: "Ar ais",
  batchConfirm: "Cúramach! Déanfar an t-athrú seo ar gach iontráil atá liostaithe anseo ($X san iomlán). An bhfuil tú cinnte?",
  narrow: "Scáileán cúng",
  narrowList: "LIOSTA",
  narrowEditor: "AMHARC/EAGAR",
};
