function L(s, gloss){
  if(s=="only") return function(s){
    return "solo "+s;
  };
  if(s=="READ-ONLY") return "للقراءة-فقط";
  if(s=="Editing") return "التحرير";
  if(s=="Dublin City University") return "جامعة مدينة دبلن";
  if(s=="Log out") return "تسجيل الخروج";
  if(s=="Change your password") return "غير كلمة المرور الخاصة بك";
  if(s=="Registered user login") return "تسجيل دخول المستخدم المسجل";
  if(s=="Get an account") return "أحصل علي حساب";
  if(s=="Forgot your password?") return "هل نسيت كلمة المرور الخاصة بك؟";
  if(s=="E-mail address") return "عنوان البريد الإلكتروني";
  if(s=="Password") return "كلمة المرور";
  if(s=="Log in") return "تسجيل الدخول";
  if(s=="Your termbases") return "قواعد المصطلحات الخاصة بك";
  if(s=="You have no termbases yet.") return "ليس لديك قواعد مصطلحات لحد الآن.";
  if(s=="Create a termbase") return "إنشاء قاعدة مصطلحات";
  if(s=="Administration") return "الإدارة";
  if(s=="Users") return "المستخدمون";
  if(s=="Termbases") return "قواعد المصطلحات";
  if(s=="smart search") return "البحث الذكي";
  if(s=="complete term") return "المصطلح الكامل";
  if(s=="start of term") return "بداية المصطلح";
  if(s=="end of term") return "نهاية المصطلح";
  if(s=="any part of term") return "جزء ما من المصطلح";
  if(s=="any part except start or end") return "أي جزء ما عدا البداية أو النهاية";
  if(s=="search in all languages") return "البحث في جميع اللغات";
  if(s=="Configuration") return "التهيئة";
  if(s=="ADMIN") return "المدير";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "DEF";
  if(s=="XMPL") return "XMPL";
  if(s=="CHECKING STATUS") return "حالة التحقق ";
  if(s=="PUBLISHING STATUS") return "حالة النشر";
  if(s=="TERMS") return "المصطلحات";
  if(s=="DOMAINS") return "المجالات";
  if(s=="term") return "المصطلح";
  if(s=="clarification") return "توضيح";
  if(s=="acceptability") return "مقبولية";
  if(s=="source") return "المصدر";
  if(s=="inflected form") return "صيغة متصرفة";
  if(s=="annotation") return "تعليق توضيحي";
  if(s=="domain") return "مجال";
  if(s=="part of speech") return "قسم من أقسام الكلام";
  if(s=="inflection") return "تصريف";
  if(s=="language of origin") return "لغة المصدر";
  if(s=="symbol") return "رَمْز";
  if(s=="trademark") return "علامة تجارية";
  if(s=="registered trademark") return "علامة تجارية مُسَجّلَة";
  if(s=="proper noun") return "إسْمُ عَلَم";
  if(s=="formatting") return "صياغة";
  if(s=="italic") return "حَرْفٌ مائِل";
  if(s=="Created") return "تم الإنشاء";
  if(s=="Changed") return "تم التغيير";
  if(s=="Deleted") return "تم الحذف";
  if(s=="Bulk-deleted") return "حذف اجمالي";
  if(s=="while uploading") return "أثناء التحميل";
  if(s=="By") return "بواسطة";
  if(s=="When") return "متى";
  if(s=="any checking status") return "جميع حالات التحقق";
  if(s=="any publishing status") return "جميع حالات النشر";
  if(s=="any language") return "أية لغة";
  if(s=="any acceptability or no acceptability") return "أية مقبولية أو لا مقبولية";
  if(s=="any acceptability") return "أية مقبولية";
  if(s=="no acceptability") return "لا مقبولية";
  if(s=="any domain or no domain") return "أي مجال أو لا مجال";
  if(s=="any domain") return "أي مجال";
  if(s=="no domain") return "لا مجال";
  if(s=="LAST MAJOR UPDATE") return "آخر تحديث رئيسي";
  if(s=="set to today") return "تعيين إلى اليوم";
  if(s=="Invalid e-mail address or password.") return "عنوان بريد إلكتروني أو كلمة مرور غير صحيحة.";
  if(s=="INTR") return "INTR";
  if(s=="COLL") return "COLL";
  if(s=="INTROS") return "INTROS";
  if(s=="DEFINITIONS") return "التعاريف";
  if(s=="EXAMPLES") return "الأمثلة";
  if(s=="COLLECTIONS") return "المجموعات";
  if(s=="definition") return "التعريف";
  if(s=="example") return "المثال";
  if(s=="sentence") return "الجملة";
  if(s=="collection") return "المجموعة";
  if(s=="any collection or no collection") return "أي مجموعة أو لا مجموعة";
  if(s=="any collection") return "أي مجموعة";
  if(s=="no collection") return "لا مجموعة";
  if(s=="comments") return "تعليقات";
  if(s=="with or without comments") return "مع تعليقات أو بدونها";
  if(s=="with comments") return "مع تعليقات";
  if(s=="without comments") return "بدون تعليقات";
  if(s=="my comments") return "تعليقاتي";
  if(s=="with or without my comments") return "مع تعليقاتي أو بدونها";
  if(s=="with my comments") return "مع تعليقاتي";
  if(s=="without my comments") return "بدون تعليقاتي";
  if(s=="other people's comments") return "تعليقات الآخرين";
  if(s=="with or without other people's comments") return "مع تعليقات الآخرين أو بدونها";
  if(s=="with other people's comments") return "مع تعليقات الآخرين";
  if(s=="without other people's comments") return "دون تعليقات الآخرين";
  if(s=="EXTRANET") return "الشبكة الخارجية";
  if(s=="EXT") return "EXT";
  if(s=="EXTRANETS") return "الشبكات الخارجية";
  if(s=="extranet") return "الشبكة الخارجية";
  if(s=="any extranet or no extranet") return "أي شبكة خارجية أو لا شبكة خارجية";
  if(s=="any extranet") return "أي شبكة خارجية";
  if(s=="no extranet") return "لا شبكة خارجية";
  if(s=="sorting language") return "فرز اللغة";
  if(s=="Create mutual cross-references") return "إنشاء مراجع تبادلية";
  if(s=="Remove mutual cross-references") return "إزالة المراجع التبادلية";
  if(s=="Merge into a single entry") return "دمج في مدخل واحد";
  if(s=="SEE ALSO") return "انظر أيضًا";
  if(s=="add to worklist") return "إضافة إلى قائمة العمل";
  if(s=="Domains") return "المجالات";
  if(s=="Part-of-speech labels") return "تسميات أقسام الكلام";
  if(s=="Inflection labels") return "تسميات التصريفات";
  if(s=="Acceptability labels") return "تسميات المقبولية";
  if(s=="Sources") return "المصادر";
  if(s=="Collections") return "المجموعات";
  if(s=="Tags") return "العلامات";
  if(s=="Extranets") return "الشبكات الخارجية";
  if(s=="Name and blurb") return "الاسم والدعاية";
  if(s=="Features") return "الميزات";
  if(s=="Languages") return "اللغات";
  if(s=="Publishing") return "النشر";
  if(s=="Change the termbase's URL") return "تغيير عنوان URL قاعدة المصطلحات";
  if(s=="Delete the termbase") return "حذف قاعدة المصطلحات";
  if(s=="TITLE") return "العنوان";
  if(s=="abbreviation") return "الإختصار";
  if(s=="LANGUAGES") return "اللغات";
  if(s=="select all") return "حدد الكل";
  if(s=="unselect all") return "الغاء أمر تحديد الكل";
  if(s=="PRIORITY") return "الأولوية";
  if(s=="high") return "عال";
  if(s=="medium") return "متوسط";
  if(s=="low") return "منخفض";
  if(s=="USERS") return "المستخدمون";
  if(s=="e-mail address") return "عنوان البريد الإلكتروني";
  if(s=="user") return "المستخدم";
  if(s=="Alphabetical order") return "ترتيب أبجدي";
  if(s=="Similar terms (click to insert)") return "مصطلحات مشابهة (انقر للإدراج)";
  if(s=="Other entries that share this term") return "مداخل أخرى تشترك في هذا المصطلح";
  if(s=="stop sharing") return "إيقاف المشاركة";
  if(s=="Change checking status to") return "تغيير حالة التحقق إلى";
  if(s=="Change publishing status to") return "تغيير حالة النشر إلى";
  if(s=="Add to extranet") return "إضافة إلى الشبكة الخارجية";
  if(s=="Remove from extranet") return "إزالة من الشبكة الخارجية";
  if(s=="checked") return "تم التحقق منه";
  if(s=="not checked") return "غير محقق";
  if(s=="publishable") return "قابل للنشر";
  if(s=="hidden") return "خفيّ";
  if(s=="CHECKED") return "تم التحقق منه";
  if(s=="NOT CHECKED") return "غير مُحقَّق";
  if(s=="PUBLISHABLE") return "قابل للنشر";
  if(s=="HIDDEN") return "خفيّ";
  if(s=="non-essential") return "غير-أساسيّ";
  if(s=="STATUS") return "الحالة";
  if(s=="live") return "مباشر";
  if(s=="not live") return "غير مباشر";
  if(s=="any clarification or no clarification") return "أي توضيح أو لا توضيح";
  if(s=="any clarification") return "أي توضيح";
  if(s=="no clarification") return "لا توضيح";
  if(s=="clarification containing...") return "توضيح يحتوي على...";
  if(s=="any intro or no intro") return "أية مقدمة أو لا مقدمة";
  if(s=="any intro") return "أية مقدمة";
  if(s=="no intro") return "لا مقدمة";
  if(s=="intro containing...") return "مقدمة تحتوي على...";
  if(s=="any definition or no definition") return "أي تعريف أو لا تعريف";
  if(s=="any definition") return "أي تعريف";
  if(s=="no definition") return "ليس هناك تعريف";
  if(s=="definition containing...") return "تعريف يحتوي على...";
  if(s=="any example or no example") return "أي مثال أو لا مثال";
  if(s=="any example") return "أي مثال";
  if(s=="no example") return "ليس هناك مثال";
  if(s=="example containing...") return "مثال يحتوي على...";
  if(s=="Automatic changes") return "التغييرات التلقائية";
  if(s=="NAME") return "الاسم";
  if(s=="BLURB") return "الدعاية";
  if(s=="level") return "المستوى";
  if(s=="reader") return "القارئ";
  if(s=="editor") return "المحرِّر";
  if(s=="creator") return "المُنشئ";
  if(s=="administrator") return "المُدِير";
  if(s=="configurator") return "المُهيئ";
  if(s=="no change") return "لا تغيير";
  if(s=="change to 'not checked'") return "تغيير  إلى \"غير مُحقَّق\""; //check
  if(s=="change to 'hidden'") return "تغيير  إلى \"مخفيّ\""; //check
  if(s=="change to 'not checked' and 'hidden'") return "تغيير  إلى \"غير  مُحقَّق\" و \"مخفي\""; //check
  if(s=="LAST SEEN") return "آخر ظهور";
  if(s=="NEVER") return "أبدًا";
  if(s=="No termbases") return "لا توجد قواعد مصطلحات";
  if(s=="language") return "اللغة";
  if(s=="major") return "رئيسيّ";
  if(s=="minor") return "ثانويّ";
  if(s=="role") return "دَوْر";
  if(s=="title") return "عنوان";
  if(s=="ACCESS LEVEL") return "مستوى الولوج";
  if(s=="LICENCE") return "رخصة الإستخدام";
  if(s=="private") return "خاصّ";
  if(s=="public") return "عام";
  if(s=="trigger_dateStampChange") return "تم تغيير طابع التواريخ";
  if(s=="trigger_domainAdd") return "تمت إضافة المجال";
  if(s=="trigger_domainRemove") return "تمت إزالة المجال";
  if(s=="trigger_domainReorder") return "تمت إعادة ترتيب المجالات";
  if(s=="trigger_domainChange") return "تم تغيير المجال";
  if(s=="trigger_desigAdd") return "تمت إضافة المصطلح";
  if(s=="trigger_desigRemove") return "تمت إزالة المصطلح";
  if(s=="trigger_desigReorder") return "تمت إعادة ترتيب المصطلحات";
  if(s=="trigger_desigClarifChange") return "تم تغيير التوضيح";
  if(s=="trigger_desigAcceptChange") return "تم تغيير المقبولية";
  if(s=="trigger_termLangChange") return "تم تغيير اللغة";
  if(s=="trigger_termWordingChange") return "تغيرت صياغة المصطلح";
  if(s=="trigger_termInflectAdd") return "تمت إضافة الصيغة المتصرفة";
  if(s=="trigger_termInflectRemove") return "تمت إزالة الصيغة المتصرفة";
  if(s=="trigger_termInflectReorder") return "تمت إعادة ترتيب الصيغ المتصرفة";
  if(s=="trigger_termInflectLabelChange") return "تم تغيير تسمية الصيغة المتصرفة";
  if(s=="trigger_termInflectTextChange") return "تم تغيير صياغة الصيغة المتصرفة";
  if(s=="trigger_termAnnotAdd") return "تمت إضافة تعليق توضيحي للمصطلح";
  if(s=="trigger_termAnnotRemove") return "تمت إزالة التعليق التوضيحي للمصطلح";
  if(s=="trigger_termAnnotReorder") return "تمت إعادة ترتيب التعليقات التوضيحية للمصطلحات";
  if(s=="trigger_termAnnotPositionChange") return "تم تغيير موضع التعليق التوضيحي للمصطلح";
  if(s=="trigger_termAnnotLabelChange") return "تم تغيير تسمية التعليق التوضيحي للمصطلح";
  if(s=="trigger_introChange") return "تغيرت المقدمة";
  if(s=="trigger_definitionAdd") return "تمت إضافة التعريف";
  if(s=="trigger_definitionRemove") return "تمت إزالة التعريف";
  if(s=="trigger_definitionReorder") return "تمت إعادة ترتيب التعاريف";
  if(s=="trigger_definitionTextChange") return "تم تغيير نص التعريف";
  if(s=="trigger_exampleAdd") return "تمت إضافة المثال";
  if(s=="trigger_exampleRemove") return "تمت إزالة المثال";
  if(s=="trigger_exampleReorder") return "تمت إعادة ترتيب الأمثلة";
  if(s=="trigger_exampleTextAdd") return "تمت إضافة الجملة النموذجية";
  if(s=="trigger_exampleTextRemove") return "تمت إزالة الجملة النموذجية";
  if(s=="trigger_exampleTextReorder") return "تمت إعادة ترتيب الجمل النموذجية";
  if(s=="trigger_exampleTextChange") return "تم تغيير صيغة الجملة النموذجية";
  if(s=="trigger_collectionAdd") return "تمت إضافة المجموعة";
  if(s=="trigger_collectionRemove") return "تمت إزالة المجموعة";
  if(s=="trigger_collectionReorder") return "تمت إعادة ترتيب المجموعات";
  if(s=="trigger_collectionChange") return "تم تغيير المجموعة";
  if(s=="trigger_extranetAdd") return "تمت إضافة الشبكة الخارجية";
  if(s=="trigger_extranetRemove") return "تمت إزالة الشبكة الخارجية";
  if(s=="trigger_extranetReorder") return "تمت إعادة ترتيب الشبكات الخارجية";
  if(s=="trigger_extranetChange") return "تم تغيير الشبكة الخارجية";
  if(s=="trigger_sourceAdd") return "تمت إضافة المصدر";
  if(s=="trigger_sourceRemove") return "تمت إزالة المصدر";
  if(s=="trigger_sourceReorder") return "تمت إعادة ترتيب المصدر";
  if(s=="trigger_sourceChange") return "تم تغيير المصدر";
  if(s=="trigger_nonessentialChange") return "تم تغيير صفة اللاأساسية";
  if(s=="(blank)") return "(فارغ)";
  if(s=="Simple Multilingual Termbase") return "قاعدة مصطلحات بسيطة متعددة اللغات";
  if(s=="Simple Bilingual Termbase") return "قاعدة مصطلحات بسيطة ثنائية اللغة";
  if(s=="Simple Monolingual Termbase") return "قاعدة مصطلحات بسيطة أحادية اللغة";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "أدخل عنوانًا يمكن قراءته بشريًا مثل \"قاموسي الخاص بالمصطلحات الرياضية\". سوف تكون قادرا على تغيير هذا في وقت لاحق."; //check
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "سيكون هذا عنوان قاعدة المصطلحات الخاصة بك على الويب. سوف تكون قادرا على تغيير هذا في وقت لاحق.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "يمكنك اختيار قالب هنا لتبدأ. كل قالب يأتي مع بعض المداخل النموذجية. سوف تكون قادرا على تغييرها أو حذفها وتخصيص القالب.";
  if(s=="Your termbase is ready.") return "أصبحت قاعدة المصطلحات الخاصة بك جاهزة.";
  if(s=="TERM OF THE DAY") return "مصطلح اليوم";
  if(s=="set to next available date") return "تعيين إلى التاريخ التالي المتاح";
  if(s=="Display from") return "العرض من";
  if(s=="Display until") return "العرض حتى";
  if(s=="News and announcements") return "﻿﻿الأخبار و الإعلانات";
  if(s=="Create your account") return "أنشئ حسابك الخاص";
  if(s=="Reset your password") return "أعد ضبط كلمة المرور الخاصة بك";
  if(s=="Terminologue signup") return "تسجيل الدخول في Terminologue";
  if(s=="Please follow the link below to create your Terminologue account:") return "يرجى اتباع الرابط أدناه لإنشاء حسابك الخاص في Terminologue:";
  if(s=="Terminologue password reset") return "إعادة تعيين كلمة المرور الخاصة ب Terminologue";
  if(s=="Please follow the link below to reset your Terminologue password:") return "يرجى اتباع الرابط أدناه لإعادة تعيين كلمة مرورك الخاصة ب Terminologue:";
  if(s=="This page is only available in English.") return "هذه الصفحة متوفرة باللغة الإنجليزية فقط.";
  if(s=="DRAFTING STATUS") return "حالة الصياغة";
  if(s=="draft entry") return "مُسودَّة مدخل";
  if(s=="finished entry") return "مدخل مكتمل";
  if(s=="DRAFT") return "مُسودَّة";
  if(s=="FINISHED") return "منتهِ";
  if(s=="any drafting status") return "جميع حالات الصياغة";
  if(s=="Prefabricated comments") return "تعليقات جاهزة";
  if(s=="NOTES") return "ملاحظات";
  if(s=="note") return "ملاحظة";
  if(s=="NOT") return "NOT";
  if(s=="with or without notes") return "مع أو بدون ملاحظات";
  if(s=="with a note") return "مع ملاحظة";
  if(s=="with a note containing...") return "مع ملاحظة تحتوي على...";
  if(s=="without notes") return "بدون ملاحظات";
  if(s=="any type") return "أي نوع";
  if(s=="private note, not shown on extranets") return "ملاحظة خاصة، لا تظهر على الشبكات الخارجية";
  if(s=="private note, shown on extranets") return "ملاحظة خاصة، تظهر على الشبكات الخارجية";
  if(s=="public note") return "ملاحظة عامة";
  if(s=="Note types") return "أنواع الملاحظة";
  if(s=="LEVEL") return "المستوى";
  if(s=="with a comment") return "مع تعليق";
  if(s=="with a comment containing...") return "مع تعليق يتضمن...";
  if(s=="TBX export") return "تصدير TBX";
  if(s=="TBX import") return "استيراد TBX";
  if(s=="Empty the termbase") return "إفراغ قاعدة المصطلحات";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "احترس الآن! أنت على وشك حذف قاعدة المصطلحات هذه. لن تتمكن من التراجع عن هذا.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "احترس الآن! أنت على وشك حذف كافة المداخل ومحفوظاتها. لن تتمكن من التراجع عن هذا.";
  if(s=="RELATED TERMS") return "مصطلحات ذات صلة";
  if(s=="Your termbase at a glance") return "قاعدة المصطلحات الخاصة بك في لمحة";
  if(s=="Number of entries") return "عدد المداخل";
  if(s=="Number of items in history log") return "عدد العناصر في سجل التاريخ";
  if(s=="Your termbase is stored in the file %F") return "قاعدة المصطلحات الخاصة بك مخزنة في الملف %F"; //check
  if(s=="File size") return "حجم الملف";
  if(s=="Download %F") return "تنزيل %F"; //check
  if(s=="Upload %F") return "تحميل %F"; //check
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "تأكد من أن الملف الذي تقوم بتحميله قاعدة مصطلحات صالحة. إذا قمت بتحميل شيء آخر سوف تتسبب في ضرر لا يمكن إصلاحه في قاعدة المصطلحات الخاصة بك.";
  if(s=="PARENT") return "الأصل";
  if(s=="no parent") return "بلا أصل";
  if(s=="excluding subdomains") return "باستثناء المجالات الفرعية";
  if(s=="including subdomains") return "بما في ذلك المجالات الفرعية";
  if(s=="the entry has this domain") return "للمدخل هذا المجال";
  if(s=="the entry has only this domain") return "للمدخل هذا المجال فقط";
  if(s=="the entry has not only this domain") return "ليس للمدخل هذا المجال فقط";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "احذر!  إذا قمت بإزالة نفسك من قاعدة المصطلحات هذه سوف لن تتمكن من ولوجها مجددا.";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
