function L(s, gloss){
  if(s=="only") return function(s){
    return "jen "+s;
  };
  if(s=="READ-ONLY") return "JEN KE ČTENÍ";
  if(s=="Editing") return "Editace";
  if(s=="Dublin City University") return "Dublin City University";
  if(s=="Log out") return "Odhlásit se";
  if(s=="Change your password") return "Změnit si heslo";
  if(s=="Registered user login") return "Registrovaní uživatelé";
  if(s=="Get an account") return "Zřídit si účet";
  if(s=="Forgot your password?") return "Zapomenuté heslo?";
  if(s=="E-mail address") return "E-mailová adresa";
  if(s=="Password") return "Heslo";
  if(s=="Log in") return "Přihlásit se";
  if(s=="Your termbases") return "Tvoje terminologické databáze";
  if(s=="You have no termbases yet.") return "Zatím žádnou nemáš.";
  if(s=="Create a termbase") return "Vytvořit terminologickou databázi";
  if(s=="Administration") return "Administrace";
  if(s=="Users") return "Uživateĺé";
  if(s=="Termbases") return "Terminologické databáze";
  if(s=="smart search") return "chytré hledání";
  if(s=="starts like this") return "začíná takhle";
  if(s=="contains a word that starts like this") return "obsahuje slovo, které takhle začíná";
  if(s=="contains this sequence of characters") return "obsahuje tuto posloupnost znaků";
  if(s=="search in all languages") return "hledat ve všech jazycích";
  if(s=="Configuration") return "Konfigurace";
  if(s=="ADMIN") return "ADMIN";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "DEF";
  if(s=="XMPL") return "NAPŘ"
  if(s=="CHECKING STATUS") return "STAV ZKONTROLOVANOSTI";
  if(s=="PUBLISHING STATUS") return "STAV PUBLIKOVATELNOSTI";
  if(s=="TERMS") return "TERMÍNY";
  if(s=="DOMAINS") return "DOMÉNY";
  if(s=="term") return "termín";
  if(s=="clarification") return "vysvětlivka";
  if(s=="acceptability") return "přijatelnost";
  if(s=="source") return "zdroj";
  if(s=="inflected form") return "vyskloňovaná forma";
  if(s=="annotation") return "anotace";
  if(s=="domain") return "doména";
  if(s=="subdomain") return "poddoména";
  if(s=="part of speech") return "slovní druh";
  if(s=="inflection") return "sklonění";
  if(s=="language of origin") return "jazyk původu";
  if(s=="symbol") return "symbol";
  if(s=="trademark") return "obchodní značka";
  if(s=="registered trademark") return "zapsaná obchodní značka";
  if(s=="proper noun") return "vlastní jméno";
  if(s=="formatting") return "formátování";
  if(s=="italic") return "kurzívou";
  if(s=="none" && gloss=="no subdomain") return "žádná";
  if(s=="Created") return "Vytvořeno";
  if(s=="Changed") return "Změněno";
  if(s=="Deleted") return "Smazáno";
  if(s=="Bulk-deleted") return "Hromadně smazáno";
  if(s=="while uploading") return "během nahrávání";
  if(s=="By") return "Kým";
  if(s=="When") return "Kdy";
  if(s=="any checking status") return "jakýkoliv status zkontrolovanosti";
  if(s=="any publishing status") return "jakýkoliv status publikovatelnosti";
  if(s=="any language") return "jakýkoliv jazyk";
  if(s=="any acceptabilty or no acceptability") return "jakákoliv přijatelnost nebo žádná";
  if(s=="any acceptabilty") return "jakákoliv přijatelnost";
  if(s=="no acceptability") return "žádná přijatelnost";
  if(s=="any domain or no domain") return "jakákoliv doména nebo žádná";
  if(s=="any domain") return "jakákoliv doména";
  if(s=="no domain") return "žádná doména";
  if(s=="any subdomain or no subdomain") return "jakákoliv poddoména nebo žádná";
  if(s=="any subdomain") return "jakákoliv poddoména";
  if(s=="no subdomain") return "žádná poddoména";
  if(s=="DATESTAMP") return "DATUM";
  if(s=="LAST MAJOR UPDATE") return "POSLEDNÍ PODSTATNÁ ZMÉNA";
  if(s=="set to today") return "změnit na dnešek";
  if(s=="any datestamp or no datestamp") return "jakékoliv datum nebo žádné";
  if(s=="any datestamp") return "jakékoliv datum";
  if(s=="no datestamp") return "žádné datum";
  if(s=="datestamp before...") return "datum před...";
  if(s=="datestamp on...") return "datum přesně...";
  if(s=="datestamp after...") return "datum po...";
  if(s=="Invalid e-mail address or password.") return "Neplatná e-mailová adresa nebo neplatné heslo.";
  if(s=="INTR") return "ÚVD";
  if(s=="COLL") return "SBÍR";
  if(s=="INTROS") return "ÚVODY";
  if(s=="DEFINITIONS") return "DEFINICE";
  if(s=="EXAMPLES") return "PŘÍKLADY";
  if(s=="COLLECTIONS") return "SBÍRKY";
  if(s=="definition") return "definice";
  if(s=="example") return "příklad";
  if(s=="sentence") return "věta";
  if(s=="collection") return "sbírka";
  if(s=="any collection or no collection") return "jakákoliv sbírka nebo žádná";
  if(s=="any collection") return "jakákoliv sbírka";
  if(s=="no collection") return "žádná sbírka";
  if(s=="my comments") return "komentáře ode mě";
  if(s=="with or without my comments") return "má komentář ode mě nebo nemá";
  if(s=="with my comments") return "má komentář ode mě";
  if(s=="without my comments") return "nemá komentář ode mě";
  if(s=="other people's comments") return "komentáře od ostatních";
  if(s=="with or without other people's comments") return "má komentáře od ostatních nebo nemá";
  if(s=="with other people's comments") return "má komentáře od ostatních";
  if(s=="without other people's comments") return "nemá komentáře od ostatních";
  if(s=="EXTRANET") return "EXTRANET";
  if(s=="EXT") return "EXT";
  if(s=="EXTRANETS") return "EXTRANETY";
  if(s=="extranet") return "extranet";
  if(s=="any extranet or no extranet") return "jakýkoliv extranet nebo žádný";
  if(s=="any extranet") return "jakýkoliv extranet";
  if(s=="no extranet") return "žádný extranet";
  if(s=="sorting language") return "jazyk abecedního řazení";
  if(s=="Create mutual cross-references") return "Propojit vzájemnými odkazy";
  if(s=="Remove mutual cross-references") return "Rozpojit vzájemné odkazy";
  if(s=="Merge into a single entry") return "Sloučit do jednoho hesla";
  if(s=="LAST UPDATED") return "POSLEDNÍ ZMĚNA";
  if(s=="SEE ALSO") return "VIZ TAKÉ";
  if(s=="add to worklist") return "dát na pracovní seznam";
  if(s=="Lists") return "Seznamy";
  if(s=="Domains") return "Domény";
  if(s=="Part-of-speech labels") return "Slovní druhy";
  if(s=="Inflection labels") return "Druhy skloňování";
  if(s=="Acceptability labels") return "Druhy přijatelnosti";
  if(s=="Sources") return "Zdroje";
  if(s=="Collections") return "Sbírky";
  if(s=="Teamwork") return "Týmová práce";
  if(s=="Tags") return "Značky";
  if(s=="Extranets") return "Extranety";
  if(s=="Termbase settings") return "Nastavení databáze";
  if(s=="Name and blurb") return "Jméno a úvod";
  if(s=="Features") return "Vlastnosti databáze";
  if(s=="Languages") return "Jazyky";
  if(s=="Termbase access") return "Přístup k databázi";
  if(s=="Publishing") return "Publikování";
  if(s=="Change the termbase's URL") return "Změnit URL databáze";
  if(s=="Delete the termbase") return "Smazat databázi";
  if(s=="Careful now! You will not be able to undo this.") return "Pozor! Tohle nepůjde vrátit zpátky.";
  if(s=="TITLE") return "NADPIS";
  if(s=="SUBDOMAINS") return "PODDOMÉNY";
  if(s=="abbreviation") return "zkratka";
  if(s=="LANGUAGES") return "JAZYKY";
  if(s=="select all") return "vybrat všechny";
  if(s=="unselect all") return "odvybrat všechny";
  if(s=="PRIORITY") return "PRIORITA";
  if(s=="high") return "vysoká";
  if(s=="medium") return "střední";
  if(s=="low") return "nízká";
  if(s=="USERS") return "UŹIVATElĚ";
  if(s=="e-mail address") return "e-mailová adresa";
  if(s=="user") return "uživatel";
  if(s=="Alphabetical order") return "Abecední řazení";
  if(s=="Similar terms (click to insert)") return "Podobné termíny (klinutím vložit)";
  if(s=="Other entries that share this term") return "Ostatní hesla, se kterými se termín sdílí";
  if(s=="stop sharing") return "přestat sdílet";
  if(s=="Change checking status to") return "Změnit stav zkontrolovanosti na";
  if(s=="Change publishing status to") return "Změnit stav publikovatelnosti na";
  if(s=="Add to extranet") return "Přidat na extranet";
  if(s=="Remove from extranet") return "Odebrat z extranetu";
  if(s=="checked") return "zkontrolováno";
  if(s=="not checked") return "nezkontrolováno";
  if(s=="publishable") return "publikovatelné";
  if(s=="hidden") return "skryté";
  if(s=="CHECKED") return "ZKONTROLOVÁNO";
  if(s=="NOT CHECKED") return "NEZKONTROLOVÁNO";
  if(s=="PUBLISHABLE") return "PUBLIKOVATELNÉ";
  if(s=="HIDDEN") return "SKRYTÉ";
  if(s=="non-essential") return "nedůležité";
  if(s=="STATUS") return "STATUS";
  if(s=="live") return "živý";
  if(s=="not live") return "neživý";
  if(s=="any clarification or no clarification") return "jakákoliv vysvětlivka nebo žádná";
  if(s=="any clarification") return "jakákoliv vysvětlivka";
  if(s=="no clarification") return "žádná vysvětlivka";
  if(s=="clarification containing...") return "vysvětlivka obsahující...";
  if(s=="any intro or no intro") return "jakýkoliv úvod nebo žádný";
  if(s=="any intro") return "jakýkoliv úvod";
  if(s=="no intro") return "žádný úvod";
  if(s=="intro containing...") return "úvod obsahující...";
  if(s=="any definition or no definition") return "jakákoliv definice nebo žádná";
  if(s=="any definition") return "jakákoliv definice";
  if(s=="no definition") return "žádná definice";
  if(s=="definition containing...") return "definice obsahující...";
  if(s=="any example or no example") return "jakýkoliv příklad nebo žádný";
  if(s=="any example") return "jakýkoliv příklad";
  if(s=="no example") return "žádný příklad";
  if(s=="example containing...") return "příklad obsahující...";
  if(s=="Automatic status changes") return "Automatické změny statusu";
  if(s=="NAME") return "JMÉNO";
  if(s=="BLURB") return "ÚVOD";
  if(s=="level") return "úroveň";
  if(s=="reader") return "čtenář";
  if(s=="editor") return "měnitel";
  if(s=="creator") return "tvořitel";
  if(s=="administrator") return "administrátor";
  if(s=="configurator") return "konfigurátor";
  if(s=="no change") return "bez změny";
  if(s=="change to 'not checked'") return "změnit na 'nezkontrolováno'";
  if(s=="change to 'hidden'") return "změnit na 'skryté'";
  if(s=="change to 'not checked' and 'hidden'") return "změnit na 'nezkontrolováno' a 'skryté'";
  if(s=="LAST SEEN") return "NAPOSLED VIDĚN";
  if(s=="NEVER") return "NIKDY";
  if(s=="No termbases") return "Nemá žádné terminologické databáze.";
  if(s=="language") return "jazyk";
  if(s=="major") return "hlavní jazyk";
  if(s=="minor") return "vedlejší jazyk";
  if(s=="role") return "role";
  if(s=="title") return "nadpis";
  if(s=="ACCESS LEVEL") return "ÚROVEŃ PŘÍSTUPU";
  if(s=="LICENCE") return "LICENCE";
  if(s=="private") return "soukromá";
  if(s=="public") return "veřejná";

  if(s=="trigger_dateStampChange") return "datestamp changed";
  if(s=="trigger_domainAdd") return "domain added";
  if(s=="trigger_domainRemove") return "domain removed";
  if(s=="trigger_domainReorder") return "domains reordered";
  if(s=="trigger_domainChange") return "domain changed";
  if(s=="trigger_subdomainChange") return "subdomain changed";
  if(s=="trigger_desigAdd") return "term added";
  if(s=="trigger_desigRemove") return "term removed";
  if(s=="trigger_desigReorder") return "terms reordered";
  if(s=="trigger_desigClarifChange") return "clarification changed";
  if(s=="trigger_desigAcceptChange") return "acceptability changed";
  if(s=="trigger_termLangChange") return "term language changed";
  if(s=="trigger_termWordingChange") return "term wording changed";
  if(s=="trigger_termInflectAdd") return "inlected form added";
  if(s=="trigger_termInflectRemove") return "inflected form removed";
  if(s=="trigger_termInflectReorder") return "infected forms reordered";
  if(s=="trigger_termInflectLabelChange") return "inflected form label changed";
  if(s=="trigger_termInflectTextChange") return "inflected form wording changed";
  if(s=="trigger_termAnnotAdd") return "term annotation added";
  if(s=="trigger_termAnnotRemove") return "term annotaion removed";
  if(s=="trigger_termAnnotReorder") return "term annotations reordered";
  if(s=="trigger_termAnnotPositionChange") return "term annotation position changed";
  if(s=="trigger_termAnnotLabelChange") return "term annotation label changed";
  if(s=="trigger_introChange") return "intro changed";
  if(s=="trigger_definitionAdd") return "definition added";
  if(s=="trigger_definitionRemove") return "definition removed";
  if(s=="trigger_definitionReorder") return "definitions reordered";
  if(s=="trigger_definitionTextChange") return "definition text changed";
  if(s=="trigger_exampleAdd") return "example added";
  if(s=="trigger_exampleRemove") return "example removed";
  if(s=="trigger_exampleReorder") return "examples reordered";
  if(s=="trigger_exampleTextAdd") return "example sentence added";
  if(s=="trigger_exampleTextRemove") return "example sentence removed";
  if(s=="trigger_exampleTextReorder") return "example sentences reordered";
  if(s=="trigger_exampleTextChange") return "example sentence wording changed";
  if(s=="trigger_collectionAdd") return "collection added";
  if(s=="trigger_collectionRemove") return "collecttion removed";
  if(s=="trigger_collectionReorder") return "collections reordered";
  if(s=="trigger_collectionChange") return "collection changed";
  if(s=="trigger_extranetAdd") return "extranet added";
  if(s=="trigger_extranetRemove") return "extranet removed";
  if(s=="trigger_extranetReorder") return "extranets reordered";
  if(s=="trigger_extranetChange") return "extranet changed";
  if(s=="trigger_sourceAdd") return "source added";
  if(s=="trigger_sourceRemove") return "source removed";
  if(s=="trigger_sourceReorder") return "source reordered";
  if(s=="trigger_sourceChange") return "source changed";
  if(s=="trigger_nonessentialChange") return "non-essentiality changed";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
