function L(s, gloss){
  if(s=="only") return function(s){
    return s+" yn unig";
  };
  if(s=="READ-ONLY") return "DARLLEN YN UNIG";
  if(s=="Editing") return "Golygu";
  if(s=="Dublin City University") return "Prifysgol Dinas Dulyn";
  if(s=="Log out") return "Allgofnodi";
  if(s=="Change your password") return "Newid eich cyfrinair";
  if(s=="Registered user login") return "Mewngofnodi defnyddiwr cofrestredig";
  if(s=="Get an account") return "Mynnu cyfrif";
  if(s=="Forgot your password?") return "Wedi anghofio'ch cyfrinair?";
  if(s=="E-mail address") return "Cyfeiriad e-bost";
  if(s=="Password") return "Cyfrinair";
  if(s=="Log in") return "Mewngofnodi";
  if(s=="Your termbases") return "Eich cronfeydd termau";
  if(s=="You have no termbases yet.") return "Does gennych ddim cronfeydd termau eto.";
  if(s=="Create a termbase") return "Creu cronfa dermau";
  if(s=="Administration") return "Gweinyddu";
  if(s=="Users") return "Defnyddwyr";
  if(s=="Termbases") return "Cronfeydd Termau";
  if(s=="smart search") return "chwilio clyfar";
  if(s=="complete term") return "term cyflawn";
  if(s=="start of term") return "dechrau'r term";
  if(s=="end of term") return "diwedd y term";
  if(s=="any part of term") return "unrhyw ran o'r term";
  if(s=="any part except start or end") return "unrhyw ran o'r term heblaw'r dechrau a'r diwedd";
  if(s=="search in all languages") return "chwilio ym mhob iaith";
  if(s=="Configuration") return "Cyflunio";
  if(s=="ADMIN") return "GWEIN";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "MAES";
  if(s=="DEF") return "DIFF";
  if(s=="XMPL") return "ENGH"
  if(s=="CHECKING STATUS") return "STATWS GWIRIO";
  if(s=="PUBLISHING STATUS") return "STATWS CYHOEDDI";
  if(s=="TERMS") return "TERMAU";
  if(s=="DOMAINS") return "MEYSYDD";
  if(s=="term") return "term";
  if(s=="clarification") return "eglurhad";
  if(s=="acceptability") return "derbynioldeb";
  if(s=="source") return "ffynhonnell";
  if(s=="inflected form") return "ffurfdroad";
  if(s=="annotation") return "arnodiad";
  if(s=="domain") return "maes";
  if(s=="part of speech") return "rhan ymadrodd";
  if(s=="inflection") return "ffurfdroad";
  if(s=="language of origin") return "iaith wreiddiol";
  if(s=="symbol") return "symbol";
  if(s=="trademark") return "nod masnach";
  if(s=="registered trademark") return "nod masnach cofrestredig";
  if(s=="proper noun") return "enw priod";
  if(s=="formatting") return "fformat";
  if(s=="italic") return "italig";
  if(s=="Created") return "Crëwyd";
  if(s=="Changed") return "Diwygiwyd";
  if(s=="Deleted") return "Dilëwyd";
  if(s=="Bulk-deleted") return "Dilëwyd fel rhan o sypyn";
  if(s=="while uploading") return "tra'n uwchlwytho";
  if(s=="By") return "Gan";
  if(s=="When") return "Pryd";
  if(s=="any checking status") return "unrhyw statws gwirio";
  if(s=="any publishing status") return "unrhyw statws cyhoeddi";
  if(s=="any language") return "unrhyw iaith";
  if(s=="any acceptability or no acceptability") return "unrhyw statws derbynioldeb neu heb statws derbynioldeb";
  if(s=="any acceptability") return "unrhyw statws derbynioldeb";
  if(s=="no acceptability") return "heb statws derbynioldeb";
  if(s=="any domain or no domain") return "unrhyw faes neu heb faes";
  if(s=="any domain") return "unrhyw faes";
  if(s=="no domain") return "heb faes";
  if(s=="LAST MAJOR UPDATE") return "DIWEDDARIAD DIWETHAF O BWYS";
  if(s=="set to today") return "gosod i heddiw";
  if(s=="Invalid e-mail address or password.") return "Cyfeiriad e-bost neu gyfrinair annilys.";
  if(s=="INTR") return "RHAG";
  if(s=="COLL") return "CASG";
  if(s=="INTROS") return "RHAGARWEINIADAU";
  if(s=="DEFINITIONS") return "DIFFINIADAU";
  if(s=="EXAMPLES") return "ENGHREIFFTIAU";
  if(s=="COLLECTIONS") return "CASGLIADAU";
  if(s=="definition") return "diffiniad";
  if(s=="example") return "enghraifft";
  if(s=="sentence") return "brawddeg";
  if(s=="collection") return "casgliad";
  if(s=="any collection or no collection") return "unrhyw gasgliad neu heb gasgliad";
  if(s=="any collection") return "unrhyw gasgliad";
  if(s=="no collection") return "heb gasgliad";
  if(s=="comments") return "sylwadau";
  if(s=="with or without comments") return "gyda neu heb sylwadau";
  if(s=="with comments") return "gyda sylwadau";
  if(s=="without comments") return "heb sylwadau";
  if(s=="my comments") return "fy sylwadau i";
  if(s=="with or without my comments") return "gyda neu heb fy sylwadau i";
  if(s=="with my comments") return "gyda fy sylwadau i";
  if(s=="without my comments") return "heb fy sylwadau i";
  if(s=="other people's comments") return "sylwadau pobl eraill";
  if(s=="with or without other people's comments") return "gyda neu heb sylwadau pobl eraill";
  if(s=="with other people's comments") return "gyda sylwadau pobl eraill";
  if(s=="without other people's comments") return "heb sylwadau pobl eraill";
  if(s=="EXTRANET") return "ALLRWYD";
  if(s=="EXT") return "ALL";
  if(s=="EXTRANETS") return "ALLRWYDI";
  if(s=="extranet") return "allrwyd";
  if(s=="any extranet or no extranet") return "unrhyw allrwyd neu heb allrwyd";
  if(s=="any extranet") return "unrhyw allrwyd";
  if(s=="no extranet") return "heb allrwyd";
  if(s=="sorting language") return "iaith drefnu";
  if(s=="Create mutual cross-references") return "Creu croesgyfeiriadau dwy ffordd";
  if(s=="Remove mutual cross-references") return "Diddymu croesgyfeiriadau dwy ffordd";
  if(s=="Merge into a single entry") return "Cyfuno yn un cofnod";
  if(s=="SEE ALSO") return "GW. HEFYD";
  if(s=="add to worklist") return "ychwanegu at y rhestr waith";
  if(s=="Domains") return "Meysydd";
  if(s=="Part-of-speech labels") return "Labeli rhan ymadrodd";
  if(s=="Inflection labels") return "Labeli ffurfdroadau";
  if(s=="Acceptability labels") return "Labeli derbynioldeb";
  if(s=="Sources") return "Ffynonellau";
  if(s=="Collections") return "Casgliadau";
  if(s=="Tags") return "Tagiau";
  if(s=="Extranets") return "Allrwydi";
  if(s=="Name and blurb") return "Enw a broliant";
  if(s=="Features") return "Nodweddion";
  if(s=="Languages") return "Ieithoedd";
  if(s=="Publishing") return "Cyhoeddi";
  if(s=="Change the termbase's URL") return "Newid URL y gronfa dermau";
  if(s=="Delete the termbase") return "Dileu'r gronfa dermau";
  if(s=="TITLE") return "TEITL";
  if(s=="abbreviation") return "byrfodd";
  if(s=="LANGUAGES") return "IEITHOEDD";
  if(s=="select all") return "dewis y cyfan";
  if(s=="unselect all") return "dad-ddewis y cyfan";
  if(s=="PRIORITY") return "BLAENORIAETH";
  if(s=="high") return "uchel";
  if(s=="medium") return "canolig";
  if(s=="low") return "isel";
  if(s=="USERS") return "DEFNYDDWYR";
  if(s=="e-mail address") return "cyfeiriad e-bost";
  if(s=="user") return "defnyddiwr";
  if(s=="Alphabetical order") return "Trefn yr wyddor";
  if(s=="Similar terms (click to insert)") return "Termau tebyg (cliciwch i ychwanegu)";
  if(s=="Other entries that share this term") return "Cofnodion eraill sy'n rhannu'r term hwn";
  if(s=="stop sharing") return "atal rhannu";
  if(s=="Change checking status to") return "Newid statws gwirio i";
  if(s=="Change publishing status to") return "Newid statws cyhoeddi i";
  if(s=="Add to extranet") return "Ychwanegu at yr allrwyd";
  if(s=="Remove from extranet") return "Tynnu o'r allrwyd";
  if(s=="checked") return "wedi'i wirio";
  if(s=="not checked") return "heb ei wirio";
  if(s=="publishable") return "cyhoeddadwy";
  if(s=="hidden") return "cudd";
  if(s=="CHECKED") return "WEDI'I WIRIO";
  if(s=="NOT CHECKED") return "HEB EI WIRIO";
  if(s=="PUBLISHABLE") return "CYHOEDDADWY";
  if(s=="HIDDEN") return "CUDD";
  if(s=="non-essential") return "anhanfodol";
  if(s=="STATUS") return "STATWS";
  if(s=="live") return "byw";
  if(s=="not live") return "heb fod yn fyw";
  if(s=="any clarification or no clarification") return "unrhyw eglurhad neu heb eglurhad";
  if(s=="any clarification") return "unrhyw eglurhad";
  if(s=="no clarification") return "heb eglurhad";
  if(s=="clarification containing...") return "eglurhad yn cynnwys...";
  if(s=="any intro or no intro") return "unrhyw gyflwyniad neu heb gyflwyniad";
  if(s=="any intro") return "unrhyw gyflwyniad";
  if(s=="no intro") return "heb gyflwyniad";
  if(s=="intro containing...") return "cyflwyniad yn cynnwys...";
  if(s=="any definition or no definition") return "unrhyw ddiffiniad neu heb ddiffiniad";
  if(s=="any definition") return "unrhyw ddiffiniad";
  if(s=="no definition") return "heb ddiffiniad";
  if(s=="definition containing...") return "diffiniad yn cynnwys...";
  if(s=="any example or no example") return "unrhyw enghraifft neu heb enghraifft";
  if(s=="any example") return "unrhyw enghraifft";
  if(s=="no example") return "heb enghraifft";
  if(s=="example containing...") return "enghraifft yn cynnwys...";
  if(s=="Automatic changes") return "Newidiadau awtomatig";
  if(s=="NAME") return "ENW";
  if(s=="BLURB") return "BROLIANT";
  if(s=="level") return "lefel";
  if(s=="reader") return "darllenwr";
  if(s=="editor") return "golygydd";
  if(s=="creator") return "crëwr";
  if(s=="administrator") return "gweinyddwr";
  if(s=="configurator") return "cyfluniwr";
  if(s=="no change") return "dim newid";
  if(s=="change to 'not checked'") return "newid i 'heb ei wirio'";
  if(s=="change to 'hidden'") return "newid i 'cudd'";
  if(s=="change to 'not checked' and 'hidden'") return "newid i 'heb ei wirio' a 'cudd'";
  if(s=="LAST SEEN") return "GWELWYD DDIWETHAF";
  if(s=="NEVER") return "BYTH";
  if(s=="No termbases") return "Dim cronfeydd termau";
  if(s=="language") return "iaith";
  if(s=="major") return "prif";
  if(s=="minor") return "llai";
  if(s=="role") return "rôl";
  if(s=="title") return "teitl";
  if(s=="ACCESS LEVEL") return "LEFEL MYNEDIAD";
  if(s=="LICENCE") return "TRWYDDED";
  if(s=="private") return "preifat";
  if(s=="public") return "cyhoeddus";
  if(s=="trigger_dateStampChange") return "newidiwyd y stamp dyddiad";
  if(s=="trigger_domainAdd") return "ychwanegwyd maes";
  if(s=="trigger_domainRemove") return "tynnwyd y maes";
  if(s=="trigger_domainReorder") return "aildrefnwyd y meysydd";
  if(s=="trigger_domainChange") return "newidiwyd y maes";
  if(s=="trigger_desigAdd") return "ychwanegwyd term";
  if(s=="trigger_desigRemove") return "tynnwyd term";
  if(s=="trigger_desigReorder") return "aildrefnwyd y termau";
  if(s=="trigger_desigClarifChange") return "newidiwyd yr esboniad";
  if(s=="trigger_desigAcceptChange") return "newidiwyd y statws derbynioldeb";
  if(s=="trigger_termLangChange") return "newidiwyd iaith y term";
  if(s=="trigger_termWordingChange") return "newidiwyd geiriad y term";
  if(s=="trigger_termInflectAdd") return "ychwanegwyd ffurfdroad";
  if(s=="trigger_termInflectRemove") return "tynnwyd ffurfdroad";
  if(s=="trigger_termInflectReorder") return "aildrefnwyd y ffurfdroadau";
  if(s=="trigger_termInflectLabelChange") return "newidiwyd label y ffurfdroad";
  if(s=="trigger_termInflectTextChange") return "newidiwyd geiriad y ffurfdroad";
  if(s=="trigger_termAnnotAdd") return "ychwanegwyd arnodyn i'r term";
  if(s=="trigger_termAnnotRemove") return "tynnwyd arnodyn o'r term";
  if(s=="trigger_termAnnotReorder") return "aildrefnwyd arnodiadau'r term";
  if(s=="trigger_termAnnotPositionChange") return "newidiwyd safle'r arnodyn i'r term";
  if(s=="trigger_termAnnotLabelChange") return "newidiwyd label y arnodyn i'r term";
  if(s=="trigger_introChange") return "newidiwyd y cyflwyniad";
  if(s=="trigger_definitionAdd") return "ychwanegwyd diffiniad";
  if(s=="trigger_definitionRemove") return "tynnwyd diffiniad";
  if(s=="trigger_definitionReorder") return "aildrefnwyd y diffiniadau";
  if(s=="trigger_definitionTextChange") return "newidiwyd geiriad y diffiniadau";
  if(s=="trigger_exampleAdd") return "ychwanegwyd enghraifft";
  if(s=="trigger_exampleRemove") return "tynnwyd enghraifft";
  if(s=="trigger_exampleReorder") return "aildrefnwyd yr enghreifftiau";
  if(s=="trigger_exampleTextAdd") return "ychwanegwyd brawddeg enghreifftiol";
  if(s=="trigger_exampleTextRemove") return "tynnwyd brawddeg enghreifftiol";
  if(s=="trigger_exampleTextReorder") return "aildrefnwyd y brawddegau enghreifftiol";
  if(s=="trigger_exampleTextChange") return "newidiwyd geiriad y brawddegau enghreifftiol";
  if(s=="trigger_collectionAdd") return "ychwanegwyd casgliad";
  if(s=="trigger_collectionRemove") return "tynnwyd casgliad";
  if(s=="trigger_collectionReorder") return "aildrefnwyd y casgliadau";
  if(s=="trigger_collectionChange") return "newidiwyd y casgliadau";
  if(s=="trigger_extranetAdd") return "ychwanegwyd allrwyd";
  if(s=="trigger_extranetRemove") return "tynnwyd allrwyd";
  if(s=="trigger_extranetReorder") return "aildrefnwyd yr allrwydi";
  if(s=="trigger_extranetChange") return "newidiwyd yr allrwyd";
  if(s=="trigger_sourceAdd") return "ychwanegwyd ffynhonnell";
  if(s=="trigger_sourceRemove") return "tynnwyd ffynhonnell";
  if(s=="trigger_sourceReorder") return "aildrefnwyd y ffynonellau";
  if(s=="trigger_sourceChange") return "newidiwyd y ffynonellau";
  if(s=="trigger_nonessentialChange") return "neidiwyd y statws anhanfodol";
  if(s=="(blank)") return "(gwag)";
  if(s=="Simple Multilingual Termbase") return "Cronfa Dermau Amlieithog Syml";
  if(s=="Simple Bilingual Termbase") return "Cronfa Dermau Ddwyieithog Syml";
  if(s=="Simple Monolingual Termbase") return "Cronfa Dermau Uniaith Syml";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Rhowch deitl ar ffurf y gall pobl ei ddarllen, e.e. \"Fy Ngeiriadur Termau Chwaraeon\". Gallwch newid hwn yn nes ymlaen.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Hwn fydd cyfeiriad eich cronfa dermau ar y we. Gallwch newid hwn yn nes ymlaen.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "Gallwch ddewis templed yma. Mae pob templed yn cynnwys rhai cofnodion enghreifftiol. Gallwch newid neu ddileu'r rhain ac addasu'r templed.";
  if(s=="Your termbase is ready.") return "Mae eich cronfa dermau yn barod.";
  if(s=="TERM OF THE DAY") return "TERM Y DYDD";
  if(s=="set to next available date") return "gosod i'r dyddiad nesaf sydd ar gael";
  if(s=="Display from") return "Dangos o";
  if(s=="Display until") return "Dangos tan";
  if(s=="News and announcements") return "Newyddion a hysbysiadau";
  if(s=="Create your account") return "Creu eich cyfrif";
  if(s=="Reset your password") return "Ailosod eich cyfrinair";
  if(s=="Terminologue signup") return "Cofrestru ar gyfer Terminologue";
  if(s=="Please follow the link below to create your Terminologue account:") return "Dilynwch y ddolen isod er mwyn creu eich cyfrif Terminologue:";
  if(s=="Terminologue password reset") return "Ailosod cyfrinair Terminologue";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Dilynwch y ddolen isod er mwyn ailosod eich cyfrinair Terminologue:";
  if(s=="This page is only available in English.") return "Dim ond yn Saesneg y mae'r dudalen hon ar gael.";
  if(s=="DRAFTING STATUS") return "STATWS DRAFFTIO";
  if(s=="draft entry") return "cofnod drafft";
  if(s=="finished entry") return "cofnod gorffenedig";
  if(s=="DRAFT") return "DRAFFT";
  if(s=="FINISHED") return "GORFFENEDIG";
  if(s=="any drafting status") return "unrhyw statws drafftio";
  if(s=="Prefabricated comments") return "Sylwadau parod";
  if(s=="NOTES") return "NODIADAU";
  if(s=="note") return "nodyn";
  if(s=="NOT") return "NOD";
  if(s=="with or without notes") return "gyda neu heb nodiadau";
  if(s=="with a note") return "gyda nodyn";
  if(s=="with a note containing...") return "gyda nodyn sy'n cynnwys...";
  if(s=="without notes") return "heb nodiadau";
  if(s=="any type") return "unrhyw fath";
  if(s=="private note, not shown on extranets") return "nodyn preifat, na fydd yn ymddangos ar allrwydi";
  if(s=="private note, shown on extranets") return "nodyn preifat a fydd yn ymddangos ar allrwydi";
  if(s=="public note") return "nodyn cyhoeddus";
  if(s=="Note types") return "Mathau o nodiadau";
  if(s=="LEVEL") return "LEFEL";
  if(s=="with a comment") return "gyda sylw";
  if(s=="with a comment containing...") return "gyda sylw sy'n cynnwys...";
  if(s=="TBX export") return "Allgludo i TBX";
  if(s=="TBX import") return "Mewngludo o TBX";
  if(s=="Empty the termbase") return "Gwagio'r gronfa dermau";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "Gofal! Rydych ar fin dileu'r gronfa dermau. Ni fydd modd ichi ddad-wneud hyn.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "Gofal! Rydych ar fin dileu'r cofnodion i gyd a'u hanes. Ni fydd modd ichi ddad-wneud hyn.";
  if(s=="RELATED TERMS") return "TERMAU CYSYLLTIEDIG";
  if(s=="Your termbase at a glance") return "Cipolwg ar eich cronfa dermau";
  if(s=="Number of entries") return "Nifer y cofnodion";
  if(s=="Number of items in history log") return "Nifer yr eitemau yn y gofrestr ddigwyddiadau";
  if(s=="Your termbase is stored in the file %F") return "Mae eich cronfa dermau wedi'i storio yn y ffeil %F";
  if(s=="File size") return "Maint y ffeil";
  if(s=="Download %F") return "Lawrlwytho %F";
  if(s=="Upload %F") return "Uwchlwytho %F";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Gwnewch yn siŵr bod y ffeil yr ydych yn ei huwchlwytho yn gronfa dermau Terminologue ddilys. Gallwch wneud niwed parhaol i'ch cronfa dermau drwy uwchlwytho ffeil o fath arall.";
  if(s=="PARENT") return "RHIANT";
  if(s=="no parent") return "dim rhiant";
  if(s=="excluding subdomains") return "heblaw is-feysydd";
  if(s=="including subdomains") return "gan gynnwys is-feysydd";
  if(s=="the entry has this domain") return "mae gan y cofnod y maes hwn";
  if(s=="the entry has only this domain") return "dim ond y maes hwn sydd gan y cofnod";
  if(s=="the entry has not only this domain") return "nid dim ond y maes hwn sydd gan y cofnod";

  //New strings, need translation:
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "Careful! If you remove yourself from this termbase you will lose access to it.";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
