function L(s, gloss){
  if(s=="only") return function(s){
    return s+" μόνο";
  };
  if(s=="READ-ONLY") return "ΜΟΝΟ ΓΙΑ ΑΝΑΓΝΩΣΗ";
  if(s=="Editing") return "Επεξεργασία";
  if(s=="Dublin City University") return "Πανεπιστήμιο του Δουβλίνου";
  if(s=="Log out") return "Αποσύνδεση";
  if(s=="Change your password") return "Αλλάξτε τον κωδικό σας";
  if(s=="Registered user login") return "Είσοδος εγγεγραμμένου χρήστη";
  if(s=="Get an account") return "Αποκτήστε λογαριασμό";
  if(s=="Forgot your password?") return "Ξεχάσατε τον κωδικό σας;";
  if(s=="E-mail address") return "Διεύθυνση ηλεκτρονικού ταχυδρομείου";
  if(s=="Password") return "Κωδικός πρόσβασης";
  if(s=="Log in") return "Σύνδεση";
  if(s=="Your termbases") return "Οι βάσεις των όρων σας";
  if(s=="You have no termbases yet.") return "Δεν έχετε ακόμη βάσεις όρων.";
  if(s=="Create a termbase") return "Δημιουργήστε μια βάση όρων";
  if(s=="Administration") return "Διαχείριση";
  if(s=="Users") return "Χρήστες";
  if(s=="Termbases") return "Βάσεις όρου";
  if(s=="smart search") return "έξυπνη αναζήτηση";
  if(s=="complete term") return "πλήρης όρος";
  if(s=="start of term") return "έναρξη του όρου";
  if(s=="end of term") return "τέλος του όρου";
  if(s=="any part of term") return "οποιοδήποτε μέρος του όρου";
  if(s=="any part except start or end") return "οποιοδήποτε μέρος εκτός από την αρχή ή το τέλος";
  if(s=="search in all languages") return "αναζήτηση σε όλες τις γλώσσες";
  if(s=="Configuration") return "Διαμόρφωση";
  if(s=="ADMIN") return "ΔΙΑΧΕΙΡΙΣΤΗΣ";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "DEF";
  if(s=="XMPL") return "XMPL";
  if(s=="CHECKING STATUS") return "ΕΛΕΓΧΟΣ ΚΑΤΑΣΤΑΣΗΣ";
  if(s=="PUBLISHING STATUS") return "ΚΑΤΑΣΤΑΣΗ ΕΚΔΟΣΗΣ";
  if(s=="TERMS") return "ΟΡΟΙ";
  if(s=="DOMAINS") return "ΤΟΜΕΙΣ";
  if(s=="term") return "όρος";
  if(s=="clarification") return "διευκρίνιση";
  if(s=="acceptability") return "δυνατότητα αποδοχής";
  if(s=="source") return "πηγή";
  if(s=="inflected form") return "επιλεγμένη μορφή";
  if(s=="annotation") return "σχόλιο";
  if(s=="domain") return "τομέα";
  if(s=="part of speech") return "μέρος του λόγου";
  if(s=="inflection") return "κλίση";
  if(s=="language of origin") return "γλώσσα προέλευσης";
  if(s=="symbol") return "σύμβολο";
  if(s=="trademark") return "εμπορικό σήμα";
  if(s=="registered trademark") return "σήμα κατατεθέν";
  if(s=="proper noun") return "κατάλληλο ουσιαστικό";
  if(s=="formatting") return "μορφοποίηση";
  if(s=="italic") return "πλάγια γραφή";
  if(s=="Created") return "Δημιουργήθηκε";
  if(s=="Changed") return "Άλλαξε";
  if(s=="Deleted") return "Διαγράφηκε";
  if(s=="Bulk-deleted") return "Μαζική διαγραφή";
  if(s=="while uploading") return "κατά τη μεταφόρτωση";
  if(s=="By") return "Με";
  if(s=="When") return "Όταν";
  if(s=="any checking status") return "οποιαδήποτε κατάσταση ελέγχου";
  if(s=="any publishing status") return "οποιαδήποτε κατάσταση έκδοσης";
  if(s=="any language") return "οποιαδήποτε γλώσσα";
  if(s=="any acceptability or no acceptability") return "οποιαδήποτε αποδοχή ή καμία αποδοχή";
  if(s=="any acceptability") return "οποιαδήποτε αποδοχή";
  if(s=="no acceptability") return "καμία αποδοχή";
  if(s=="any domain or no domain") return "οποιοδήποτε τομέα ή κανένας τομέας";
  if(s=="any domain") return "οποιοδήποτε τομέα";
  if(s=="no domain") return "κανένας τομέας";
  if(s=="LAST MAJOR UPDATE") return "ΤΕΛΕΥΤΑΙΑ ΜΕΓΑΛΗ ΕΝΗΜΕΡΩΣΗ";
  if(s=="set to today") return "Να οριστεί στο σήμερα";
  if(s=="Invalid e-mail address or password.") return "Μη έγκυρη διεύθυνση ηλ. ταχυδρομείου ή κωδικός πρόσβασης.";
  if(s=="INTR") return "INTR";
  if(s=="COLL") return "COLL";
  if(s=="INTROS") return "ΕΙΣΑΓΩΓΗ";
  if(s=="DEFINITIONS") return "ΟΡΙΣΜΟΙ";
  if(s=="EXAMPLES") return "ΠΑΡΑΔΕΙΓΜΑΤΑ";
  if(s=="COLLECTIONS") return "ΣΥΛΛΟΓΕΣ";
  if(s=="definition") return "ορισμός";
  if(s=="example") return "παράδειγμα";
  if(s=="sentence") return "πρόταση";
  if(s=="collection") return "συλλογή";
  if(s=="any collection or no collection") return "οποιαδήποτε συλλογή ή καμία συλλογή";
  if(s=="any collection") return "οποιαδήποτε συλλογή";
  if(s=="no collection") return "καμία συλλογή";
  if(s=="comments") return "σχόλια";
  if(s=="with or without comments") return "με ή χωρίς σχόλια";
  if(s=="with comments") return "με σχόλια";
  if(s=="without comments") return "ΧΩΡΙΣ ΣΧΟΛΙΑ";
  if(s=="my comments") return "τα σχόλιά μου";
  if(s=="with or without my comments") return "με ή χωρίς τα σχόλιά μου";
  if(s=="with my comments") return "με τα σχόλιά μου";
  if(s=="without my comments") return "χωρίς τα σχόλιά μου";
  if(s=="other people's comments") return "σχόλια άλλων ανθρώπων";
  if(s=="with or without other people's comments") return "με ή χωρίς σχόλια άλλων";
  if(s=="with other people's comments") return "με σχόλια άλλων";
  if(s=="without other people's comments") return "χωρίς σχόλια άλλων";
  if(s=="EXTRANET") return "Πρόσθετο δίχτυο";
  if(s=="EXT") return "EXT";
  if(s=="EXTRANETS") return "Πρόσθετα δίχτυα";
  if(s=="extranet") return "πρόσθετο δίχτυο";
  if(s=="any extranet or no extranet") return "οποιοδήποτε πρόσθετο δίχτυο ή καθόλου πρόσθετο δίχτυο";
  if(s=="any extranet") return "οποιοδήποτε πρόσθετο δίχτυο";
  if(s=="no extranet") return "χωρίς πρόσθετο δίχτυο";
  if(s=="sorting language") return "γλώσσα ταξινόμησης";
  if(s=="Create mutual cross-references") return "Δημιουργήστε αμοιβαίες παραπομπές";
  if(s=="Remove mutual cross-references") return "Καταργήστε τις αμοιβαίες παραπομπές";
  if(s=="Merge into a single entry") return "Συγχώνευση σε μία μόνο καταχώρηση";
  if(s=="SEE ALSO") return "ΔΕΙΤΕ ΕΠΙΣΗΣ";
  if(s=="add to worklist") return "προσθήκη στη λίστα εργασιών";
  if(s=="Domains") return "Τομείς";
  if(s=="Part-of-speech labels") return "Ετικέτες τμήματος του λόγου";
  if(s=="Inflection labels") return "Ετικέτες καμπής";
  if(s=="Acceptability labels") return "Ετικέτες αποδοχής";
  if(s=="Sources") return "Πηγές";
  if(s=="Collections") return "Συλλογές";
  if(s=="Tags") return "Ετικέτες";
  if(s=="Extranets") return "Πρόσθετα δίχτυα";
  if(s=="Name and blurb") return "Όνομα και περιγραφή";
  if(s=="Features") return "Χαρακτηριστικά";
  if(s=="Languages") return "Γλώσσες";
  if(s=="Publishing") return "Εκδόσεις";
  if(s=="Change the termbase's URL") return "Αλλάξτε τη διεύθυνση URL της βάσης όρων";
  if(s=="Delete the termbase") return "Διαγράψτε τη βάση όρων";
  if(s=="TITLE") return "ΤΙΤΛΟΣ";
  if(s=="abbreviation") return "συντομογραφία";
  if(s=="LANGUAGES") return "ΓΛΩΣΣΕΣ";
  if(s=="select all") return "επιλογή όλων";
  if(s=="unselect all") return "αποεπιλογή όλων";
  if(s=="PRIORITY") return "ΠΡΟΤΕΡΑΙΟΤΗΤΑ";
  if(s=="high") return "υψηλό";
  if(s=="medium") return "μεσαίο";
  if(s=="low") return "χαμηλό";
  if(s=="USERS") return "ΧΡΗΣΤΕΣ";
  if(s=="e-mail address") return "διεύθυνση ηλεκτρονικού ταχυδρομείου";
  if(s=="user") return "χρήστης";
  if(s=="Alphabetical order") return "Αλφαβητική σειρά";
  if(s=="Similar terms (click to insert)") return "Παρόμοιοι όροι (κάντε κλικ για εισαγωγή)";
  if(s=="Other entries that share this term") return "Άλλες καταχωρήσεις που μοιράζονται αυτόν τον όρο";
  if(s=="stop sharing") return "σταματήστε να μοιράζεστε";
  if(s=="Change checking status to") return "Αλλαγή κατάστασης ελέγχου σε";
  if(s=="Change publishing status to") return "Αλλαγή κατάστασης δημοσίευσης σε";
  if(s=="Add to extranet") return "Προσθήκη στο πρόσθετο δίχτυο";
  if(s=="Remove from extranet") return "Κατάργηση από το πρόσθετο δίχτυο";
  if(s=="checked") return "ελεγμένο";
  if(s=="not checked") return "δεν έχει ελεγχθεί";
  if(s=="publishable") return "δημοσιεύσιμος";
  if(s=="hidden") return "κρυμμένος";
  if(s=="CHECKED") return "ΕΛΕΓΜΕΝΟ";
  if(s=="NOT CHECKED") return "ΔΕΝ ΕΧΕΙ ΕΛΕΓΧΘΕΙ";
  if(s=="PUBLISHABLE") return "ΔΗΜΟΣΙΕΥΣΙΜΟ";
  if(s=="HIDDEN") return "ΚΡΥΦΟ";
  if(s=="non-essential") return "μη ουσιώδης";
  if(s=="STATUS") return "ΚΑΤΑΣΤΑΣΗ";
  if(s=="live") return "ζωντανά";
  if(s=="not live") return "όχι ζωντανά";
  if(s=="any clarification or no clarification") return "οποιαδήποτε διευκρίνιση ή καμία διευκρίνιση";
  if(s=="any clarification") return "οποιαδήποτε διευκρίνιση";
  if(s=="no clarification") return "καμία διευκρίνηση";
  if(s=="clarification containing...") return "διευκρίνιση που περιέχει...";
  if(s=="any intro or no intro") return "οποιαδήποτε εισαγωγή ή καμία εισαγωγή";
  if(s=="any intro") return "οποιαδήποτε εισαγωγή";
  if(s=="no intro") return "όχι εισαγωγή";
  if(s=="intro containing...") return "εισαγωγή που περιέχει...";
  if(s=="any definition or no definition") return "οποιοσδήποτε ορισμός ή κανένας ορισμός";
  if(s=="any definition") return "οποιονδήποτε ορισμό";
  if(s=="no definition") return "κανένας ορισμός";
  if(s=="definition containing...") return "ορισμός που περιέχει...";
  if(s=="any example or no example") return "οποιοδήποτε παράδειγμα ή κανένα παράδειγμα";
  if(s=="any example") return "οποιοδήποτε παράδειγμα";
  if(s=="no example") return "κανένα παράδειγμα";
  if(s=="example containing...") return "παράδειγμα που περιέχει...";
  if(s=="Automatic changes") return "Αυτόματες αλλαγές";
  if(s=="NAME") return "ΟΝΟΜΑ";
  if(s=="BLURB") return "ΑΝΑΚΟΙΝΩΣΗ";
  if(s=="level") return "επίπεδο";
  if(s=="reader") return "αναγνώστης";
  if(s=="editor") return "συντάκτης";
  if(s=="creator") return "δημιουργός";
  if(s=="administrator") return "διαχειριστής";
  if(s=="configurator") return "διαμορφωτής";
  if(s=="no change") return "καμία αλλαγή";
  if(s=="change to 'not checked'") return "αλλαγή σε 'μη ελεγμένο'";
  if(s=="change to 'hidden'") return "αλλαγή σε 'κρυφό'";
  if(s=="change to 'not checked' and 'hidden'") return "αλλαγή σε 'μη ελεγμένο' και 'κρυφό'";
  if(s=="LAST SEEN") return "ΤΕΛΕΥΤΑΙΑ ΕΜΦΑΝΙΣΗ";
  if(s=="NEVER") return "ΠΟΤΕ";
  if(s=="No termbases") return "Δεν υπάρχουν βάσεις όρων";
  if(s=="language") return "Γλώσσα";
  if(s=="major") return "σημαντικό";
  if(s=="minor") return "ανήλικος";
  if(s=="role") return "ρόλος";
  if(s=="title") return "τίτλος";
  if(s=="ACCESS LEVEL") return "ΕΠΙΠΕΔΟ ΠΡΟΣΒΑΣΗΣ";
  if(s=="LICENCE") return "ΑΔΕΙΑ ΧΡΗΣΗΣ";
  if(s=="private") return "ιδιωτικό";
  if(s=="public") return "δημόσιο";
  if(s=="trigger_dateStampChange") return "η ημερομηνία άλλαξε";
  if(s=="trigger_domainAdd") return "προστέθηκε τομέας";
  if(s=="trigger_domainRemove") return "καταργήθηκε ο τομέας";
  if(s=="trigger_domainReorder") return "αναδιάταξη τομέων";
  if(s=="trigger_domainChange") return "ο τομέας άλλαξε";
  if(s=="trigger_desigAdd") return "όρος προστέθηκε";
  if(s=="trigger_desigRemove") return "καταργήθηκε ο όρος";
  if(s=="trigger_desigReorder") return "αναδιάταξη όρων";
  if(s=="trigger_desigClarifChange") return "η διευκρίνιση άλλαξε";
  if(s=="trigger_desigAcceptChange") return "η αποδοχή άλλαξε";
  if(s=="trigger_termLangChange") return "η γλώσσα του όρου άλλαξε";
  if(s=="trigger_termWordingChange") return "άλλαξε η διατύπωση του όρου";
  if(s=="trigger_termInflectAdd") return "προστέθηκε κλιτή μορφή";
  if(s=="trigger_termInflectRemove") return "η κλιτή μορφή αφαιρέθηκε";
  if(s=="trigger_termInflectReorder") return "αναδιάταξη των κλιτών μορφών";
  if(s=="trigger_termInflectLabelChange") return "η ετικέτα μορφών με κλίση άλλαξε";
  if(s=="trigger_termInflectTextChange") return "η διατύπωση της κλιτής μορφής άλλαξε";
  if(s=="trigger_termAnnotAdd") return "προστέθηκε σχολιασμός όρου";
  if(s=="trigger_termAnnotRemove") return "καταργήθηκε ο σχολιασμός όρου";
  if(s=="trigger_termAnnotReorder") return "οι σχολιασμοί όρων αναδιατάχθηκαν";
  if(s=="trigger_termAnnotPositionChange") return "Η θέση του σχολιασμού του όρου άλλαξε";
  if(s=="trigger_termAnnotLabelChange") return "άλλαξε η ετικέτα σχολιασμού όρου";
  if(s=="trigger_introChange") return "η εισαγωγή άλλαξε";
  if(s=="trigger_definitionAdd") return "προστέθηκε ορισμός";
  if(s=="trigger_definitionRemove") return "ο ορισμός αφαιρέθηκε";
  if(s=="trigger_definitionReorder") return "οι ορισμοί αναδιατάχθηκαν";
  if(s=="trigger_definitionTextChange") return "το κείμενο του ορισμού άλλαξε";
  if(s=="trigger_exampleAdd") return "προστέθηκε παράδειγμα";
  if(s=="trigger_exampleRemove") return "το παράδειγμα αφαιρέθηκε";
  if(s=="trigger_exampleReorder") return "παραδείγματα αναδιάταξη";
  if(s=="trigger_exampleTextAdd") return "προστέθηκε παράδειγμα πρότασης";
  if(s=="trigger_exampleTextRemove") return "παραδειγματική πρόταση αφαιρέθηκε";
  if(s=="trigger_exampleTextReorder") return "παραδείγματα προτάσεων αναδιάταξη";
  if(s=="trigger_exampleTextChange") return "η διατύπωση της πρότασης του παραδείγματος άλλαξε";
  if(s=="trigger_collectionAdd") return "προστέθηκε συλλογή";
  if(s=="trigger_collectionRemove") return "η συλλογή αφαιρέθηκε";
  if(s=="trigger_collectionReorder") return "συλλογές αναπαραγγελθεί";
  if(s=="trigger_collectionChange") return "η συλλογή άλλαξε";
  if(s=="trigger_extranetAdd") return "προστέθηκε το πρόσθετο δίκτυο";
  if(s=="trigger_extranetRemove") return "αφαιρέθηκε το πρόσθετο δίκτυο";
  if(s=="trigger_extranetReorder") return "τα πρόσθετα δίκτυα αναδιατάχθηκαν";
  if(s=="trigger_extranetChange") return "το πρόσθετο δίκτυο άλλαξε";
  if(s=="trigger_sourceAdd") return "προστέθηκε πηγή";
  if(s=="trigger_sourceRemove") return "η πηγή αφαιρέθηκε";
  if(s=="trigger_sourceReorder") return "η πηγή αναδιατάχθηκε";
  if(s=="trigger_sourceChange") return "η πηγή άλλαξε";
  if(s=="trigger_nonessentialChange") return "μη ουσιώδης αλλαγή";
  if(s=="(blank)") return "(κενό)";
  if(s=="Simple Multilingual Termbase") return "Απλή πολύγλωσση βάση όρων";
  if(s=="Simple Bilingual Termbase") return "Απλή δίγλωσση βάση όρου";
  if(s=="Simple Monolingual Termbase") return "Απλή μονόγλωσση βάση όρου";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Εισαγάγετε έναν τίτλο αναγνώσιμο από τον άνθρωπο, όπως \"My Dictionary of Sports Terms\". Θα μπορείτε να το αλλάξετε αργότερα.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Αυτή θα είναι η διεύθυνση της βάσης όρων σας στον ιστό. Θα μπορείτε να το αλλάξετε αργότερα.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "Μπορείτε να επιλέξετε ένα πρότυπο εδώ για να ξεκινήσετε. Κάθε πρότυπο συνοδεύεται από μερικές καταχωρήσεις δειγμάτων. Θα μπορείτε να τα αλλάξετε ή να τα διαγράψετε και να προσαρμόσετε το πρότυπο.";
  if(s=="Your termbase is ready.") return "Η βάση όρων σας είναι έτοιμη.";
  if(s=="TERM OF THE DAY") return "Ο ΟΡΟΣ ΤΗΣ ΗΜΕΡΑΣ";
  if(s=="set to next available date") return "Να οριστεί στην επόμενη διαθέσιμη ημερομηνία";
  if(s=="Display from") return "Εμφάνιση από";
  if(s=="Display until") return "Εμφάνιση μέχρι";
  if(s=="News and announcements") return "Ειδήσεις και ανακοινώσεις";
  if(s=="Create your account") return "Δημιούργησε τον λογαριασμό σου";
  if(s=="Reset your password") return "Επαναφορά του κωδικού πρόσβασής σας";
  if(s=="Terminologue signup") return "Εγγραφή ορολογίας";
  if(s=="Please follow the link below to create your Terminologue account:") return "Ακολουθήστε τον παρακάτω σύνδεσμο για να δημιουργήσετε τον λογαριασμό σας στο Terminologue:";
  if(s=="Terminologue password reset") return "Επαναφορά κωδικού πρόσβασης ορολογίας";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Ακολουθήστε τον παρακάτω σύνδεσμο για να επαναφέρετε τον κωδικό πρόσβασής σας στο Terminologue:";
  if(s=="This page is only available in English.") return "Αυτή η σελίδα είναι διαθέσιμη μόνο στα Αγγλικά.";
  if(s=="DRAFTING STATUS") return "ΚΑΤΑΣΤΑΣΗ ΣΧΕΔΙΑΣΜΟΥ";
  if(s=="draft entry") return "προσχέδιο καταχώρισης";
  if(s=="finished entry") return "τελειωμένη είσοδος";
  if(s=="DRAFT") return "ΠΡΟΣΧΕΔΙΟ";
  if(s=="FINISHED") return "ΟΛΟΚΛΗΡΩΘΗΚΕ";
  if(s=="any drafting status") return "οποιαδήποτε κατάσταση σύνταξης";
  if(s=="Prefabricated comments") return "Προκατασκευασμένα σχόλια";
  if(s=="NOTES") return "ΣΗΜΕΙΩΣΕΙΣ";
  if(s=="note") return "Σημείωση";
  if(s=="NOT") return "ΔΕΝ";
  if(s=="with or without notes") return "με ή χωρίς σημειώσεις";
  if(s=="with a note") return "με μια σημείωση";
  if(s=="with a note containing...") return "με ένα σημείωμα που περιέχει...";
  if(s=="without notes") return "χωρίς σημειώσεις";
  if(s=="any type") return "οποιοσδήποτε τύπος";
  if(s=="private note, not shown on extranets") return "ιδιωτική σημείωση, δεν εμφανίζεται σε πρόσθετο δίκτυο";
  if(s=="private note, shown on extranets") return "ιδιωτική σημείωση, που εμφανίζεται σε πρόσθετα δίκτυα";
  if(s=="public note") return "δημόσια σημείωση";
  if(s=="Note types") return "Τύποι σημειώσεων";
  if(s=="LEVEL") return "ΕΠΙΠΕΔΟ";
  if(s=="with a comment") return "με ένα σχόλιο";
  if(s=="with a comment containing...") return "με ένα σχόλιο που περιέχει...";
  if(s=="TBX export") return "Εξαγωγή TBX";
  if(s=="TBX import") return "Εισαγωγή TBX";
  if(s=="Empty the termbase") return "Αδειάστε τη βάση όρων";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "Προσοχή τώρα! Πρόκειται να διαγράψετε αυτήν τη βάση όρων. Δεν θα μπορείτε να το αναιρέσετε.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "Προσοχή τώρα! Πρόκειται να διαγράψετε όλες τις καταχωρήσεις και το ιστορικό τους. Δεν θα μπορείτε να το αναιρέσετε.";
  if(s=="RELATED TERMS") return "ΣΧΕΤΙΚΟΙ ΟΡΟΙ";
  if(s=="Your termbase at a glance") return "Η βάση των όρων σας με μια ματιά";
  if(s=="Number of entries") return "Αριθμός καταχωρήσεων";
  if(s=="Number of items in history log") return "Αριθμός στοιχείων στο αρχείο καταγραφής ιστορικού";
  if(s=="Your termbase is stored in the file %F") return "Η βάση όρων σας αποθηκεύεται στο αρχείο %F";
  if(s=="File size") return "Μέγεθος αρχείου";
  if(s=="Download %F") return "Λήψη %F";
  if(s=="Upload %F") return "Μεταφόρτωση %F";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Βεβαιωθείτε ότι το αρχείο που ανεβάζετε είναι έγκυρη βάση όρων ορολογίας. Αν ανεβάσετε κάτι άλλο θα κάνετε ανεπανόρθωτη ζημιά στη βάση όρων σας.";
  if(s=="PARENT") return "ΓΟΝΕΑΣ";
  if(s=="no parent") return "κανένας γονέας";
  if(s=="excluding subdomains") return "εξαιρουμένων των υποτομέων";
  if(s=="including subdomains") return "συμπεριλαμβανομένων των υποτομέων";
  if(s=="the entry has this domain") return "η καταχώρηση έχει αυτόν τον τομέα";
  if(s=="the entry has only this domain") return "η καταχώρηση έχει μόνο αυτόν τον τομέα";
  if(s=="the entry has not only this domain") return "η καταχώρηση δεν έχει μόνο αυτόν τον τομέα";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "Προσοχή! Εάν καταργήσετε τον εαυτό σας από αυτήν τη βάση όρων, θα χάσετε την πρόσβαση σε αυτήν.";

  //New strings, need translation:
  if(s=="Leave this termbase") return s;

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
