function L(s, gloss){
  if(s=="only") return function(s){
    return "solo "+s;
  };
  if(s=="READ-ONLY") return "SOLO LECTURA";
  if(s=="Editing") return "Edición";
  if(s=="Dublin City University") return "Universidad Ciudad de Dublín";
  if(s=="Log out") return "Cerrar sesión";
  if(s=="Change your password") return "Cambiar la contraseña";
  if(s=="Registered user login") return "Inicio de sesión de usuario/a registrado/a";
  if(s=="Get an account") return "Crear una cuenta";
  if(s=="Forgot your password?") return "¿Olvidaste la contraseña?";
  if(s=="E-mail address") return "Dirección de correo electrónico";
  if(s=="Password") return "Contraseña";
  if(s=="Log in") return "Iniciar sesión";
  if(s=="Your termbases") return "Tus bases de datos terminológicas";
  if(s=="You have no termbases yet.") return "Aún no tienes bases de datos terminológicas.";
  if(s=="Create a termbase") return "Crear una base de datos terminológica";
  if(s=="Administration") return "Administración";
  if(s=="Users") return "Usuarios/as";
  if(s=="Termbases") return "Bases de datos terminológicas";
  if(s=="smart search") return "búsqueda inteligente";
  if(s=="complete term") return "término completo";
  if(s=="start of term") return "comienzo del término";
  if(s=="end of term") return "final del término";
  if(s=="any part of term") return "cualquier parte del término";
  if(s=="any part except start or end") return "cualquier parte salvo el principio y el final";
  if(s=="search in all languages") return "buscar en todos los idiomas";
  if(s=="Configuration") return "Configuración";
  if(s=="ADMIN") return "ADMIN";
  if(s=="TRM") return "TÉRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "DEF";
  if(s=="XMPL") return "EJ.USO";
  if(s=="CHECKING STATUS") return "ESTADO DE REVISIÓN";
  if(s=="PUBLISHING STATUS") return "ESTADO DE PUBLICACIÓN";
  if(s=="TERMS") return "TÉRMINOS";
  if(s=="DOMAINS") return "DOMINIOS";
  if(s=="term") return "término";
  if(s=="clarification") return "aclaración";
  if(s=="acceptability") return "aceptabilidad";
  if(s=="source") return "fuente";
  if(s=="inflected form") return "forma gramatical";
  if(s=="annotation") return "anotación";
  if(s=="domain") return "dominio";
  if(s=="part of speech") return "categoría gramatical";
  if(s=="inflection") return "flexión";
  if(s=="language of origin") return "lengua de origen";
  if(s=="symbol") return "símbolo";
  if(s=="trademark") return "marca comercial";
  if(s=="registered trademark") return "marca registrada";
  if(s=="proper noun") return "nombre propio";
  if(s=="formatting") return "formato";
  if(s=="italic") return "cursiva";
  if(s=="Created") return "Creado";
  if(s=="Changed") return "Cambiado";
  if(s=="Deleted") return "Eliminado";
  if(s=="Bulk-deleted") return "Eliminado de forma masiva";
  if(s=="while uploading") return "durante la subida";
  if(s=="By") return "Por";
  if(s=="When") return "Cuándo";
  if(s=="any checking status") return "cualquier estado de revisión";
  if(s=="any publishing status") return "cualquier estado de publicación";
  if(s=="any language") return "cualquier idioma";
  if(s=="any acceptabilty or no acceptability") return "cualquier aceptabilidad o ninguna aceptabilidad";
  if(s=="any acceptabilty") return "cualquier aceptabilidad";
  if(s=="no acceptability") return "ninguna aceptabilidad";
  if(s=="any domain or no domain") return "cualquier dominio o ningún dominio";
  if(s=="any domain") return "cualquier dominio";
  if(s=="no domain") return "ningún dominio";
  if(s=="LAST MAJOR UPDATE") return "ÚLTIMA ACTUALIZACIÓN IMPORTANTE";
  if(s=="set to today") return "Establecer a fecha de hoy";
  if(s=="Invalid e-mail address or password.") return "Dirección de correo electrónico o contraseña inválidos.";
  if(s=="INTR") return "INTR";
  if(s=="COLL") return "COLEC";
  if(s=="INTROS") return "INTRODUCCIÓN";
  if(s=="DEFINITIONS") return "DEFINICIONES";
  if(s=="EXAMPLES") return "EJEMPLOS";
  if(s=="COLLECTIONS") return "COLECCIONES";
  if(s=="definition") return "definición";
  if(s=="example") return "ejemplo";
  if(s=="sentence") return "oración";
  if(s=="collection") return "colección";
  if(s=="any collection or no collection") return "cualquier colección o ninguna colección";
  if(s=="any collection") return "cualquier colección";
  if(s=="no collection") return "ninguna colección";
  if(s=="comments") return "comentarios";
  if(s=="with or without comments") return "con o sin comentarios";
  if(s=="with comments") return "con comentarios";
  if(s=="without comments") return "sin comentarios";
  if(s=="my comments") return "mis comentarios";
  if(s=="with or without my comments") return "con o sin mis comentarios";
  if(s=="with my comments") return "con mis comentarios";
  if(s=="without my comments") return "sin mis comentarios";
  if(s=="other people's comments") return "comentarios de otras personas";
  if(s=="with or without other people's comments") return "con o sin comentarios de otras personas";
  if(s=="with other people's comments") return "con comentarios de otras personas";
  if(s=="without other people's comments") return "sin comentarios de otras personas";
  if(s=="EXTRANET") return "EXTRANET";
  if(s=="EXT") return "EXT";
  if(s=="EXTRANETS") return "EXTRANETS";
  if(s=="extranet") return "extranet";
  if(s=="any extranet or no extranet") return "cualquier extranet o ninguna extranet";
  if(s=="any extranet") return "cualquier extranet";
  if(s=="no extranet") return "ninguna extranet";
  if(s=="sorting language") return "ordenar por idioma";
  if(s=="Create mutual cross-references") return "Crear referencias cruzadas mutuas";
  if(s=="Remove mutual cross-references") return "Eliminar referencias cruzadas mutuas";
  if(s=="Merge into a single entry") return "Combinar en una sola entrada";
  if(s=="SEE ALSO") return "VÉASE TAMBIÉN";
  if(s=="add to worklist") return "añadir a la lista de tareas";
  if(s=="Domains") return "Dominios";
  if(s=="Part-of-speech labels") return "Etiquetas de categoría gramatical";
  if(s=="Inflection labels") return "Etiquetas de flexión";
  if(s=="Acceptability labels") return "Etiquetas de aceptabilidad";
  if(s=="Sources") return "Fuentes";
  if(s=="Collections") return "Colecciones";
  if(s=="Tags") return "Etiquetas";
  if(s=="Extranets") return "Extranets";
  if(s=="Name and blurb") return "Nombre y comentario promocional";
  if(s=="Features") return "Características";
  if(s=="Languages") return "Idiomas";
  if(s=="Publishing") return "Publicación";
  if(s=="Change the termbase's URL") return "Cambiar la dirección URL de la base de datos terminológica";
  if(s=="Delete the termbase") return "Eliminar la base de datos terminológica";
  if(s=="TITLE") return "TÍTULO";
  if(s=="abbreviation") return "abreviatura";
  if(s=="LANGUAGES") return "IDIOMAS";
  if(s=="select all") return "seleccionar todos";
  if(s=="unselect all") return "deseleccionar todos";
  if(s=="PRIORITY") return "PRIORIDAD";
  if(s=="high") return "alta";
  if(s=="medium") return "media";
  if(s=="low") return "baja";
  if(s=="USERS") return "USUARIOS/AS";
  if(s=="e-mail address") return "dirección de correo electrónico";
  if(s=="user") return "usuario/a";
  if(s=="Alphabetical order") return "Orden alfabético";
  if(s=="Similar terms (click to insert)") return "Términos similares (haz clic para insertar)";
  if(s=="Other entries that share this term") return "Otras entradas que comparten este término";
  if(s=="stop sharing") return "dejar de compartir";
  if(s=="Change checking status to") return "Cambiar el estado de revisión a";
  if(s=="Change publishing status to") return "Cambiar el estado de publicación a";
  if(s=="Add to extranet") return "Añadir a la extranet";
  if(s=="Remove from extranet") return "Eliminar de la extranet";
  if(s=="checked") return "revisado";
  if(s=="not checked") return "no revisado";
  if(s=="publishable") return "publicable";
  if(s=="hidden") return "oculto";
  if(s=="CHECKED") return "REVISADO";
  if(s=="NOT CHECKED") return "NO REVISADO";
  if(s=="PUBLISHABLE") return "PUBLICABLE";
  if(s=="HIDDEN") return "OCULTO";
  if(s=="non-essential") return "no esencial";
  if(s=="STATUS") return "ESTADO";
  if(s=="live") return "activo";
  if(s=="not live") return "inactivo";
  if(s=="any clarification or no clarification") return "cualquier aclaración o ninguna aclaración";
  if(s=="any clarification") return "cualquier aclaración";
  if(s=="no clarification") return "ninguna aclaración";
  if(s=="clarification containing...") return "aclaración que contenga...";
  if(s=="any intro or no intro") return "cualquier introducción o ninguna introducción";
  if(s=="any intro") return "cualquier introducción";
  if(s=="no intro") return "ninguna introducción";
  if(s=="intro containing...") return "introducción que contenga...";
  if(s=="any definition or no definition") return "cualquier definición o ninguna definición";
  if(s=="any definition") return "cualquier definición";
  if(s=="no definition") return "ninguna definición";
  if(s=="definition containing...") return "definición que contenga...";
  if(s=="any example or no example") return "cualquier ejemplo o ningún ejemplo";
  if(s=="any example") return "cualquier ejemplo";
  if(s=="no example") return "ningún ejemplo";
  if(s=="example containing...") return "ejemplo que contenga...";
  if(s=="Automatic changes") return "Cambios automáticos";
  if(s=="NAME") return "NOMBRE";
  if(s=="BLURB") return "COMENTARIO PROMOCIONAL";
  if(s=="level") return "nivel";
  if(s=="reader") return "lector/a";
  if(s=="editor") return "editor/a";
  if(s=="creator") return "creador/a";
  if(s=="administrator") return "administrador/a";
  if(s=="configurator") return "configurador/a";
  if(s=="no change") return "ningún cambio";
  if(s=="change to 'not checked'") return "cambio a 'no revisado'";
  if(s=="change to 'hidden'") return "cambio a 'oculto'";
  if(s=="change to 'not checked' and 'hidden'") return "cambio a 'no revisado' y 'oculto'";
  if(s=="LAST SEEN") return "VISTO POR ÚLTIMA VEZ";
  if(s=="NEVER") return "NUNCA";
  if(s=="No termbases") return "Ninguna base de datos terminológica";
  if(s=="language") return "idioma";
  if(s=="major") return "importante";
  if(s=="minor") return "secundario";
  if(s=="role") return "rol";
  if(s=="title") return "título";
  if(s=="ACCESS LEVEL") return "NIVEL DE ACCESO";
  if(s=="LICENCE") return "LICENCIA";
  if(s=="private") return "privada";
  if(s=="public") return "pública";
  if(s=="trigger_dateStampChange") return "fecha cambiada";
  if(s=="trigger_domainAdd") return "dominio añadido";
  if(s=="trigger_domainRemove") return "dominio eliminado";
  if(s=="trigger_domainReorder") return "dominios reordenados";
  if(s=="trigger_domainChange") return "dominio cambiado";
  if(s=="trigger_desigAdd") return "término añadido";
  if(s=="trigger_desigRemove") return "término eliminado";
  if(s=="trigger_desigReorder") return "términos reordenados";
  if(s=="trigger_desigClarifChange") return "aclaración cambiada";
  if(s=="trigger_desigAcceptChange") return "aceptabilidad cambiada";
  if(s=="trigger_termLangChange") return "idioma del término cambiado";
  if(s=="trigger_termWordingChange") return "formulación del término cambiada";
  if(s=="trigger_termInflectAdd") return "forma gramatical añadida";
  if(s=="trigger_termInflectRemove") return "forma gramatical eliminada";
  if(s=="trigger_termInflectReorder") return "formas gramaticales reordenadas";
  if(s=="trigger_termInflectLabelChange") return "etiqueta de forma gramatical cambiada";
  if(s=="trigger_termInflectTextChange") return "formulación de forma gramatical cambiada";
  if(s=="trigger_termAnnotAdd") return "anotación del término añadida";
  if(s=="trigger_termAnnotRemove") return "anotación del término eliminada";
  if(s=="trigger_termAnnotReorder") return "anotaciones de los términos reordenadas";
  if(s=="trigger_termAnnotPositionChange") return "posición de la anotación del término cambiada";
  if(s=="trigger_termAnnotLabelChange") return "etiqueta de la anotación del término cambiada";
  if(s=="trigger_introChange") return "introducción cambiada";
  if(s=="trigger_definitionAdd") return "definición añadida";
  if(s=="trigger_definitionRemove") return "definición eliminada";
  if(s=="trigger_definitionReorder") return "definiciones reordenadas";
  if(s=="trigger_definitionTextChange") return "texto de la definición cambiado";
  if(s=="trigger_exampleAdd") return "ejemplo añadido";
  if(s=="trigger_exampleRemove") return "ejemplo eliminado";
  if(s=="trigger_exampleReorder") return "ejemplos reordenados";
  if(s=="trigger_exampleTextAdd") return "oración de ejemplo añadida";
  if(s=="trigger_exampleTextRemove") return "oración de ejemplo eliminada";
  if(s=="trigger_exampleTextReorder") return "oraciones de ejemplo reordenadas";
  if(s=="trigger_exampleTextChange") return "formulación de la oración de ejemplo cambiada";
  if(s=="trigger_collectionAdd") return "colección añadida";
  if(s=="trigger_collectionRemove") return "colección eliminada";
  if(s=="trigger_collectionReorder") return "colecciones reordenadas";
  if(s=="trigger_collectionChange") return "colección cambiada";
  if(s=="trigger_extranetAdd") return "extranet añadida";
  if(s=="trigger_extranetRemove") return "extranet eliminada";
  if(s=="trigger_extranetReorder") return "extranets reordenadas";
  if(s=="trigger_extranetChange") return "extranet cambiada";
  if(s=="trigger_sourceAdd") return "fuente añadida";
  if(s=="trigger_sourceRemove") return "fuente eliminada";
  if(s=="trigger_sourceReorder") return "fuente reordenada";
  if(s=="trigger_sourceChange") return "fuente cambiada";
  if(s=="trigger_nonessentialChange") return "no esencialidad cambiada";
  if(s=="(blank)") return "(en blanco)";
  if(s=="Simple Multilingual Termbase") return "Base de datos terminológica sencilla multilingüe";
  if(s=="Simple Bilingual Termbase") return "Base de datos terminológica sencilla bilingüe";
  if(s=="Simple Monolingual Termbase") return "Base de datos terminológica sencilla monolingüe";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Escribe un título en formato legible tal como \"Mi diccionario de términos deportivos\". Podrás cambiarlo más adelante.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Esta será la dirección web de tu base de datos terminológica. Podrás cambiarla más adelante.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "Selecciona aquí una plantilla para comenzar. Cada una de ellas es personalizable y contiene unas cuantas entradas, las cuales se pueden modificar o eliminar.";
  if(s=="Your termbase is ready.") return "Tu base de datos terminológica está lista.";
  if(s=="TERM OF THE DAY") return "TÉRMINO DEL DÍA";
  if(s=="set to next available date") return "establecer a próxima fecha disponible";
  if(s=="Display from") return "Mostrar desde";
  if(s=="Display until") return "Mostrar hasta";
  if(s=="News and announcements") return "Noticias y anuncios";
  if(s=="Create your account") return "Crea una cuenta";
  if(s=="Reset your password") return "Restablece tu contraseña";
  if(s=="Terminologue signup") return "Inscripción a Terminologue";
  if(s=="Please follow the link below to create your Terminologue account:") return "Haz clic en el siguiente enlace para crear una cuenta en Terminologue:";
  if(s=="Terminologue password reset") return "Restablecer la contraseña de Terminologue";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Haz clic en el siguiente enlace para restablecer tu contraseña de Terminologue:";
  if(s=="This page is only available in English.") return "Esta página solo está disponible en inglés.";
  if(s=="DRAFTING STATUS") return "ESTADO DEL BORRADOR";
  if(s=="draft entry") return "entrada provisional";
  if(s=="finished entry") return "entrada finalizada";
  if(s=="DRAFT") return "BORRADOR";
  if(s=="FINISHED") return "ACABADO";
  if(s=="any drafting status") return "cualquier estado del borrador";
  if(s=="Prefabricated comments") return "Comentarios predeterminados";
  if(s=="NOTES") return "NOTAS";
  if(s=="note") return "nota";
  if(s=="NOT") return "NO";
  if(s=="with or without notes") return "con o sin notas";
  if(s=="with a note") return "con una nota";
  if(s=="with a note containing...") return "con una nota que contenga...";
  if(s=="without notes") return "sin notas";
  if(s=="any type") return "cualquier tipo";
  if(s=="private note, not shown on extranets") return "nota privada, no mostrada en extranets";
  if(s=="private note, shown on extranets") return "nota privada, mostrada en extranets";
  if(s=="public note") return "nota pública";
  if(s=="Note types") return "Tipos de nota";
  if(s=="LEVEL") return "NIVEL";
  if(s=="with a comment") return "con un comentario";
  if(s=="with a comment containing...") return "con un comentario que contenga...";
  if(s=="TBX export") return "Exportar TBX";
  if(s=="TBX import") return "Importar TBX";
  if(s=="Empty the termbase") return "Vaciar la base de datos terminológica";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "¡Cuidado! Estás a punto de eliminar la base de datos terminológica. Esta acción no se puede deshacer.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "¡Cuidado! Estás a punto de eliminar todas las entradas y su historial. Esta acción no se puede deshacer.";
  if(s=="RELATED TERMS") return "TÉRMINOS RELACIONADOS";
  if(s=="Your termbase at a glance") return "Un vistazo rápido a tu base de datos terminológica";
  if(s=="Number of entries") return "Número de entradas";
  if(s=="Number of items in history log") return "Número de elementos en el registro histórico";
  if(s=="Your termbase is stored in the file %F") return "Tu base de datos terminológica se almacena en el archivo %F";
  if(s=="File size") return "Tamaño del archivo";
  if(s=="Download %F") return "Descargar %F";
  if(s=="Upload %F") return "Subir %F";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Asegúrate de que el archivo que subas es una base de datos terminológica válida de Terminologue. Si subes cualquier otra cosa, causarás un daño irreparable en tu base de datos.";
  if(s=="PARENT") return "ELEMENTO RAÍZ";
  if(s=="no parent") return "sin elemento raíz";
  if(s=="excluding subdomains") return "excluyendo subdominios";
  if(s=="including subdomains") return "incluyendo subdominios";
  if(s=="the entry has this domain") return "la entrada tiene este dominio";
  if(s=="the entry has only this domain") return "la entrada tiene solo este dominio";
  if(s=="the entry has not only this domain") return "la entrada no solo tiene este dominio";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "¡Cuidado! Perderás el acceso a esta base de datos terminológica si te eliminas a ti mismo/a.";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
