function L(s, gloss){
  if(s=="only") return function(s){
    return s+" bakarrik";
  };
  if(s=="READ-ONLY") return "IRAKURTZEKO SOILIK";
  if(s=="Editing") return "Edizioa";
  if(s=="Dublin City University") return "Dublin City University";
  if(s=="Log out") return "Saioa amaitu";
  if(s=="Change your password") return "Pasahitza aldatu";
  if(s=="Registered user login") return "Erregistratutako erabiltzaile-sarrera";
  if(s=="Get an account") return "Kontu bat lortu";
  if(s=="Forgot your password?") return "Pasahitza ahaztu duzu?";
  if(s=="E-mail address") return "Helbide elektronikoa";
  if(s=="Password") return "Pasahitza";
  if(s=="Log in") return "Sartu";
  if(s=="Your termbases") return "Zure termino-baseak";
  if(s=="You have no termbases yet.") return "Oraindik ez duzu termino-baserik.";
  if(s=="Create a termbase") return "Sortu termino-base bat";
  if(s=="Administration") return "Administrazioa";
  if(s=="Users") return "Erabiltzaileak";
  if(s=="Termbases") return "Termino-baseak";
  if(s=="smart search") return "bilaketa adimenduna";
  if(s=="complete term") return "Terminoa osatu";
  if(s=="start of term") return "terminoaren hasiera";
  if(s=="end of term") return "terminoaren amaiera";
  if(s=="any part of term") return "terminoaren edozein zati";
  if(s=="any part except start or end") return "edozein zati hasiera edo bukaera baino";
  if(s=="search in all languages") return "bilatu hizkuntza guztietan";
  if(s=="Configuration") return "Konfigurazioa";
  if(s=="ADMIN") return "ADMIN";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "DEF";
  if(s=="XMPL") return "ADIB";
  if(s=="CHECKING STATUS") return "EGOERA EGIAZTAZEN";
  if(s=="PUBLISHING STATUS") return "ARGITARAPEN EGOERA";
  if(s=="TERMS") return "TERMINOAK";
  if(s=="DOMAINS") return "DOMEINUAK";
  if(s=="term") return "terminoa";
  if(s=="clarification") return "argibide";
  if(s=="acceptability") return "onargarritasuna";
  if(s=="source") return "jatorria";
  if(s=="inflected form") return "inflexionatutako forma";
  if(s=="annotation") return "oharrak";
  if(s=="domain") return "domeinua";
  if(s=="part of speech") return "kategoria gramatikala";
  if(s=="inflection") return "inflexioa";
  if(s=="language of origin") return "jatorrizko hizkuntza";
  if(s=="symbol") return "sinboloa";
  if(s=="trademark") return "marka";
  if(s=="registered trademark") return "marka erregistratua";
  if(s=="proper noun") return "izen propioa";
  if(s=="formatting") return "formateatzea";
  if(s=="italic") return "etzana";
  if(s=="Created") return "Sortua";
  if(s=="Changed") return "Aldatua";
  if(s=="Deleted") return "Ezabatua";
  if(s=="Bulk-deleted") return "Multzoka ezabatua";
  if(s=="while uploading") return "igo bitartean";
  if(s=="By") return "#NAME?";
  if(s=="When") return "Noiz";
  if(s=="any checking status") return "edozein egiaztapen-egoera";
  if(s=="any publishing status") return "edozein argitalpen egoera";
  if(s=="any language") return "edozein hizkuntza";
  if(s=="any acceptability or no acceptability") return "edozein onargarritasun edo onargarritasunik ez";
  if(s=="any acceptability") return "edozein onargarritasun";
  if(s=="no acceptability") return "onargarritasunik ez";
  if(s=="any domain or no domain") return "edozein domeinu edo domeinurik ez";
  if(s=="any domain") return "edozein domeinu";
  if(s=="no domain") return "domeinurik ez";
  if(s=="LAST MAJOR UPDATE") return "AZKEN EGUNERAZIO NAGUSIA";
  if(s=="set to today") return "gaurko ezarri";
  if(s=="Invalid e-mail address or password.") return "Helbide elektroniko edo pasahitz baliogabea.";
  if(s=="INTR") return "INTR";
  if(s=="COLL") return "COLL";
  if(s=="INTROS") return "SARRERAK";
  if(s=="DEFINITIONS") return "DEFINIZIOAK";
  if(s=="EXAMPLES") return "ADIBIDEAK";
  if(s=="COLLECTIONS") return "BILDUMAK";
  if(s=="definition") return "definizioa";
  if(s=="example") return "adibidea";
  if(s=="sentence") return "esaldia";
  if(s=="collection") return "bilduma";
  if(s=="any collection or no collection") return "edozein bilduma edo bildumarik ez";
  if(s=="any collection") return "edozein bilduma";
  if(s=="no collection") return "bildumarik ez";
  if(s=="comments") return "iruzkinak";
  if(s=="with or without comments") return "iruzkinekin edo gabe";
  if(s=="with comments") return "iruzkinekin";
  if(s=="without comments") return "iruzkinik gabe";
  if(s=="my comments") return "nire iruzkinak";
  if(s=="with or without my comments") return "nire iruzkinekin edo gabe";
  if(s=="with my comments") return "nire iruzkinekin";
  if(s=="without my comments") return "nire iruzkinik gabe";
  if(s=="other people's comments") return "besteen iruzkinak";
  if(s=="with or without other people's comments") return "besteen iruzkinekin edo gabe";
  if(s=="with other people's comments") return "besteen iruzkinekin";
  if(s=="without other people's comments") return "besteen iruzkinik gabe";
  if(s=="EXTRANET") return "EXTRANET";
  if(s=="EXT") return "EXT";
  if(s=="EXTRANETS") return "EXTRANETAK";
  if(s=="extranet") return "extranet";
  if(s=="any extranet or no extranet") return "edozein extranet edo extranetik ez";
  if(s=="any extranet") return "edozein extranet";
  if(s=="no extranet") return "extranetik ez";
  if(s=="sorting language") return "sailkapen-hizkuntza";
  if(s=="Create mutual cross-references") return "Elkarrekiko erreferentzia gurutzatuak sortu";
  if(s=="Remove mutual cross-references") return "Elkarrekiko erreferentzia gurutzatuak ezabatu";
  if(s=="Merge into a single entry") return "Sarrera bakarrean bateratu";
  if(s=="SEE ALSO") return "IKUS GAINERA";
  if(s=="add to worklist") return "gehitu lan zerrendara";
  if(s=="Domains") return "Domeinuak";
  if(s=="Part-of-speech labels") return "Kategoria gramatikalen etiketak";
  if(s=="Inflection labels") return "Inflexioen etiketak";
  if(s=="Acceptability labels") return "Onargarritasun etiketak";
  if(s=="Sources") return "Iturriak";
  if(s=="Collections") return "Bildumak";
  if(s=="Tags") return "Etiketak";
  if(s=="Extranets") return "Extranetak";
  if(s=="Name and blurb") return "Izena eta iragarkia";
  if(s=="Features") return "Ezaugarriak";
  if(s=="Languages") return "Hizkuntzak";
  if(s=="Publishing") return "Argitalpena";
  if(s=="Change the termbase's URL") return "Termino-basearen URL aldatu";
  if(s=="Delete the termbase") return "Termino-basea ezabatu";
  if(s=="TITLE") return "IZENBURUA";
  if(s=="abbreviation") return "laburdura";
  if(s=="LANGUAGES") return "HIZKUNTZAK";
  if(s=="select all") return "guztia hautatu";
  if(s=="unselect all") return "desautatu guztia";
  if(s=="PRIORITY") return "LEHENTASUNA";
  if(s=="high") return "handia";
  if(s=="medium") return "ertaina";
  if(s=="low") return "txikia";
  if(s=="USERS") return "ERABILTZAILEAK";
  if(s=="e-mail address") return "helbide elektronikoa";
  if(s=="user") return "erabiltzailea";
  if(s=="Alphabetical order") return "Sailkapen alfabetikoa";
  if(s=="Similar terms (click to insert)") return "Antzeko terminoak (egin klik txertatzeko)";
  if(s=="Other entries that share this term") return "Termino hau partekatzen duten beste sarrera batzuk";
  if(s=="stop sharing") return "partekatzeari utzi";
  if(s=="Change checking status to") return "Aldatu egiaztatze-egoera honetara:";
  if(s=="Change publishing status to") return "Aldatu argitalpen-egoera honetara:";
  if(s=="Add to extranet") return "Extranetera gehitu";
  if(s=="Remove from extranet") return "Extranetetik ezabatu";
  if(s=="checked") return "egiaztatuta";
  if(s=="not checked") return "egiaztatu gabe";
  if(s=="publishable") return "argitaragarria";
  if(s=="hidden") return "ezkutua";
  if(s=="CHECKED") return "EGIAZTATUTA";
  if(s=="NOT CHECKED") return "EGIAZTATU GABE";
  if(s=="PUBLISHABLE") return "ARGITARAGARRIA";
  if(s=="HIDDEN") return "EZKUTUA";
  if(s=="non-essential") return "ez-funtsezkoa";
  if(s=="STATUS") return "EGOERA";
  if(s=="live") return "zuzenean";
  if(s=="not live") return "ez zuzenean";
  if(s=="any clarification or no clarification") return "edozein argibide edo argibiderik gabe";
  if(s=="any clarification") return "edozein argibide";
  if(s=="no clarification") return "argibiderik gabe";
  if(s=="clarification containing...") return "… jasotzen duen argibidea";
  if(s=="any intro or no intro") return "edozein sarrera edo sarrera gabe";
  if(s=="any intro") return "edozein sarrera";
  if(s=="no intro") return "sarrera gabe";
  if(s=="intro containing...") return "… eduki duen sarrera";
  if(s=="any definition or no definition") return "edozein definizio edo definizio barik";
  if(s=="any definition") return "edozen definizio";
  if(s=="no definition") return "ez dago definiziorik";
  if(s=="definition containing...") return "… eduki duen definizioa";
  if(s=="any example or no example") return "edozein adibide edo adibiderik gabe";
  if(s=="any example") return "edozein adibide";
  if(s=="no example") return "ez dago adibiderik";
  if(s=="example containing...") return "… eduki duen adibidea";
  if(s=="Automatic changes") return "Aldaketa automatikoak";
  if(s=="NAME") return "IZENA";
  if(s=="BLURB") return "SINOPSI";
  if(s=="level") return "maila";
  if(s=="reader") return "irakurlea";
  if(s=="editor") return "editorea";
  if(s=="creator") return "sortzailea";
  if(s=="administrator") return "administratzailea";
  if(s=="configurator") return "konfiguratzailea";
  if(s=="no change") return "ez dago aldaketarik";
  if(s=="change to 'not checked'") return "aldatu 'ez egiaztatu'-ra";
  if(s=="change to 'hidden'") return "aldatu 'ezkutuko'-ra";
  if(s=="change to 'not checked' and 'hidden'") return "aldatu 'ez egiaztatua' eta 'ezkutatuta'-ra";
  if(s=="LAST SEEN") return "AZKENEKOZ IKUSIA";
  if(s=="NEVER") return "INOIZ";
  if(s=="No termbases") return "Ez daude termino-baserik";
  if(s=="language") return "hizkuntza";
  if(s=="major") return "ikasgai nagusi";
  if(s=="minor") return "espezialitate";
  if(s=="role") return "rola";
  if(s=="title") return "izenburua";
  if(s=="ACCESS LEVEL") return "SARBIDE MAILA";
  if(s=="LICENCE") return "BAIMENA";
  if(s=="private") return "pribatua";
  if(s=="public") return "publikoa";
  if(s=="trigger_dateStampChange") return "data-zigilua aldatu da";
  if(s=="trigger_domainAdd") return "domeinua gehitu da";
  if(s=="trigger_domainRemove") return "domeinua kendu da";
  if(s=="trigger_domainReorder") return "domeinuak berrantolatu dira";
  if(s=="trigger_domainChange") return "domeinua aldatu da";
  if(s=="trigger_desigAdd") return "terminoa gehitu da";
  if(s=="trigger_desigRemove") return "terminoa kendu da";
  if(s=="trigger_desigReorder") return "terminoak berrantolatu dira";
  if(s=="trigger_desigClarifChange") return "argibidea aldatu da";
  if(s=="trigger_desigAcceptChange") return "onargarritasuna aldatu da";
  if(s=="trigger_termLangChange") return "terminoaren hizkuntza aldatu da";
  if(s=="trigger_termWordingChange") return "terminoa adierazteko modua aldatu da";
  if(s=="trigger_termInflectAdd") return "inflexio forma gehitu da";
  if(s=="trigger_termInflectRemove") return "inflexio forma kendu da";
  if(s=="trigger_termInflectReorder") return "inflexio formak berrantolatu dira";
  if(s=="trigger_termInflectLabelChange") return "inflexio formaren etiketa aldatu da";
  if(s=="trigger_termInflectTextChange") return "inflexio forma adierazteko modua aldatu da";
  if(s=="trigger_termAnnotAdd") return "terminoaren oharra gehitu da";
  if(s=="trigger_termAnnotRemove") return "terminoaren oharra kendu da";
  if(s=="trigger_termAnnotReorder") return "terminoen oharpenak berrantolatu dira";
  if(s=="trigger_termAnnotPositionChange") return "terminoaren oharpenaren posizioa aldatu da";
  if(s=="trigger_termAnnotLabelChange") return "terminoaren oharpen etiketa aldatu da";
  if(s=="trigger_introChange") return "sarrera aldatu da";
  if(s=="trigger_definitionAdd") return "definizioa gehitu da";
  if(s=="trigger_definitionRemove") return "definizioa kendu da";
  if(s=="trigger_definitionReorder") return "definizioak berrantolatu dira";
  if(s=="trigger_definitionTextChange") return "definizioaren textua aldatu da";
  if(s=="trigger_exampleAdd") return "adibidea gehitu da";
  if(s=="trigger_exampleRemove") return "adibidea kendu da";
  if(s=="trigger_exampleReorder") return "adibideak berrantolatu dira";
  if(s=="trigger_exampleTextAdd") return "esaldi adibidea gehitu da";
  if(s=="trigger_exampleTextRemove") return "adibideko esaldia kendu da";
  if(s=="trigger_exampleTextReorder") return "adibideko esaldiak berrantolatu dira";
  if(s=="trigger_exampleTextChange") return "adibideko esaldiaren adierazteko modua aldatu da";
  if(s=="trigger_collectionAdd") return "bilduma gehitu da";
  if(s=="trigger_collectionRemove") return "bilduma kendu da";
  if(s=="trigger_collectionReorder") return "bilduma berrantolatu da";
  if(s=="trigger_collectionChange") return "bilduma aldatu da";
  if(s=="trigger_extranetAdd") return "extraneta gehitu da";
  if(s=="trigger_extranetRemove") return "extraneta kendu da";
  if(s=="trigger_extranetReorder") return "extraneta berrantolatu da";
  if(s=="trigger_extranetChange") return "extraneta aldatu da";
  if(s=="trigger_sourceAdd") return "iturria gehitu da";
  if(s=="trigger_sourceRemove") return "iturria kendu da";
  if(s=="trigger_sourceReorder") return "iturria berrantolatu da";
  if(s=="trigger_sourceChange") return "iturria aldatu da";
  if(s=="trigger_nonessentialChange") return "ez-funtsezkotasuna aldatu da";
  if(s=="(blank)") return "(hutsik)";
  if(s=="Simple Multilingual Termbase") return "Termino-base Eleaniztun Sinplea";
  if(s=="Simple Bilingual Termbase") return "Termino-base Elebidun Sinplea";
  if(s=="Simple Monolingual Termbase") return "Termino-base Elebakar Sinplea";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Idatzi gizakiek irakur daitekeen izenburu bat, adibidez, \"Nire kirol terminoen hiztegia\". Geroago aldatzeko aukera izango duzu.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Hau izango da zure termino-basearen helbidea webean. Geroago aldatzeko aukera izango duzu.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "Hemen txantiloi bat hauta dezakezu hasteko. Txantiloi bakoitza lagin-sarrera batzuekin dator. Horiek aldatu edo ezabatu eta txantiloia pertsonalizatzeko aukera izango duzu.";
  if(s=="Your termbase is ready.") return "Zure termino-basea prest dago.";
  if(s=="TERM OF THE DAY") return "EGUNEKO TERMINOA";
  if(s=="set to next available date") return "eskuragarri dagoen hurrengo data ezarri";
  if(s=="Display from") return "Bistaratu hemendik";
  if(s=="Display until") return "Erakutsi ... arte";
  if(s=="News and announcements") return "Albisteak eta iragarkiak";
  if(s=="Create your account") return "Zure kontua sortu";
  if(s=="Reset your password") return "Berrezarri pasahitza";
  if(s=="Terminologue signup") return "Terminologuen izena ematea";
  if(s=="Please follow the link below to create your Terminologue account:") return "Mesedez, jarraitu beheko esteka zure Terminologue kontua sortzeko:";
  if(s=="Terminologue password reset") return "Terminologue pasahitza berrezarri";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Mesedez, jarraitu beheko esteka zure Terminologue pasahitza berrezartzeko:";
  if(s=="This page is only available in English.") return "Orrialde hau ingelesez bakarrik dago eskuragarri.";
  if(s=="DRAFTING STATUS") return "ERREDAKZIO EGOERA";
  if(s=="draft entry") return "zirriborro sarrera";
  if(s=="finished entry") return "sarrera amaitua";
  if(s=="DRAFT") return "ZIRRIBORROA";
  if(s=="FINISHED") return "AMAITUA";
  if(s=="any drafting status") return "edozein zirriborro egoera";
  if(s=="Prefabricated comments") return "Aurrefabrikatutako iruzkinak";
  if(s=="NOTES") return "OHARRAK";
  if(s=="note") return "oharra";
  if(s=="NOT") return "NOT";
  if(s=="with or without notes") return "ohar batekin edo ohar barik";
  if(s=="with a note") return "ohar batekin";
  if(s=="with a note containing...") return "honela jasotzen duen ohar batekin...";
  if(s=="without notes") return "oharrik gabe";
  if(s=="any type") return "edozein motatakoa";
  if(s=="private note, not shown on extranets") return "ohar pribatua, ez da extranetetan agertzen";
  if(s=="private note, shown on extranets") return "ohar pribatua, extranetetan ikusgai";
  if(s=="public note") return "ohar publikoa";
  if(s=="Note types") return "Ohar motak";
  if(s=="LEVEL") return "MAILA";
  if(s=="with a comment") return "iruzkin batekin";
  if(s=="with a comment containing...") return "… ezagutarazten duen iruzkin batekin";
  if(s=="TBX export") return "TBX esportazioa";
  if(s=="TBX import") return "TBX inportazioa";
  if(s=="Empty the termbase") return "Termino-basea hustu";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "Kontuz! Termino-oinarri hau ezabatzera zoaz. Ezin izango duzu hau desegin.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "Kontuz! Sarrera guztiak eta haien historia ezabatzera zoaz. Ezin izango duzu hau desegin.";
  if(s=="RELATED TERMS") return "ERLAZIONATUTAKO TERMINOAK";
  if(s=="Your termbase at a glance") return "Zure termino-basea begirada batean";
  if(s=="Number of entries") return "Sarrera kopurua";
  if(s=="Number of items in history log") return "Historiako erregistroko elementu kopurua";
  if(s=="Your termbase is stored in the file %F") return "Zure termino-basea %F fitxategian gordeta dago";
  if(s=="File size") return "Fitxategiaren tamaina";
  if(s=="Download %F") return "Deskargatu %F";
  if(s=="Upload %F") return "Igo %F";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Ziurtatu kargatzen ari zaren fitxategia baliozko Terminologue termino-base bat dela. Beste zerbait kargatzen baduzu, kalte konponezina egingo diozu zure termino-baseari.";
  if(s=="PARENT") return "GURASOAK";
  if(s=="no parent") return "gurasorik ez";
  if(s=="excluding subdomains") return "azpidomeinuak kenduta";
  if(s=="including subdomains") return "azpidomeinuak barne";
  if(s=="the entry has this domain") return "sarrerak domeinu hau dauka";
  if(s=="the entry has only this domain") return "sarrerak domeinu hau baino ez dauka";
  if(s=="the entry has not only this domain") return "sarrerak ez du domeinu hori bakarrik";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "Kontuz! Zeure burua termino-base honetatik kentzen baduzu, sarbidea galduko duzu.";
  if(s=="Leave this termbase") return "Termino-base hau utzi";
  if(s=="IMG") return "IMG";
  if(s=="IMAGES") return "IRUDIAK";
  if(s=="image") return "irudia";
  if(s=="credits") return "kredituak";
  if(s=="link to source") return "iturrira esteka";
  if(s=="The file is too large. The maximum allowed size is $1 bytes.") return "Fitxategia handiegia da. Onartutako gehienezko tamaina $1 byte da.";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
