function L(s, gloss){
  if(s=="only") return function(s){
    return s+" seulement";
  };
  if(s=="READ-ONLY") return "En lecture seule";
  if(s=="Editing") return "Édition";
  if(s=="Dublin City University") return "Dublin City University";
  if(s=="Log out") return "Se déconnecter";
  if(s=="Change your password") return "Modifier le mot de passe";
  if(s=="Registered user login") return "Connexion à un compte existant";
  if(s=="Get an account") return "Créer un compte";
  if(s=="Forgot your password?") return "Mot de passe oublié?";
  if(s=="E-mail address") return "Adresse courriel";
  if(s=="Password") return "Mot de passe";
  if(s=="Log in") return "Se connecter";
  if(s=="Your termbases") return "Vos bases terminologiques";
  if(s=="You have no termbases yet.") return "Vous n’avez aucune base terminologique.";
  if(s=="Create a termbase") return "Créer une base terminologique";
  if(s=="Administration") return "Administration";
  if(s=="Users") return "Utilisateurs";
  if(s=="Termbases") return "Bases terminologiques";
  if(s=="smart search") return "recherche intelligente";
  if(s=="complete term") return "terme complet";
  if(s=="start of term") return "début du terme";
  if(s=="end of term") return "fin du terme";
  if(s=="any part of term") return "n’importe quelle partie du terme";
  if(s=="any part except start or end") return "n’importe quelle partie du terme sauf le début ou la fin";
  if(s=="search in all languages") return "rechercher dans toutes les langues";
  if(s=="Configuration") return "Configuration";
  if(s=="ADMIN") return "ADMIN";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "DÉF";
  if(s=="XMPL") return "XMPL";
  if(s=="CHECKING STATUS") return "ÉTAT DE RÉVISION";
  if(s=="PUBLISHING STATUS") return "ÉTAT DE PUBLICATION";
  if(s=="TERMS") return "TERMES";
  if(s=="DOMAINS") return "DOMAINES";
  if(s=="term") return "terme";
  if(s=="clarification") return "précision";
  if(s=="acceptability") return "marque d'usage";
  if(s=="source") return "source";
  if(s=="inflected form") return "forme fléchie";
  if(s=="annotation") return "annotation";
  if(s=="domain") return "domaine";
  if(s=="part of speech") return "catégorie grammaticale";
  if(s=="inflection") return "flexion";
  if(s=="language of origin") return "langue d’origine";
  if(s=="symbol") return "symbole";
  if(s=="trademark") return "marque de commerce";
  if(s=="registered trademark") return "marque déposée";
  if(s=="proper noun") return "nom propre";
  if(s=="formatting") return "mise en forme";
  if(s=="italic") return "italique";
  if(s=="Created") return "Créée";
  if(s=="Changed") return "Modifiée";
  if(s=="Deleted") return "Supprimée";
  if(s=="Bulk-deleted") return "Supprimées en bloc";
  if(s=="while uploading") return "pendant le téléversement";
  if(s=="By") return "Par ";
  if(s=="When") return "Quand ";
  if(s=="any checking status") return "tout état de révision";
  if(s=="any publishing status") return "tout état de publication";
  if(s=="any language") return "toute langue";
  if(s=="any acceptability or no acceptability") return "avec ou sans marques d’usage";
  if(s=="any acceptability") return "avec marques d’usage";
  if(s=="no acceptability") return "sans marques d’usage";
  if(s=="any domain or no domain") return "avec ou sans domaines";
  if(s=="any domain") return "avec domaines";
  if(s=="no domain") return "sans domaines";
  if(s=="LAST MAJOR UPDATE") return "DERNIÈRE MISE À JOUR MAJEURE";
  if(s=="set to today") return "fixer à la date d’aujourd’hui";
  if(s=="Invalid e-mail address or password.") return "Adresse courriel ou mot de passe incorrects.";
  if(s=="INTR") return "INTR";
  if(s=="COLL") return "COLL";
  if(s=="INTROS") return "INTRODUCTIONS";
  if(s=="DEFINITIONS") return "DÉFINITIONS";
  if(s=="EXAMPLES") return "EXEMPLES";
  if(s=="COLLECTIONS") return "COLLECTIONS";
  if(s=="definition") return "définition";
  if(s=="example") return "exemple";
  if(s=="sentence") return "phrase";
  if(s=="collection") return "collection";
  if(s=="any collection or no collection") return "fait partie ou non d’une collection";
  if(s=="any collection") return "fait partie d’une collection";
  if(s=="no collection") return "ne fait partie d’aucune collection";
  if(s=="comments") return "commentaires";
  if(s=="with or without comments") return "avec ou sans commentaires";
  if(s=="with comments") return "avec commentaires";
  if(s=="without comments") return "sans commentaires";
  if(s=="my comments") return "mes commentaires";
  if(s=="with or without my comments") return "avec mes commentaires ou non";
  if(s=="with my comments") return "avec mes commentaires";
  if(s=="without my comments") return "sans mes commentaires";
  if(s=="other people's comments") return "commentaires d’autres personnes";
  if(s=="with or without other people's comments") return "avec ou sans les commentaires d'autres personnes";
  if(s=="with other people's comments") return "avec les commentaires d'autres personnes";
  if(s=="without other people's comments") return "sans les commentaires d'autres personnes";
  if(s=="EXTRANET") return "EXTRANET";
  if(s=="EXT") return "EXT";
  if(s=="EXTRANETS") return "EXTRANETS";
  if(s=="extranet") return "extranet";
  if(s=="any extranet or no extranet") return "diffusée ou non dans un extranet";
  if(s=="any extranet") return "diffusée dans un extranet, peu importe lequel";
  if(s=="no extranet") return "diffusée dans aucun extranet";
  if(s=="sorting language") return "langue prioritaire ";
  if(s=="Create mutual cross-references") return "Ajouter des renvois mutuels sur toutes les fiches de la liste";
  if(s=="Remove mutual cross-references") return "Supprimer les renvois mutuels";
  if(s=="Merge into a single entry") return "Fusionner les fiches de la liste";
  if(s=="SEE ALSO") return "VOIR AUSSI";
  if(s=="add to worklist") return "ajouter à la liste de travail";
  if(s=="Domains") return "Domaines";
  if(s=="Part-of-speech labels") return "Marques grammaticales";
  if(s=="Inflection labels") return "Marques de flexion";
  if(s=="Acceptability labels") return "Marques d’usage";
  if(s=="Sources") return "Sources";
  if(s=="Collections") return "Collections";
  if(s=="Tags") return "Balises";
  if(s=="Extranets") return "Extranets";
  if(s=="Name and blurb") return "Nom de la base terminologique et texte de présentation";
  if(s=="Features") return "Fonctionnalités";
  if(s=="Languages") return "Langues";
  if(s=="Publishing") return "Publication";
  if(s=="Change the termbase's URL") return "Modifier l’adresse URL de la base";
  if(s=="Delete the termbase") return "Supprimer la base";
  if(s=="TITLE") return "TITRE";
  if(s=="abbreviation") return "abréviation";
  if(s=="LANGUAGES") return "LANGUES";
  if(s=="select all") return "tout sélectionner";
  if(s=="unselect all") return "tout désélectionner";
  if(s=="PRIORITY") return "PRIORITÉ";
  if(s=="high") return "élevée";
  if(s=="medium") return "moyenne";
  if(s=="low") return "faible";
  if(s=="USERS") return "UTILISATEURS";
  if(s=="e-mail address") return "adresse courriel";
  if(s=="user") return "utilisateur";
  if(s=="Alphabetical order") return "Ordre alphabétique";
  if(s=="Similar terms (click to insert)") return "Termes similaires (cliquer pour activer le partage entre fiches)";
  if(s=="Other entries that share this term") return "Autres fiches qui partagent ce terme";
  if(s=="stop sharing") return "arrêter le partage";
  if(s=="Change checking status to") return "Faire passer l’état de révision à";
  if(s=="Change publishing status to") return "Faire passer l’état de publication à";
  if(s=="Add to extranet") return "Ajouter à l’extranet";
  if(s=="Remove from extranet") return "Retirer de l’extranet";
  if(s=="checked") return "révisée";
  if(s=="not checked") return "non révisée";
  if(s=="publishable") return "publiable";
  if(s=="hidden") return "cachée";
  if(s=="CHECKED") return "RÉVISÉE";
  if(s=="NOT CHECKED") return "NON RÉVISÉE";
  if(s=="PUBLISHABLE") return "PUBLIABLE";
  if(s=="HIDDEN") return "CACHÉE";
  if(s=="non-essential") return "non essentiel";
  if(s=="STATUS") return "ÉTAT";
  if(s=="live") return "activé";
  if(s=="not live") return "désactivé";
  if(s=="any clarification or no clarification") return "avec ou sans précisions";
  if(s=="any clarification") return "avec précisions";
  if(s=="no clarification") return "sans précisions";
  if(s=="clarification containing...") return "avec une précision qui contient…";
  if(s=="any intro or no intro") return "avec ou sans introduction";
  if(s=="any intro") return "avec introduction";
  if(s=="no intro") return "sans introduction";
  if(s=="intro containing...") return "avec une introduction qui contient…";
  if(s=="any definition or no definition") return "avec ou sans définition";
  if(s=="any definition") return "avec définition";
  if(s=="no definition") return "sans définition";
  if(s=="definition containing...") return "avec une définition qui contient…";
  if(s=="any example or no example") return "avec ou sans exemples";
  if(s=="any example") return "avec exemples";
  if(s=="no example") return "sans exemples";
  if(s=="example containing...") return "avec un exemple qui contient…";
  if(s=="Automatic changes") return "Changements automatiques";
  if(s=="NAME") return "NOM DE LA BASE TERMINOLOGIQUE";
  if(s=="BLURB") return "TEXTE DE PRÉSENTATION";
  if(s=="level") return "niveau d’accès";
  if(s=="reader") return "lecteur";
  if(s=="editor") return "collaborateur";
  if(s=="creator") return "auteur";
  if(s=="administrator") return "administrateur";
  if(s=="configurator") return "configurateur";
  if(s=="no change") return "aucun changement";
  if(s=="change to 'not checked'") return "faire passer la fiche à « non révisée »";
  if(s=="change to 'hidden'") return "faire passer la fiche à « cachée »";
  if(s=="change to 'not checked' and 'hidden'") return "faire passer la fiche à « non révisée » et à « cachée »";
  if(s=="LAST SEEN") return "DERNIER AFFICHAGE";
  if(s=="NEVER") return "JAMAIS";
  if(s=="No termbases") return "Aucune base terminologique";
  if(s=="language") return "langue";
  if(s=="major") return "primaire";
  if(s=="minor") return "secondaire";
  if(s=="role") return "rôle";
  if(s=="title") return "nom de la langue";
  if(s=="ACCESS LEVEL") return "STATUT DE DIFFUSION DE LA BASE TERMINOLOGIQUE";
  if(s=="LICENCE") return "LICENCE";
  if(s=="private") return "privée";
  if(s=="public") return "publique";
  if(s=="trigger_dateStampChange") return "modification de la date";
  if(s=="trigger_domainAdd") return "ajout d’un domaine";
  if(s=="trigger_domainRemove") return "suppression d’un domaine";
  if(s=="trigger_domainReorder") return "modification de l’ordre des domaines";
  if(s=="trigger_domainChange") return "modification d’un domaine";
  if(s=="trigger_desigAdd") return "ajout d’un terme";
  if(s=="trigger_desigRemove") return "suppression d’un terme";
  if(s=="trigger_desigReorder") return "modification de l’ordre des termes";
  if(s=="trigger_desigClarifChange") return "modification d’une précision";
  if(s=="trigger_desigAcceptChange") return "modification d’une marque d’usage";
  if(s=="trigger_termLangChange") return "modification de la langue associée à un terme";
  if(s=="trigger_termWordingChange") return "modification de la formulation d'un terme";
  if(s=="trigger_termInflectAdd") return "ajout d’une forme fléchie";
  if(s=="trigger_termInflectRemove") return "suppression d’une forme fléchie";
  if(s=="trigger_termInflectReorder") return "modification de l’ordre des formes fléchies";
  if(s=="trigger_termInflectLabelChange") return "modification de la marque associée à une forme fléchie";
  if(s=="trigger_termInflectTextChange") return "modification de la formulation d'une forme fléchie";
  if(s=="trigger_termAnnotAdd") return "ajout d’une annotation à un terme";
  if(s=="trigger_termAnnotRemove") return "suppression d’une annotation associée à un terme";
  if(s=="trigger_termAnnotReorder") return "modification de l’ordre des annotations associées à un terme";
  if(s=="trigger_termAnnotPositionChange") return "modification de la partie du terme à laquelle une annotation s’applique";
  if(s=="trigger_termAnnotLabelChange") return "modification de l’étiquette associée à une annotation";
  if(s=="trigger_introChange") return "modification d’une introduction";
  if(s=="trigger_definitionAdd") return "ajout d’une définition";
  if(s=="trigger_definitionRemove") return "suppression d’une définition";
  if(s=="trigger_definitionReorder") return "modification de l’ordre des définitions";
  if(s=="trigger_definitionTextChange") return "modification du texte d’une définition";
  if(s=="trigger_exampleAdd") return "ajout d’un exemple";
  if(s=="trigger_exampleRemove") return "suppression d’un exemple";
  if(s=="trigger_exampleReorder") return "modification de l’ordre des exemples";
  if(s=="trigger_exampleTextAdd") return "ajout d’une phrase dans un exemple";
  if(s=="trigger_exampleTextRemove") return "suppression d’une phrase dans un exemple";
  if(s=="trigger_exampleTextReorder") return "modification de l’ordre des phrases dans un exemple";
  if(s=="trigger_exampleTextChange") return "modification d’une phrase existante dans un exemple";
  if(s=="trigger_collectionAdd") return "ajout d’une collection";
  if(s=="trigger_collectionRemove") return "suppression d’une collection";
  if(s=="trigger_collectionReorder") return "modification de l’ordre des collections";
  if(s=="trigger_collectionChange") return "modification d'une collection";
  if(s=="trigger_extranetAdd") return "ajout d’un extranet";
  if(s=="trigger_extranetRemove") return "suppression d’un extranet";
  if(s=="trigger_extranetReorder") return "modification de l’ordre des extranets";
  if(s=="trigger_extranetChange") return "modification d'un extranet";
  if(s=="trigger_sourceAdd") return "ajout d’une source";
  if(s=="trigger_sourceRemove") return "suppression d’une source";
  if(s=="trigger_sourceReorder") return "modification de l’ordre des sources";
  if(s=="trigger_sourceChange") return "modification d'une source";
  if(s=="trigger_nonessentialChange") return "modification du statut de non-essentialité";
  if(s=="(blank)") return "(aucun modèle)";
  if(s=="Simple Multilingual Termbase") return "Base terminologique multilingue simple";
  if(s=="Simple Bilingual Termbase") return "Base terminologique bilingue simple";
  if(s=="Simple Monolingual Termbase") return "Base terminologique unilingue simple";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Entrez un nom que les autres utilisateurs seront capables de lire et de comprendre, par exemple « Mon dictionnaire des sports ». Vous pourrez modifier ce nom plus tard.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Si vous décidez de rendre votre base terminologique accessible au public, elle sera disponible sur le Web à l’adresse URL choisie. Vous pourrez modifier cette adresse plus tard.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "Pour vous aider, nous vous proposons quelques modèles de bases terminologiques. Chaque modèle contient quelques exemples de fiches. Vous pourrez modifier ou supprimer ces fiches et personnaliser la base selon vos besoins.";
  if(s=="Your termbase is ready.") return "Votre base terminologique est prête.";
  if(s=="TERM OF THE DAY") return "FICHE DU JOUR";
  if(s=="set to next available date") return "fixer à la prochaine date disponible";
  if(s=="Display from") return "Afficher à compter de";
  if(s=="Display until") return "Afficher jusqu’à";
  if(s=="News and announcements") return "Nouvelles et annonces";
  if(s=="Create your account") return "Créer un compte";
  if(s=="Reset your password") return "Réinitialiser le mot de passe";
  if(s=="Terminologue signup") return "Création de votre compte Terminologue";
  if(s=="Please follow the link below to create your Terminologue account:") return "Pour créer votre compte Terminologue, cliquez sur le lien ci-dessous :";
  if(s=="Terminologue password reset") return "Réinitialisation du mot de passe de votre compte Terminologue";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Pour réinitialiser le mot de passe de votre compte Terminologue, cliquez sur le lien ci-dessous :";
  if(s=="This page is only available in English.") return "Cette page ne peut être affichée qu’en anglais.";
  if(s=="DRAFTING STATUS") return "ÉTAT D’ACHÈVEMENT";
  if(s=="draft entry") return "fiche brouillon";
  if(s=="finished entry") return "fiche terminée";
  if(s=="DRAFT") return "BROUILLON";
  if(s=="FINISHED") return "TERMINÉE";
  if(s=="any drafting status") return "quel que soit l’état d’achèvement";
  if(s=="Prefabricated comments") return "Commentaires prêts à l’emploi";
  if(s=="NOTES") return "NOTES";
  if(s=="note") return "note";
  if(s=="NOT") return "NOTE";
  if(s=="with or without notes") return "avec ou sans notes";
  if(s=="with a note") return "avec notes";
  if(s=="with a note containing...") return "avec une note qui contient…";
  if(s=="without notes") return "sans notes";
  if(s=="any type") return "tout type";
  if(s=="private note, not shown on extranets") return "note privée qui n’apparaît pas dans les extranets";
  if(s=="private note, shown on extranets") return "note privée qui apparaît dans les extranets";
  if(s=="public note") return "note publique";
  if(s=="Note types") return "Types de notes";
  if(s=="LEVEL") return "NIVEAU DE DIFFUSION";
  if(s=="with a comment") return "avec un commentaire";
  if(s=="with a comment containing...") return "avec un commentaire qui contient…";
  if(s=="TBX export") return "Exportation au format TBX";
  if(s=="TBX import") return "Importation au format TBX";
  if(s=="Empty the termbase") return "Supprimer toutes les fiches de la base terminologique";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "Attention! Vous êtes sur le point de supprimer cette base terminologique. Vous ne pourrez plus revenir en arrière après la suppression.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "Attention! Vous êtes sur le point de supprimer toutes les fiches de cette base terminologique de même que leur historique. Vous ne pourrez plus revenir en arrière après la suppression.";
  if(s=="RELATED TERMS") return "TERMES CONNEXES";
  if(s=="Your termbase at a glance") return "Votre base terminologique en bref";
  if(s=="Number of entries") return "Nombre de fiches terminologiques";
  if(s=="Number of items in history log") return "Nombre d’éléments enregistrés dans l’historique";
  if(s=="Your termbase is stored in the file %F") return "Votre base terminologique est enregistrée dans le fichier %F";
  if(s=="File size") return "Taille du fichier";
  if(s=="Download %F") return "Télécharger %F";
  if(s=="Upload %F") return "Téléverser %F";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Assurez-vous que le fichier à téléverser correspond bien à une base terminologique valide de Terminologue. Dans le cas contraire, vous causerez des dommages irréparables à votre base terminologique.";
  if(s=="PARENT") return "DOMAINE GÉNÉRIQUE";
  if(s=="no parent") return "pas de domaine générique";
  if(s=="excluding subdomains") return "sous-domaines exclus";
  if(s=="including subdomains") return "sous-domaines inclus";
  if(s=="the entry has this domain") return "la fiche est associée à ce domaine";
  if(s=="the entry has only this domain") return "la fiche est associée à ce domaine seulement";
  if(s=="the entry has not only this domain") return "la fiche est associée à d’autres domaines également";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "Attention! Si vous renoncez à cette base terminologique, vous n’y aurez plus accès.";
  if(s=="Leave this termbase") return "Renoncer à cette base terminologique";
  if(s=="IMG") return "IMG";
  if(s=="IMAGES") return "IMAGES";
  if(s=="image") return "image";
  if(s=="credits") return "source de l’image";
  if(s=="link to source") return "lien vers la source";
  if(s=="The file is too large. The maximum allowed size is $1 bytes.") return "Le fichier est trop volumineux. La taille maximale autorisée est de $1 octets.";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
