function L(s, gloss){
  if(s=="only") return function(s){
    return "tik "+s;
  };
  if(s=="READ-ONLY") return "NEKEIČIAMAS FAILAS";
  if(s=="Editing") return "Redagavimas";
  if(s=="Dublin City University") return "Dublino universitetas";
  if(s=="Log out") return "Atsijunkite";
  if(s=="Change your password") return "Pasikeiskite savo slaptažodį";
  if(s=="Registered user login") return "Registruoto vartotojo prisijungimas";
  if(s=="Get an account") return "Gaukite paskyrą";
  if(s=="Forgot your password?") return "Pamiršote slaptažodį?";
  if(s=="E-mail address") return "El. pašto adresas";
  if(s=="Password") return "Slaptažodis";
  if(s=="Log in") return "Prisijunkite";
  if(s=="Your termbases") return "Jūsų terminų bazės";
  if(s=="You have no termbases yet.") return "Jūs dar neturite terminų bazių.";
  if(s=="Create a termbase") return "Sukurkite terminų bazę";
  if(s=="Administration") return "Administravimas";
  if(s=="Users") return "Vartotojai";
  if(s=="Termbases") return "Terminų bazės";
  if(s=="smart search") return "išmani paieška";
  if(s=="complete term") return "visas terminas";
  if(s=="start of term") return "termino pradžia";
  if(s=="end of term") return "termino pabaiga";
  if(s=="any part of term") return "bet kuri termino dalis";
  if(s=="any part except start or end") return "bet kuri dalis, išskyrus pradžią ir pabaigą";
  if(s=="search in all languages") return "ieškoti visose kalbose";
  if(s=="Configuration") return "Konfigūravimas";
  if(s=="ADMIN") return "ADMIN";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "SRT";
  if(s=="DEF") return "API";
  if(s=="XMPL") return "PVZD";
  if(s=="CHECKING STATUS") return "TIKRINAMA BŪSENA";
  if(s=="PUBLISHING STATUS") return "SKELBIAMA BŪSENA";
  if(s=="TERMS") return "TERMINAI";
  if(s=="DOMAINS") return "SRITYS";
  if(s=="term") return "terminas";
  if(s=="clarification") return "paaiškinimas";
  if(s=="acceptability") return "priimtinumas";
  if(s=="source") return "šaltinis";
  if(s=="inflected form") return "kaitoma forma";
  if(s=="annotation") return "anotacija";
  if(s=="domain") return "sritis";
  if(s=="part of speech") return "kalbos dalis";
  if(s=="inflection") return "galūnė";
  if(s=="language of origin") return "kilmės kalba";
  if(s=="symbol") return "simbolis";
  if(s=="trademark") return "prekės ženklas";
  if(s=="registered trademark") return "registruotas prekės ženklas";
  if(s=="proper noun") return "tikrinis daiktavardis";
  if(s=="formatting") return "formatavimas";
  if(s=="italic") return "kursyvas";
  if(s=="Created") return "Sukurta";
  if(s=="Changed") return "Pakeista";
  if(s=="Deleted") return "Ištrinta";
  if(s=="Bulk-deleted") return "Masiškai ištrinta";
  if(s=="while uploading") return "kol įkeliama";
  if(s=="By") return "Iki";
  if(s=="When") return "Kada";
  if(s=="any checking status") return "bet kokia tikrinimo būsena";
  if(s=="any publishing status") return "bet kokia skelbimo būsena";
  if(s=="any language") return "bet kuri kalba";
  if(s=="any acceptability or no acceptability") return "bet koks prieinamumas arba neprieinamumas";
  if(s=="any acceptability") return "bet koks prieinamumas";
  if(s=="no acceptability") return "nėra prieinamumo";
  if(s=="any domain or no domain") return "bet kokia sritis arba nėra srities";
  if(s=="any domain") return "bet kokia sritis";
  if(s=="no domain") return "nėra srities";
  if(s=="LAST MAJOR UPDATE") return "PASKUTINIS PAGRINDINIS ATNAUJINIMAS";
  if(s=="set to today") return "nustatykite į šiandien";
  if(s=="Invalid e-mail address or password.") return "Klaidingas el. pašto adresas arba slaptažodis.";
  if(s=="INTR") return "ĮVD";
  if(s=="COLL") return "RINK";
  if(s=="INTROS") return "ĮVADAI";
  if(s=="DEFINITIONS") return "APIBRĖŽTYS";
  if(s=="EXAMPLES") return "PAVYZDŽIAI";
  if(s=="COLLECTIONS") return "RINKINIAI";
  if(s=="definition") return "apibrėžtis";
  if(s=="example") return "pavyzdys";
  if(s=="sentence") return "sakinys";
  if(s=="collection") return "rinkinys";
  if(s=="any collection or no collection") return "bet koks rinkinys arba nėra rinkinio";
  if(s=="any collection") return "bet koks rinkinys";
  if(s=="no collection") return "nėra rinkinio";
  if(s=="comments") return "komentarai";
  if(s=="with or without comments") return "su arba be komentarų";
  if(s=="with comments") return "su komentarais";
  if(s=="without comments") return "be komentarų";
  if(s=="my comments") return "mano komentarai";
  if(s=="with or without my comments") return "su arba be mano komentarų";
  if(s=="with my comments") return "su mano komentarais";
  if(s=="without my comments") return "be mano komentarų";
  if(s=="other people's comments") return "kitų žmonių komentarai";
  if(s=="with or without other people's comments") return "su arba be kitų žmonių komentarų";
  if(s=="with other people's comments") return "su kitų žmonių komentarais";
  if(s=="without other people's comments") return "be kitų žmonių komentarų";
  if(s=="EXTRANET") return "EKSTRANETAS";
  if(s=="EXT") return "EKS";
  if(s=="EXTRANETS") return "EKSTRANETAI";
  if(s=="extranet") return "ekstranetas";
  if(s=="any extranet or no extranet") return "bet koks ekstranetas arba nėra ekstraneto";
  if(s=="any extranet") return "bet koks ekstranetas";
  if(s=="no extranet") return "nėra ekstraneto";
  if(s=="sorting language") return "rūšiavimo kalba";
  if(s=="Create mutual cross-references") return "Sukurkite kryžmines nuorodas";
  if(s=="Remove mutual cross-references") return "Pašalinkite kryžmines nuorodas";
  if(s=="Merge into a single entry") return "Sujunkite į vieną įrašą";
  if(s=="SEE ALSO") return "TAIP PAT ŽIŪRĖKITE";
  if(s=="add to worklist") return "pridėkite prie darbinio sąrašo";
  if(s=="Domains") return "Sritys";
  if(s=="Part-of-speech labels") return "Kalbos dalių žymos";
  if(s=="Inflection labels") return "Galūnių žymos";
  if(s=="Acceptability labels") return "Prieinamumo žymos";
  if(s=="Sources") return "Šaltiniai";
  if(s=="Collections") return "Rinkiniai";
  if(s=="Tags") return "Žymos";
  if(s=="Extranets") return "Ekstranetai";
  if(s=="Name and blurb") return "Vardas ir anotacija";
  if(s=="Features") return "Požymiai";
  if(s=="Languages") return "Kalbos";
  if(s=="Publishing") return "Skelbiama";
  if(s=="Change the termbase's URL") return "Pakeiskite terminų bazės nuorodą";
  if(s=="Delete the termbase") return "Ištrinkite terminų bazę";
  if(s=="TITLE") return "PAVADINIMAS";
  if(s=="abbreviation") return "santrumpa";
  if(s=="LANGUAGES") return "KALBOS";
  if(s=="select all") return "pažymėkite viską";
  if(s=="unselect all") return "panaikinkite visą pažymėjimą";
  if(s=="PRIORITY") return "PRIORITETAS";
  if(s=="high") return "aukštas";
  if(s=="medium") return "vidutinis";
  if(s=="low") return "žemas";
  if(s=="USERS") return "VARTOTOJAI";
  if(s=="e-mail address") return "el. pašto adresas";
  if(s=="user") return "vartotojas";
  if(s=="Alphabetical order") return "Abėcėlinė tvarka";
  if(s=="Similar terms (click to insert)") return "Panašūs terminai (paspauskite, kad įterptumėte)";
  if(s=="Other entries that share this term") return "Kiti įrašai, kurie dalinasi šiuo terminu";
  if(s=="stop sharing") return "nesidalinkite";
  if(s=="Change checking status to") return "Pakeiskite tikrinimo būseną į";
  if(s=="Change publishing status to") return "Pakeiskite skelbimo būseną į";
  if(s=="Add to extranet") return "Pridėkite prie ekstraneto";
  if(s=="Remove from extranet") return "Pašalinkite iš ekstraneto";
  if(s=="checked") return "patikrinta";
  if(s=="not checked") return "nepatikrinta";
  if(s=="publishable") return "skelbtina";
  if(s=="hidden") return "paslėpta";
  if(s=="CHECKED") return "PATIKRINTA";
  if(s=="NOT CHECKED") return "NEPATIKRINTA";
  if(s=="PUBLISHABLE") return "SKELBTINA";
  if(s=="HIDDEN") return "PASLĖPTA";
  if(s=="non-essential") return "neesminis";
  if(s=="STATUS") return "BŪSENA";
  if(s=="live") return "tiesioginė transliacija";
  if(s=="not live") return "netiesioginė transliacija";
  if(s=="any clarification or no clarification") return "bet koks paaiškinimas arba nėra paaiškinimo";
  if(s=="any clarification") return "bet koks paaiškinimas";
  if(s=="no clarification") return "nėra paaiškinimo";
  if(s=="clarification containing...") return "turintys paaiškinimą...";
  if(s=="any intro or no intro") return "bet koks įvadas arba nėra įvado";
  if(s=="any intro") return "bet koks įvadas";
  if(s=="no intro") return "nėra įvado";
  if(s=="intro containing...") return "turintys įvadą...";
  if(s=="any definition or no definition") return "bet koks apibrėžimas arba be apibrėžimo";
  if(s=="any definition") return "bet koks apibrėžimas";
  if(s=="no definition") return "be apibrėžimo";
  if(s=="definition containing...") return "turintys apibrėžimą...";
  if(s=="any example or no example") return "bet koks pavyzdys arbe be pavyzdžių";
  if(s=="any example") return "bet koks pavyzdys";
  if(s=="no example") return "be pavyzdžių";
  if(s=="example containing...") return "pavyzdys, į kurį įeina...";
  if(s=="Automatic changes") return "Automatiniai pakeitimai";
  if(s=="NAME") return "PAVADINIMAS";
  if(s=="BLURB") return "ANOTACIJA";
  if(s=="level") return "lygis";
  if(s=="reader") return "skaitytojas";
  if(s=="editor") return "redaktorius";
  if(s=="creator") return "kūrėjas";
  if(s=="administrator") return "administratorius";
  if(s=="configurator") return "konfigūratorius";
  if(s=="no change") return "nėra pakeitimų";
  if(s=="change to 'not checked'") return "pakeiskite į 'nepažymėta'";
  if(s=="change to 'hidden'") return "pakeiskite į 'paslėpta'";
  if(s=="change to 'not checked' and 'hidden'") return "pakeiskite į 'nepažymėta' ir 'paslėpta'";
  if(s=="LAST SEEN") return "PASKUTINĮ KARTĄ MATYTAS";
  if(s=="NEVER") return "NIEKADA";
  if(s=="No termbases") return "Nėra terminų bazių";
  if(s=="language") return "kalba";
  if(s=="major") return "pagrindinis";
  if(s=="minor") return "nepagrindinis";
  if(s=="role") return "vaidmuo";
  if(s=="title") return "pavadinimas";
  if(s=="ACCESS LEVEL") return "PRIEIGOS LYGIS";
  if(s=="LICENCE") return "LICENCIJA";
  if(s=="private") return "privatu";
  if(s=="public") return "vieša";
  if(s=="trigger_dateStampChange") return "pakeista data";
  if(s=="trigger_domainAdd") return "pridėta sritis";
  if(s=="trigger_domainRemove") return "pašalinta sritis";
  if(s=="trigger_domainReorder") return "pakeista sričių tvarka";
  if(s=="trigger_domainChange") return "pakeista sritis";
  if(s=="trigger_desigAdd") return "pridėtas terminas";
  if(s=="trigger_desigRemove") return "pašalintas terminas";
  if(s=="trigger_desigReorder") return "pakeista terminų tvarka";
  if(s=="trigger_desigClarifChange") return "pakeistas paaiškinimas";
  if(s=="trigger_desigAcceptChange") return "pakeistas prieinamumas";
  if(s=="trigger_termLangChange") return "pakeista termino kalba";
  if(s=="trigger_termWordingChange") return "pakeisti termino žodžiai";
  if(s=="trigger_termInflectAdd") return "pridėta kaitybinė forma";
  if(s=="trigger_termInflectRemove") return "pašalinta kaitybinė forma";
  if(s=="trigger_termInflectReorder") return "pakeista kaitybinių formų tvarka";
  if(s=="trigger_termInflectLabelChange") return "pakeista kaitybinės formos žyma";
  if(s=="trigger_termInflectTextChange") return "pakeisti kaitybinės formos žodžiai";
  if(s=="trigger_termAnnotAdd") return "pridėta termino anotacija";
  if(s=="trigger_termAnnotRemove") return "pašalinta termino anotacija";
  if(s=="trigger_termAnnotReorder") return "pakeista terminų anotacijų tvarka";
  if(s=="trigger_termAnnotPositionChange") return "pakeista termino anotacijos vieta";
  if(s=="trigger_termAnnotLabelChange") return "pakeista termino anotacijos žyma";
  if(s=="trigger_introChange") return "pakeistas įvadas";
  if(s=="trigger_definitionAdd") return "pridėtas apibrėžimas";
  if(s=="trigger_definitionRemove") return "pašalintas apibrėžimas";
  if(s=="trigger_definitionReorder") return "pakeista apibrėžimų tvarka";
  if(s=="trigger_definitionTextChange") return "pakeistas apibrėžimo tekstas";
  if(s=="trigger_exampleAdd") return "pridėtas pavyzdys";
  if(s=="trigger_exampleRemove") return "pašalintas pavyzdys";
  if(s=="trigger_exampleReorder") return "pakeista pavyzdžių tvarka";
  if(s=="trigger_exampleTextAdd") return "pridėtas pavyzdinis sakinys";
  if(s=="trigger_exampleTextRemove") return "pašalintas pavyzdinis sakinys";
  if(s=="trigger_exampleTextReorder") return "pakeista pavyzdinių sakinių tvarka";
  if(s=="trigger_exampleTextChange") return "pakeisti pavyzdinio sakinio žodžiai";
  if(s=="trigger_collectionAdd") return "pridėtas rinkinys";
  if(s=="trigger_collectionRemove") return "pašalintas rinkinys";
  if(s=="trigger_collectionReorder") return "pakeista rinkinių tvarka";
  if(s=="trigger_collectionChange") return "pakeistas rinkinys";
  if(s=="trigger_extranetAdd") return "pridėtas ekstranetas";
  if(s=="trigger_extranetRemove") return "pašalintas ekstranetas";
  if(s=="trigger_extranetReorder") return "pakeista ekstranetų tvarka";
  if(s=="trigger_extranetChange") return "pakeistas ekstranetas";
  if(s=="trigger_sourceAdd") return "pridėtas šaltinis";
  if(s=="trigger_sourceRemove") return "pašalintas šaltinis";
  if(s=="trigger_sourceReorder") return "pakeista šaltinio tvarka";
  if(s=="trigger_sourceChange") return "pakeistas šaltinis";
  if(s=="trigger_nonessentialChange") return "pakeistas nebūtinumas";
  if(s=="(blank)") return "(tuščia)";
  if(s=="Simple Multilingual Termbase") return "Paprasta daugiakalbė terminų bazė";
  if(s=="Simple Bilingual Termbase") return "Paprasta dvikalbė terminų bazė";
  if(s=="Simple Monolingual Termbase") return "Paprasta vienakalbė terminų bazė";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Įveskite žmonėms suprantamą pavadinimą, pvz., \"Mano sporto terminų žodynas\". Vėliau galėsite tai pakeisti.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Tai bus jūsų terminų bazės adresas žiniatinklyje. Vėliau galėsite tai pakeisti.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "Čia galite pasirinkti šabloną, kad galėtumėte pradėti. Kiekviename šablone yra keletas įrašų pavyzdžių. Galėsite juos pakeisti arba ištrinti ir tinkinti šabloną.";
  if(s=="Your termbase is ready.") return "Jūsų terminų bazė paruošta.";
  if(s=="TERM OF THE DAY") return "DIENOS TERMINAS";
  if(s=="set to next available date") return "nustatykite kitą galimą datą";
  if(s=="Display from") return "Rodykite nuo";
  if(s=="Display until") return "Rodykite iki";
  if(s=="News and announcements") return "Naujienos ir skelbimai";
  if(s=="Create your account") return "Sukurkite savo paskyrą";
  if(s=="Reset your password") return "Pakeiskite savo slaptažodį";
  if(s=="Terminologue signup") return "Terminologue registracija";
  if(s=="Please follow the link below to create your Terminologue account:") return "Pasirinkite žemiau pateiktą nuorodą, kad sukurtumėte savo Terminologue paskyrą:";
  if(s=="Terminologue password reset") return "Terminologue slaptažodžio atnaujinimas";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Pasirinkite žemiau pateiktą nuorodą, kad atnaujintumėte savo Terminologue paskyrą:";
  if(s=="This page is only available in English.") return "Šis puslapis galimas tik anglų kalba.";
  if(s=="DRAFTING STATUS") return "RENGIMO BŪSENA";
  if(s=="draft entry") return "juodraščio įrašas";
  if(s=="finished entry") return "pabaigtas įrašas";
  if(s=="DRAFT") return "JUODRAŠTIS";
  if(s=="FINISHED") return "PABAIGTA";
  if(s=="any drafting status") return "bet kokia rengimo būsena";
  if(s=="Prefabricated comments") return "Išanksto sukurti komentarai";
  if(s=="NOTES") return "PASTABOS";
  if(s=="note") return "pastaba";
  if(s=="NOT") return "NE";
  if(s=="with or without notes") return "su arba be pastabų";
  if(s=="with a note") return "su pastaba";
  if(s=="with a note containing...") return "su pastaba turinčia...";
  if(s=="without notes") return "be pastabų";
  if(s=="any type") return "bet kokios rūšies";
  if(s=="private note, not shown on extranets") return "privati pastaba, nematoma ekstranetuose";
  if(s=="private note, shown on extranets") return "privati pastaba, matoma ekstranetuose";
  if(s=="public note") return "vieša pastaba";
  if(s=="Note types") return "Pastabų rūšys";
  if(s=="LEVEL") return "LYGIS";
  if(s=="with a comment") return "su komentaru";
  if(s=="with a comment containing...") return "su komentaru turinčiu...";
  if(s=="TBX export") return "TBX eksportavimas";
  if(s=="TBX import") return "TBX importavimas";
  if(s=="Empty the termbase") return "Išvalykite terminų bazę";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "Atsargiai! Ketinate ištrinti šią terminų bazę. To anuliuoti negalėsite.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "Atsargiai! Ketinate ištrinti visus įrašus ir jų istoriją. To anuliuoti negalėsite.";
  if(s=="RELATED TERMS") return "SUSIJĘ TERMINAI";
  if(s=="Your termbase at a glance") return "Terminų bazės apžvalga";
  if(s=="Number of entries") return "Įrašų skaičius";
  if(s=="Number of items in history log") return "Elementų skaičius žurnale";
  if(s=="Your termbase is stored in the file %F") return "Jūsų terminų bazė yra užsaugota faile %F";
  if(s=="File size") return "Failo dydis";
  if(s=="Download %F") return "Saugokite %F";
  if(s=="Upload %F") return "Įkelkite %F";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Įsitikinkite, kad įkeliamas failas yra tinkama Terminologue terminų bazė. Jei įkelsite ką nors kita, savo terminų bazei padarysite nepataisomą žalą.";
  if(s=="PARENT") return "PIRMINIS";
  if(s=="no parent") return "nėra pirminio";
  if(s=="excluding subdomains") return "neįtraukiami posričiai";
  if(s=="including subdomains") return "įtraukiami posričiai";
  if(s=="the entry has this domain") return "įrašas turi šią sritį";
  if(s=="the entry has only this domain") return "įrašas turi tik šią sritį";
  if(s=="the entry has not only this domain") return "įrašas turi ne tik šią sritį";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "Atsargiai! Jei pašalinsite save iš šios terminų bazės, prarasite prieigą prie jos.";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
