function L(s, gloss){
  if(s=="only") return function(s){
    return "Slechts "+s;
  };
  if(s=="READ-ONLY") return "ALLEEN-LEZEN";
  if(s=="Editing") return "Bewerken";
  if(s=="Dublin City University") return "Dublin City University";
  if(s=="Log out") return "Uitloggen";
  if(s=="Change your password") return "Uw wachtwoord wijzigen";
  if(s=="Registered user login") return "Geregistreerde gebruikerslogin";
  if(s=="Get an account") return "Een account aanmaken";
  if(s=="Forgot your password?") return "Wachtwoord vergeten?";
  if(s=="E-mail address") return "E-mailadres";
  if(s=="Password") return "Wachtwoord";
  if(s=="Log in") return "Aanmelden";
  if(s=="Your termbases") return "Uw termenbank";
  if(s=="You have no termbases yet.") return "U heeft nog geen termenbank.";
  if(s=="Create a termbase") return "Maak een termenbank";
  if(s=="Administration") return "Beheer";
  if(s=="Users") return "Gebruikers";
  if(s=="Termbases") return "Termenbanken";
  if(s=="smart search") return "smart search";
  if(s=="complete term") return "volledige term";
  if(s=="start of term") return "begin van de term";
  if(s=="end of term") return "einde van de term";
  if(s=="any part of term") return "elk onderdeel van de term";
  if(s=="any part except start or end") return "elk onderdeel, behalve het begin of einde";
  if(s=="search in all languages") return "zoeken in alle talen";
  if(s=="Configuration") return "Configuratie";
  if(s=="ADMIN") return "ADMIN";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "DEF";
  if(s=="XMPL") return "VRBLD";
  if(s=="CHECKING STATUS") return "STATUS CONTROLEREN";
  if(s=="PUBLISHING STATUS") return "STATUS PUBLICEREN";
  if(s=="TERMS") return "TERMEN";
  if(s=="DOMAINS") return "DOMEINEN";
  if(s=="term") return "term";
  if(s=="clarification") return "verduidelijking";
  if(s=="acceptability") return "aanvaardbaarheid";
  if(s=="source") return "bron";
  if(s=="inflected form") return "vervoeging";
  if(s=="annotation") return "aantekening";
  if(s=="domain") return "domein";
  if(s=="part of speech") return "woordsoort";
  if(s=="inflection") return "vervoegingsuitgang";
  if(s=="language of origin") return "brontaal";
  if(s=="symbol") return "symbool";
  if(s=="trademark") return "handelsmerk";
  if(s=="registered trademark") return "gedeponeerd handelsmerk";
  if(s=="proper noun") return "eigennaam";
  if(s=="formatting") return "opmaak";
  if(s=="italic") return "cursief";
  if(s=="Created") return "Gemaakt op";
  if(s=="Changed") return "Aangepast op";
  if(s=="Deleted") return "Verwijderd op";
  if(s=="Bulk-deleted") return "Massaal verwijderd";
  if(s=="while uploading") return "tijdens het uploaden";
  if(s=="By") return "Tegen";
  if(s=="When") return "Wanneer";
  if(s=="any checking status") return "elke controlestatus";
  if(s=="any publishing status") return "elke publicatiestatus";
  if(s=="any language") return "elke taal";
  if(s=="any acceptabilty or no acceptability") return "elke aanvaardbaarheid of geen aanvaardbaarheid";
  if(s=="any acceptabilty") return "elke aanvaardbaarheid";
  if(s=="no acceptability") return "geen aanvaardbaarheid";
  if(s=="any domain or no domain") return "elk domein of geen domein";
  if(s=="any domain") return "elk domein";
  if(s=="no domain") return "geen domein";
  if(s=="LAST MAJOR UPDATE") return "LAATSTE GROTE UPDATE";
  if(s=="set to today") return "ingesteld op vandaag";
  if(s=="Invalid e-mail address or password.") return "Ongeldig e-mailadres of wachtwoord.";
  if(s=="INTR") return "INTR";
  if(s=="COLL") return "COLL";
  if(s=="INTROS") return "INTRO‘S";
  if(s=="DEFINITIONS") return "DEFINITIES";
  if(s=="EXAMPLES") return "VOORBEELDEN";
  if(s=="COLLECTIONS") return "COLLECTIES";
  if(s=="definition") return "definitie";
  if(s=="example") return "voorbeeld";
  if(s=="sentence") return "zin";
  if(s=="collection") return "collectie";
  if(s=="any collection or no collection") return "elke collectie of geen collectie";
  if(s=="any collection") return "elke collectie";
  if(s=="no collection") return "geen collectie";
  if(s=="comments") return "opmerkingen";
  if(s=="with or without comments") return "met of zonder opmerkingen";
  if(s=="with comments") return "met opmerkingen";
  if(s=="without comments") return "zonder opmerkingen";
  if(s=="my comments") return "mijn opmerkingen";
  if(s=="with or without my comments") return "met of zonder mijn opmerkingen";
  if(s=="with my comments") return "met mijn opmerkingen";
  if(s=="without my comments") return "zonder mijn opmerkingen";
  if(s=="other people's comments") return "opmerkingen van anderen";
  if(s=="with or without other people's comments") return "met of zonder opmerkingen van anderen";
  if(s=="with other people's comments") return "met opmerkingen van anderen";
  if(s=="without other people's comments") return "zonder opmerkingen van anderen";
  if(s=="EXTRANET") return "EXTRANET";
  if(s=="EXT") return "EXT";
  if(s=="EXTRANETS") return "EXTRANETTEN";
  if(s=="extranet") return "extranet";
  if(s=="any extranet or no extranet") return "elk extranet of geen extranet";
  if(s=="any extranet") return "elk extranet";
  if(s=="no extranet") return "geen extranet";
  if(s=="sorting language") return "sorteertaal";
  if(s=="Create mutual cross-references") return "Creëeren van wederzijdse kruisverwijzingen";
  if(s=="Remove mutual cross-references") return "Verwijderen van wederzijdse kruisverwijzingen";
  if(s=="Merge into a single entry") return "Samenvoegen tot één enkel item";
  if(s=="SEE ALSO") return "ZIE OOK";
  if(s=="add to worklist") return "toevoegen aan de werklijst";
  if(s=="Domains") return "Domeinen";
  if(s=="Part-of-speech labels") return "Woordsoort labels";
  if(s=="Inflection labels") return "Vervoegingsuitgang-labels";
  if(s=="Acceptability labels") return "Aanvaardbaarheidslabels";
  if(s=="Sources") return "Bronnen";
  if(s=="Collections") return "Collecties";
  if(s=="Tags") return "Tags";
  if(s=="Extranets") return "Extranetten";
  if(s=="Name and blurb") return "Naam en flaptekst";
  if(s=="Features") return "Kenmerken";
  if(s=="Languages") return "Talen";
  if(s=="Publishing") return "Publiceren";
  if(s=="Change the termbase's URL") return "De URL van de termenbank veranderen";
  if(s=="Delete the termbase") return "De termenbank verwijderen";
  if(s=="TITLE") return "TITEL";
  if(s=="abbreviation") return "afkorting";
  if(s=="LANGUAGES") return "TALEN";
  if(s=="select all") return "alles selecteren";
  if(s=="unselect all") return "alles deselecteren";
  if(s=="PRIORITY") return "PRIORITEIT";
  if(s=="high") return "hoog";
  if(s=="medium") return "medium";
  if(s=="low") return "laag";
  if(s=="USERS") return "GEBRUIKERS";
  if(s=="e-mail address") return "e-mailadres";
  if(s=="user") return "gebruiker";
  if(s=="Alphabetical order") return "Alfabetische volgorde";
  if(s=="Similar terms (click to insert)") return "Vergelijkbare termen (klik om in te voegen)";
  if(s=="Other entries that share this term") return "Andere fiches die dezelfde term hebben";
  if(s=="stop sharing") return "stoppen met delen";
  if(s=="Change checking status to") return "De controlestatus veranderen naar";
  if(s=="Change publishing status to") return "De publicatiestatus veranderen naar";
  if(s=="Add to extranet") return "Toevoegen aan extranet";
  if(s=="Remove from extranet") return "Verwijderen uit extranet";
  if(s=="checked") return "gecontroleerd";
  if(s=="not checked") return "niet gecontroleerd";
  if(s=="publishable") return "geschikt voor publicatie";
  if(s=="hidden") return "verborgen";
  if(s=="CHECKED") return "GECONTROLEERD";
  if(s=="NOT CHECKED") return "NIET GECONTROLEERD";
  if(s=="PUBLISHABLE") return "GESCHIKT VOOR PUBLICATIE";
  if(s=="HIDDEN") return "VERBORGEN";
  if(s=="non-essential") return "niet-essentieel";
  if(s=="STATUS") return "STATUS";
  if(s=="live") return "actief";
  if(s=="not live") return "niet actief";
  if(s=="any clarification or no clarification") return "enige verduidelijking of geen verduidelijking";
  if(s=="any clarification") return "enige verduidelijking";
  if(s=="no clarification") return "geen verduidelijking";
  if(s=="clarification containing...") return "verduidelijking bevat...";
  if(s=="any intro or no intro") return "elke introductie of geen introductie";
  if(s=="any intro") return "elke introductie";
  if(s=="no intro") return "geen introductie";
  if(s=="intro containing...") return "introductie bevat...";
  if(s=="any definition or no definition") return "elke definitie of geen definitie";
  if(s=="any definition") return "elke definitie";
  if(s=="no definition") return "geen definitie";
  if(s=="definition containing...") return "definitie bevat...";
  if(s=="any example or no example") return "elk voorbeeld of geen voorbeeld";
  if(s=="any example") return "elk voorbeeld";
  if(s=="no example") return "geen voorbeeld";
  if(s=="example containing...") return "voorbeeld bevat...";
  if(s=="Automatic changes") return "Automatische veranderingen";
  if(s=="NAME") return "NAAM";
  if(s=="BLURB") return "FLAPTEKST";
  if(s=="level") return "niveau";
  if(s=="reader") return "lezer";
  if(s=="editor") return "redacteur";
  if(s=="creator") return "maker";
  if(s=="administrator") return "beheerder";
  if(s=="configurator") return "configurator";
  if(s=="no change") return "geen wijziging";
  if(s=="change to 'not checked'") return "verander naar 'niet gecontroleerd'";
  if(s=="change to 'hidden'") return "verander naar ‘verborgen‘";
  if(s=="change to 'not checked' and 'hidden'") return "veranderen naar 'niet gecontroleerd' en 'verborgen'";
  if(s=="LAST SEEN") return "LAATST GEZIEN";
  if(s=="NEVER") return "NOOIT";
  if(s=="No termbases") return "Geen termenbank";
  if(s=="language") return "taal";
  if(s=="major") return "groot";
  if(s=="minor") return "klein";
  if(s=="role") return "rol";
  if(s=="title") return "titel";
  if(s=="ACCESS LEVEL") return "TOEGANGSNIVEAU";
  if(s=="LICENCE") return "LICENTIE";
  if(s=="private") return "privé";
  if(s=="public") return "publiek";
  if(s=="trigger_dateStampChange") return "datumstempel gewijzigd";
  if(s=="trigger_domainAdd") return "domein toegevoegd";
  if(s=="trigger_domainRemove") return "domein verwijderd";
  if(s=="trigger_domainReorder") return "domein herordend";
  if(s=="trigger_domainChange") return "domein gewijzigd";
  if(s=="trigger_desigAdd") return "term toegevoegd";
  if(s=="trigger_desigRemove") return "term verwijderd";
  if(s=="trigger_desigReorder") return "term herordend";
  if(s=="trigger_desigClarifChange") return "verklaring gewijzigd";
  if(s=="trigger_desigAcceptChange") return "aanvaardbaarheid gewijzigd";
  if(s=="trigger_termLangChange") return "taal van term gewijzigd";
  if(s=="trigger_termWordingChange") return "verwoording van term gewijzigd";
  if(s=="trigger_termInflectAdd") return "vervoeging toegevoegd";
  if(s=="trigger_termInflectRemove") return "vervoeging verwijderd";
  if(s=="trigger_termInflectReorder") return "vervoeging herordend";
  if(s=="trigger_termInflectLabelChange") return "vervoegingslabel gewijzigd";
  if(s=="trigger_termInflectTextChange") return "verwoording van vervoeging gewijzigd";
  if(s=="trigger_termAnnotAdd") return "aantekening term toegevoegd";
  if(s=="trigger_termAnnotRemove") return "aantekening term verwijderd";
  if(s=="trigger_termAnnotReorder") return "aantekeningen term herordend";
  if(s=="trigger_termAnnotPositionChange") return "positie aantekening term gewijzigd";
  if(s=="trigger_termAnnotLabelChange") return "annotatielabel van term gewijzigd";
  if(s=="trigger_introChange") return "introductie gewijzigd";
  if(s=="trigger_definitionAdd") return "definitie toegevoegd";
  if(s=="trigger_definitionRemove") return "definitie verwijderd";
  if(s=="trigger_definitionReorder") return "definitie herordend";
  if(s=="trigger_definitionTextChange") return "definitietekst gewijzigd";
  if(s=="trigger_exampleAdd") return "voorbeeld toegevoegd";
  if(s=="trigger_exampleRemove") return "voorbeeld verwijderd";
  if(s=="trigger_exampleReorder") return "voorbeeld herordend";
  if(s=="trigger_exampleTextAdd") return "voorbeeldzin toegevoegd";
  if(s=="trigger_exampleTextRemove") return "voorbeeldzin verwijderd";
  if(s=="trigger_exampleTextReorder") return "voorbeeldzinnen herordend";
  if(s=="trigger_exampleTextChange") return "verwoording voorbeeldzin gewijzigd";
  if(s=="trigger_collectionAdd") return "collectie toegevoegd";
  if(s=="trigger_collectionRemove") return "collectie verwijderd";
  if(s=="trigger_collectionReorder") return "collectie herordend";
  if(s=="trigger_collectionChange") return "collectie gewijzigd";
  if(s=="trigger_extranetAdd") return "extranet toegevoegd";
  if(s=="trigger_extranetRemove") return "extranet verwijderd";
  if(s=="trigger_extranetReorder") return "extranet herordend";
  if(s=="trigger_extranetChange") return "extranet gewijzigd";
  if(s=="trigger_sourceAdd") return "bron toegevoegd";
  if(s=="trigger_sourceRemove") return "bron verwijderd";
  if(s=="trigger_sourceReorder") return "bron herordend";
  if(s=="trigger_sourceChange") return "bron gewijzigd";
  if(s=="trigger_nonessentialChange") return "het niet-essentiële gewijzigd";
  if(s=="(blank)") return "(blanco)";
  if(s=="Simple Multilingual Termbase") return "Eenvoudige Meertalige Termenbank";
  if(s=="Simple Bilingual Termbase") return "Eenvoudige Tweetalige Termenbank";
  if(s=="Simple Monolingual Termbase") return "Eenvoudige Eentalige Termenbank";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Voer een menselijk leesbare titel in zoals \"Mijn woordenboek van sporttermen\". U kunt dit later nog veranderen.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Dit zal het adres van uw termenbank op het web zijn. U kunt dit later nog veranderen.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "U kunt hier een sjabloon kiezen om te beginnen. Elk sjabloon wordt voorzien van een paar voorbeeldfiches. U kunt deze wijzigen of verwijderen en het sjabloon aanpassen.";
  if(s=="Your termbase is ready.") return "Uw termenbank is klaar.";
  if(s=="TERM OF THE DAY") return "TERM VAN DE DAG";
  if(s=="set to next available date") return "ingesteld op de volgende beschikbare datum";
  if(s=="Display from") return "Tonen van";
  if(s=="Display until") return "Tonen tot";
  if(s=="News and announcements") return "Nieuws en aankondigingen";
  if(s=="Create your account") return "Uw account aanmaken";
  if(s=="Reset your password") return "Uw wachtwoord resetten";
  if(s=="Terminologue signup") return "Aanmelden in Terminologue";
  if(s=="Please follow the link below to create your Terminologue account:") return "Volg de onderstaande link om uw Terminologue-account aan te maken:";
  if(s=="Terminologue password reset") return "Terminologue-wachtwoord resettten";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Volg de onderstaande link om uw Terminologue-wachtwoord te resetten:";
  if(s=="This page is only available in English.") return "Deze pagina is alleen beschikbaar in het Engels.";
  if(s=="DRAFTING STATUS") return "SCHETSSTATUS";
  if(s=="draft entry") return "conceptfiche";
  if(s=="finished entry") return "afgewerkt fiche";
  if(s=="DRAFT") return "CONCEPT";
  if(s=="FINISHED") return "AFGEWERKT";
  if(s=="any drafting status") return "elke vorm van concept";
  if(s=="Prefabricated comments") return "Geprefabriceerde opmerkingen";
  if(s=="NOTES") return "OPMERKINGEN";
  if(s=="note") return "opmerking";
  if(s=="NOT") return "NIET";
  if(s=="with or without notes") return "met of zonder opmerkingen";
  if(s=="with a note") return "met een opmerking";
  if(s=="with a note containing...") return "met een opmerking over...";
  if(s=="without notes") return "zonder opmerkingen";
  if(s=="any type") return "elk type";
  if(s=="private note, not shown on extranets") return "privé opmerking, niet afgebeeld op extranets";
  if(s=="private note, shown on extranets") return "privé opmerking, afgebeeld op extranets";
  if(s=="public note") return "publieke opmerking";
  if(s=="Note types") return "Opmerkingstypes";
  if(s=="LEVEL") return "NIVEAU";
  if(s=="with a comment") return "met een opmerking";
  if(s=="with a comment contaning...") return "met een opmerking over...";
  if(s=="TBX export") return "TBX-export";
  if(s=="TBX import") return "TBX-import";
  if(s=="Empty the termbase") return "De termenbank leegmaken";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "Opgelet! U staat op het punt om deze termenbank te verwijderen. U zult dit niet ongedaan kunnen maken.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "Opgelet! U staat op het punt om alle fiches en hun geschiedenis te verwijderen. U zult dit niet ongedaan kunnen maken.";
  if(s=="RELATED TERMS") return "GERELATEERDE TERMIJNEN";
  if(s=="Your termbase at a glance") return "Uw termenbank in een oogopslag";
  if(s=="Number of entries") return "Aantal fiches";
  if(s=="Number of items in history log") return "Aantal items in het geschiedenis";
  if(s=="Your termbase is stored in the file %F") return "Uw termenbank wordt opgeslagen in het bestand %F";
  if(s=="File size") return "Bestandsgrootte";
  if(s=="Download %F") return "%F downloaden";
  if(s=="Upload %F") return "%F uploaden";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Zorg ervoor dat het bestand dat u uploadt een geldige Terminologue-termbase is. Als u iets anders uploadt, kan dit permanente schade toebrengen aan uw termenbank.";
  if(s=="PARENT") return "translation required";
  if(s=="no parent") return "translation required";
  if(s=="excluding subdomains") return "translation required";
  if(s=="including subdomains") return "translation required";
  if(s=="the entry has this domain") return "translation required";
  if(s=="the entry has only this domain") return "translation required";
  if(s=="the entry has not only this domain") return "translation required";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "translation required";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
