function L(s, gloss){
  if(s=="only") return function(s){
    return "Только "+s;
  };
  if(s=="READ-ONLY") return "ТОЛЬКО ДЛЯ ЧТЕНИЯ";
  if(s=="Editing") return "Редактирование";
  if(s=="Dublin City University") return "Городской университет Дублина";
  if(s=="Log out") return "Выход из системы";
  if(s=="Change your password") return "Изменить пароль";
  if(s=="Registered user login") return "Сохраненный логин пользователя";
  if(s=="Get an account") return "Завести аккаунт";
  if(s=="Forgot your password?") return "Забыли пароль?";
  if(s=="E-mail address") return "Электронный адрес";
  if(s=="Password") return "Пароль";
  if(s=="Log in") return "Вход в систему";
  if(s=="Your termbases") return "Ваши термбазы ";
  if(s=="You have no termbases yet.") return "У вас нет созданных термбаз.";
  if(s=="Create a termbase") return "Создать термбазу";
  if(s=="Administration") return "Управление ";
  if(s=="Users") return "Пользователи";
  if(s=="Termbases") return "Термбазы";
  if(s=="smart search") return "умный поиск";
  if(s=="complete term") return "законченный термин";
  if(s=="start of term") return "начало термина";
  if(s=="end of term") return "конец термина";
  if(s=="any part of term") return "любая часть термина";
  if(s=="any part except start or end") return "любая часть, кроме начала или конца";
  if(s=="search in all languages") return "поиск по всем языкам";
  if(s=="Configuration") return "Конфигурация";
  if(s=="ADMIN") return "ADMIN";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "DEF";
  if(s=="XMPL") return "XMPL";
  if(s=="CHECKING STATUS") return "СТАТУС ПРОВЕРКИ";
  if(s=="PUBLISHING STATUS") return "СТАТУС ПУБЛИКАЦИИ";
  if(s=="TERMS") return "ТЕРМИНЫ";
  if(s=="DOMAINS") return "ДОМЕНЫ";
  if(s=="term") return "термин";
  if(s=="clarification") return "пояснение";
  if(s=="acceptability") return "приемлемость";
  if(s=="source") return "источник";
  if(s=="inflected form") return "измененная форма";
  if(s=="annotation") return "примечание";
  if(s=="domain") return "домен";
  if(s=="part of speech") return "часть речи";
  if(s=="inflection") return "флексия";
  if(s=="language of origin") return "исходный язык";
  if(s=="symbol") return "символ";
  if(s=="trademark") return "товарный знак";
  if(s=="registered trademark") return "зарегистрированный товарный знак";
  if(s=="proper noun") return "имя собственное";
  if(s=="formatting") return "форматирование";
  if(s=="italic") return "курсив";
  if(s=="Created") return "Создано";
  if(s=="Changed") return "Изменено";
  if(s=="Deleted") return "Удалено";
  if(s=="Bulk-deleted") return "Удаленно массово ";
  if(s=="while uploading") return "во время загрузки";
  if(s=="By") return "Выполнено";
  if(s=="When") return "Когда";
  if(s=="any checking status") return "любой статус проверки";
  if(s=="any publishing status") return "любой статус публикации";
  if(s=="any language") return "любой язык";
  if(s=="any acceptability or no acceptability") return "приемлемость или неприемлемость";
  if(s=="any acceptability") return "любая приемлемость";
  if(s=="no acceptability") return "неприемлемость";
  if(s=="any domain or no domain") return "любой домен или без домена";
  if(s=="any domain") return "любой домен";
  if(s=="no domain") return "без домена";
  if(s=="LAST MAJOR UPDATE") return "ПОСЛЕДНЕЕ КРУПНОЕ ОБНОВЛЕНИЕ";
  if(s=="set to today") return "установить на сегодня";
  if(s=="Invalid e-mail address or password.") return "Недействительный адрес электронной почты или пароль.";
  if(s=="INTR") return "INTR";
  if(s=="COLL") return "COLL";
  if(s=="INTROS") return "ВСТУПЛЕНИЕ";
  if(s=="DEFINITIONS") return "ОПРЕДЕЛЕНИЯ";
  if(s=="EXAMPLES") return "ПРИМЕРЫ";
  if(s=="COLLECTIONS") return "КОЛЛЕКЦИИ";
  if(s=="definition") return "определение";
  if(s=="example") return "пример";
  if(s=="sentence") return "предложение";
  if(s=="collection") return "коллекция";
  if(s=="any collection or no collection") return "любая коллекция или без коллекций";
  if(s=="any collection") return "любая коллекция";
  if(s=="no collection") return "без коллекции";
  if(s=="comments") return "комментарии";
  if(s=="with or without comments") return "с комментариями или без";
  if(s=="with comments") return "с комментариями";
  if(s=="without comments") return "без комментариев";
  if(s=="my comments") return "мои комментарии";
  if(s=="with or without my comments") return "с моими комментариями или без них";
  if(s=="with my comments") return "с моими комментариями";
  if(s=="without my comments") return "без моих комментариев";
  if(s=="other people's comments") return "чужие комментарии ";
  if(s=="with or without other people's comments") return "с чужими комментариями или без";
  if(s=="with other people's comments") return "с чужими комментариями";
  if(s=="without other people's comments") return "без чужих комментариев";
  if(s=="EXTRANET") return "ЭКСТРАНЕТ";
  if(s=="EXT") return "EXT";
  if(s=="EXTRANETS") return "ЭКСТРАНЕТЫ";
  if(s=="extranet") return "экстранет";
  if(s=="any extranet or no extranet") return "любой экстранет или без экстранета ";
  if(s=="any extranet") return "любой экстранет";
  if(s=="no extranet") return "без экстранета ";
  if(s=="sorting language") return "язык сортировки";
  if(s=="Create mutual cross-references") return "Создать общие перекрёстные ссылки";
  if(s=="Remove mutual cross-references") return "Удалить общие перекрёстные ссылки";
  if(s=="Merge into a single entry") return "Объединить в одну запись";
  if(s=="SEE ALSO") return "СМОТРИ ТАКЖЕ";
  if(s=="add to worklist") return "внести в рабочий список";
  if(s=="Domains") return "Домены";
  if(s=="Part-of-speech labels") return "Ярлык части речи";
  if(s=="Inflection labels") return "Ярлык флексии";
  if(s=="Acceptability labels") return "Ярлык приемлемости";
  if(s=="Sources") return "Источники";
  if(s=="Collections") return "Коллекции";
  if(s=="Tags") return "Теги";
  if(s=="Extranets") return "Экстранеты";
  if(s=="Name and blurb") return "Имя и издательская реклама";
  if(s=="Features") return "Особенности";
  if(s=="Languages") return "Языки";
  if(s=="Publishing") return "Публикация";
  if(s=="Change the termbase's URL") return "Изменить URL-адрес термбазы";
  if(s=="Delete the termbase") return "Удалить термбазу";
  if(s=="TITLE") return "ЗАГОЛОВОК";
  if(s=="abbreviation") return "аббревиатура";
  if(s=="LANGUAGES") return "ЯЗЫКИ";
  if(s=="select all") return "выбрать все";
  if(s=="unselect all") return "отменить выбор";
  if(s=="PRIORITY") return "УРОВЕНЬ ПРИОРИТЕТА";
  if(s=="high") return "высокий ";
  if(s=="medium") return "средний ";
  if(s=="low") return "низкий";
  if(s=="USERS") return "ПОЛЬЗОВАТЕЛИ";
  if(s=="e-mail address") return "электронный адрес";
  if(s=="user") return "пользователь";
  if(s=="Alphabetical order") return "алфавитный порядок";
  if(s=="Similar terms (click to insert)") return "Аналогичные термины (нажмите, чтобы вставить)";
  if(s=="Other entries that share this term") return "Другие записи, которые включают этот термин";
  if(s=="stop sharing") return "прекратить совместное использование";
  if(s=="Change checking status to") return "Изменить статус проверки на";
  if(s=="Change publishing status to") return "Изменить статус публикации на";
  if(s=="Add to extranet") return "Добавить в экстранет";
  if(s=="Remove from extranet") return "Удалить из экстранета";
  if(s=="checked") return "проверено";
  if(s=="not checked") return "не проверено ";
  if(s=="publishable") return "доступный для публикации";
  if(s=="hidden") return "скрытый";
  if(s=="CHECKED") return "ПРОВЕРЕНО";
  if(s=="NOT CHECKED") return "НЕ ПРОВЕРЕНО";
  if(s=="PUBLISHABLE") return "ДОСТУПНЫЙ ДЛЯ ПУБЛИКАЦИИ";
  if(s=="HIDDEN") return "СКРЫТЫЙ";
  if(s=="non-essential") return "второстепенный";
  if(s=="STATUS") return "СТАТУС";
  if(s=="live") return "активен";
  if(s=="not live") return "не активен";
  if(s=="any clarification or no clarification") return "любое пояснение или без пояснений";
  if(s=="any clarification") return "любое пояснение";
  if(s=="no clarification") return "без пояснения";
  if(s=="clarification containing...") return "пояснение, содержащее...";
  if(s=="any intro or no intro") return "любое вступление или без вступлений";
  if(s=="any intro") return "любое вступление ";
  if(s=="no intro") return "без вступления";
  if(s=="intro containing...") return "вступление, содержащее...";
  if(s=="any definition or no definition") return "любое определение или без определений";
  if(s=="any definition") return "любое определение";
  if(s=="no definition") return "без определений";
  if(s=="definition containing...") return "определение, содержащее...";
  if(s=="any example or no example") return "любой пример или без примеров";
  if(s=="any example") return "любой пример";
  if(s=="no example") return "без примеров";
  if(s=="example containing...") return "пример, содержащий...";
  if(s=="Automatic changes") return "Автоматические изменения";
  if(s=="NAME") return "ИМЯ";
  if(s=="BLURB") return "ИЗДАТЕЛЬСКАЯ РЕКЛАМА";
  if(s=="level") return "уровень";
  if(s=="reader") return "Читатель";
  if(s=="editor") return "редактор";
  if(s=="creator") return "создатель";
  if(s=="administrator") return "администратор";
  if(s=="configurator") return "конфигуратор";
  if(s=="no change") return "без изменений";
  if(s=="change to 'not checked'") return "изменить на «не проверено»";
  if(s=="change to 'hidden'") return "изменить на «скрыто»";
  if(s=="change to 'not checked' and 'hidden'") return "изменить на «не проверено» и «скрыто»";
  if(s=="LAST SEEN") return "ЗАМЕЧЕННЫЙ В ПОСЛЕДНИЙ РАЗ";
  if(s=="NEVER") return "НИКОГДА";
  if(s=="No termbases") return "Термбазы отсутствуют";
  if(s=="language") return "язык";
  if(s=="major") return "главный";
  if(s=="minor") return "второстепенный";
  if(s=="role") return "роль";
  if(s=="title") return "заголовок";
  if(s=="ACCESS LEVEL") return "УРОВЕНЬ ДОСТУПА";
  if(s=="LICENCE") return "ПРАВА";
  if(s=="private") return "личная";
  if(s=="public") return "публичная";
  if(s=="trigger_dateStampChange") return "метка даты изменена";
  if(s=="trigger_domainAdd") return "домен добавлен";
  if(s=="trigger_domainRemove") return "домен удален";
  if(s=="trigger_domainReorder") return "домены перегруппированы ";
  if(s=="trigger_domainChange") return "домен изменен";
  if(s=="trigger_desigAdd") return "термин добавлен ";
  if(s=="trigger_desigRemove") return "термин удален";
  if(s=="trigger_desigReorder") return "термины перегруппированы";
  if(s=="trigger_desigClarifChange") return "пояснение изменено";
  if(s=="trigger_desigAcceptChange") return "приемлемость изменена ";
  if(s=="trigger_termLangChange") return "язык термина изменен";
  if(s=="trigger_termWordingChange") return "формулировка термина изменена";
  if(s=="trigger_termInflectAdd") return "выбранная форма добавлена ";
  if(s=="trigger_termInflectRemove") return "выбранная форма удалена";
  if(s=="trigger_termInflectReorder") return "выбранные формы перегруппированы";
  if(s=="trigger_termInflectLabelChange") return "ярлык выбранных форм изменен";
  if(s=="trigger_termInflectTextChange") return "формулировка выбранной формы изменена ";
  if(s=="trigger_termAnnotAdd") return "примечание к термину добавлено";
  if(s=="trigger_termAnnotRemove") return "примечание к термину удалено";
  if(s=="trigger_termAnnotReorder") return "примечания к термину перегруппированы";
  if(s=="trigger_termAnnotPositionChange") return "позиция примечаний к термину изменена";
  if(s=="trigger_termAnnotLabelChange") return "ярлык примечания к термину изменен";
  if(s=="trigger_introChange") return "вступление изменено";
  if(s=="trigger_definitionAdd") return "определение добавлено";
  if(s=="trigger_definitionRemove") return "вступление удалено";
  if(s=="trigger_definitionReorder") return "определения перегруппированы";
  if(s=="trigger_definitionTextChange") return "текст определения изменен";
  if(s=="trigger_exampleAdd") return "пример добавлен ";
  if(s=="trigger_exampleRemove") return "пример удален ";
  if(s=="trigger_exampleReorder") return "примеры перегруппированы";
  if(s=="trigger_exampleTextAdd") return "образец предложения добавлен ";
  if(s=="trigger_exampleTextRemove") return "образец предложения удален ";
  if(s=="trigger_exampleTextReorder") return "образцы предложений перегруппированы";
  if(s=="trigger_exampleTextChange") return "формулировка образца предложения изменена";
  if(s=="trigger_collectionAdd") return "коллекция добавлена";
  if(s=="trigger_collectionRemove") return "коллекция удалена ";
  if(s=="trigger_collectionReorder") return "коллекции перегруппированы ";
  if(s=="trigger_collectionChange") return "коллекция изменена ";
  if(s=="trigger_extranetAdd") return "экстранет добавлен";
  if(s=="trigger_extranetRemove") return "экстранет удален";
  if(s=="trigger_extranetReorder") return "экстранеты перегруппированы";
  if(s=="trigger_extranetChange") return "экстранет изменен";
  if(s=="trigger_sourceAdd") return "источник добавлен ";
  if(s=="trigger_sourceRemove") return "источник удален ";
  if(s=="trigger_sourceReorder") return "источник перегруппирован ";
  if(s=="trigger_sourceChange") return "источник изменен ";
  if(s=="trigger_nonessentialChange") return "несущественность изменена";
  if(s=="(blank)") return "(пустое место)";
  if(s=="Simple Multilingual Termbase") return "Простая многоязычная термбаза";
  if(s=="Simple Bilingual Termbase") return "Простая двуязычная термбаза";
  if(s=="Simple Monolingual Termbase") return "Простая одноязычная термбаза";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Введите легко читаемый заголовок, например, \"Мой Словарь  Спортивных Терминов\". Вы сможете изменить его позже.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Это будет адресом вашей термбазы в интернете. Вы сможете изменить его позже.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "Вы можете выбрать шаблон здесь, чтобы начать. В каждом шаблоне есть несколько примеров записей. Вы сможете изменить или удалить их и модифицировать шаблон.";
  if(s=="Your termbase is ready.") return "Ваша термбаза готова.";
  if(s=="TERM OF THE DAY") return "ТЕРМИН ДНЯ";
  if(s=="set to next available date") return "назначить на следующую доступную дату";
  if(s=="Display from") return "Отображать с";
  if(s=="Display until") return "Отображать до";
  if(s=="News and announcements") return "Новости и объявления";
  if(s=="Create your account") return "Создать свой аккаунт";
  if(s=="Reset your password") return "Сбросить пароль";
  if(s=="Terminologue signup") return "Регистрация в Terminologue";
  if(s=="Please follow the link below to create your Terminologue account:") return "Пожалуйста, перейдите по ссылке ниже, чтобы создать свой аккаунт в Terminologue:";
  if(s=="Terminologue password reset") return "Сброс пароля в Terminologue";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Пожалуйста, перейдите по ссылке ниже, чтобы сбросить ваш пароль в Terminologue:";
  if(s=="This page is only available in English.") return "Эта страница доступна только на английском языке.";
  if(s=="DRAFTING STATUS") return "СОСТОЯНИЕ РАЗРАБОТКИ";
  if(s=="draft entry") return "черновой вариант записи";
  if(s=="finished entry") return "законченная запись";
  if(s=="DRAFT") return "ЧЕРНОВОЙ ВАРИАНТ";
  if(s=="FINISHED") return "ЗАКОНЧЕНО ";
  if(s=="any drafting status") return "любой черновой статус";
  if(s=="Prefabricated comments") return "Подготовленные комментарии";
  if(s=="NOTES") return "ПРИМЕЧАНИЯ";
  if(s=="note") return "примечание";
  if(s=="NOT") return "НЕ";
  if(s=="with or without notes") return "с примечаниями или без примечаний";
  if(s=="with a note") return "с примечанием";
  if(s=="with a note containing...") return "с примечанием, содержащим";
  if(s=="without notes") return "без примечаний";
  if(s=="any type") return "любой вид";
  if(s=="private note, not shown on extranets") return "личное примечание, не показанное в экстранетах";
  if(s=="private note, shown on extranets") return "личное примечание, показанное в экстранетах";
  if(s=="public note") return "открытое примечание";
  if(s=="Note types") return "виды примечаний";
  if(s=="LEVEL") return "УРОВЕНЬ";
  if(s=="with a comment") return "с комментарием";
  if(s=="with a comment containing...") return "с комментарием, содержащим...";
  if(s=="TBX export") return "экспорт TBX";
  if(s=="TBX import") return "импорт TBX";
  if(s=="Empty the termbase") return "Опустошить термбазу";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "Внимание! Вы собираетесь удалить эту термбазу. Вы не сможете отменить это действие.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "Внимание! Вы собираетесь удалить все записи и их историю. Вы не сможете отменить это действие.";
  if(s=="RELATED TERMS") return "СВЯЗАННЫЕ ТЕРМНИНЫ";
  if(s=="Your termbase at a glance") return "Краткий обзор вашей термбазы";
  if(s=="Number of entries") return "Количество записей";
  if(s=="Number of items in history log") return "Количество элементов в журнале истории";
  if(s=="Your termbase is stored in the file %F") return "Ваша термбаза хранится в файле %F";
  if(s=="File size") return "Размер файла";
  if(s=="Download %F") return "Скачать %F";
  if(s=="Upload %F") return "Загрузить %F";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Убедитесь, что загружаемый файл является действующей термбазой Terminologue. Если вы загрузите что-либо еще, вы нанесете непоправимый ущерб вашей термбазе. ";
  if(s=="PARENT") return "translation required";
  if(s=="no parent") return "translation required";
  if(s=="excluding subdomains") return "translation required";
  if(s=="including subdomains") return "translation required";
  if(s=="the entry has this domain") return "translation required";
  if(s=="the entry has only this domain") return "translation required";
  if(s=="the entry has not only this domain") return "translation required";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "translation required";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
