function L(s, gloss){
  if(s=="only") return function(s){
    return s+" amháin";
  };
  if(s=="READ-ONLY") return "xx";
  if(s=="Editing") return "xx";
  if(s=="Dublin City University") return "xx";
  if(s=="Log out") return "xx";
  if(s=="Change your password") return "xx";
  if(s=="Registered user login") return "xx";
  if(s=="Get an account") return "xx";
  if(s=="Forgot your password?") return "xx";
  if(s=="E-mail address") return "xx";
  if(s=="Password") return "xx";
  if(s=="Log in") return "xx";
  if(s=="Your termbases") return "xx";
  if(s=="You have no termbases yet.") return "xx";
  if(s=="Create a termbase") return "xx";
  if(s=="Administration") return "xx";
  if(s=="Users") return "Användare";
  if(s=="Termbases") return "xx";
  if(s=="smart search") return "xx";

  if(s=="complete term") return "xx";
  if(s=="start of term") return "xx";
  if(s=="end of term") return "xx";
  if(s=="any part of term") return "xx";
  if(s=="any part except start or end") return "xx";

  if(s=="search in all languages") return "xx";
  if(s=="Configuration") return "Konfiguration";
  if(s=="ADMIN") return "xx";
  if(s=="TRM") return "TRM";
  if(s=="DOM") return "DOM";
  if(s=="DEF") return "xx";
  if(s=="XMPL") return "SMPL"
  if(s=="CHECKING STATUS") return "KONTROLLSTATUS";
  if(s=="PUBLISHING STATUS") return "PUBLICERINGSSTATUS";
  if(s=="TERMS") return "TERMER";
  if(s=="DOMAINS") return "DOMÄNER";
  if(s=="term") return "xx";
  if(s=="clarification") return "xx";
  if(s=="acceptability") return "acceptans";
  if(s=="source") return "källa";
  if(s=="inflected form") return "böjningsform";
  if(s=="annotation") return "annotering";
  if(s=="domain") return "xx";
  if(s=="subdomain") return "xx";
  if(s=="part of speech") return "xx";
  if(s=="inflection") return "xx";
  if(s=="language of origin") return "xx";
  if(s=="symbol") return "xx";
  if(s=="trademark") return "xx";
  if(s=="registered trademark") return "xx";
  if(s=="proper noun") return "xx";
  if(s=="formatting") return "xx";
  if(s=="italic") return "xx";
  if(s=="none" && gloss=="no subdomain") return "xx";
  if(s=="Created") return "xx";
  if(s=="Changed") return "xx";
  if(s=="Deleted") return "xx";
  if(s=="Bulk-deleted") return "xx";
  if(s=="while uploading") return "xx";
  if(s=="By") return "xx";
  if(s=="When") return "xx";
  if(s=="any checking status") return "xx";
  if(s=="any publishing status") return "xx";
  if(s=="any language") return "xx";
  if(s=="any acceptabilty or no acceptability") return "xx";
  if(s=="any acceptabilty") return "xx";
  if(s=="no acceptability") return "xx";
  if(s=="any domain or no domain") return "xx";
  if(s=="any domain") return "xx";
  if(s=="no domain") return "xx";
  if(s=="any subdomain or no subdomain") return "xx";
  if(s=="any subdomain") return "xx";
  if(s=="no subdomain") return "xx";
  if(s=="LAST MAJOR UPDATE") return "SENASTE STÖRRE UPPDATERING";
  if(s=="set to today") return "använd dagens datum";
  if(s=="Invalid e-mail address or password.") return "xx";
  if(s=="INTR") return "DIS";
  if(s=="COLL") return "xx";
  if(s=="INTROS") return "DISAMBIGUERARE";
  if(s=="DEFINITIONS") return "xx";
  if(s=="EXAMPLES") return "xx";
  if(s=="COLLECTIONS") return "xx";
  if(s=="definition") return "xx";
  if(s=="example") return "xx";
  if(s=="sentence") return "xx";
  if(s=="collection") return "xx";
  if(s=="any collection or no collection") return "xx";
  if(s=="any collection") return "xx";
  if(s=="no collection") return "xx";
  if(s=="comments") return "xx";
  if(s=="with or without comments") return "xx";
  if(s=="with comments") return "xx";
  if(s=="without comments") return "xx";
  if(s=="my comments") return "xx";
  if(s=="with or without my comments") return "xx";
  if(s=="with my comments") return "xx";
  if(s=="without my comments") return "xx";
  if(s=="other people's comments") return "xx";
  if(s=="with or without other people's comments") return "xx";
  if(s=="with other people's comments") return "xx";
  if(s=="without other people's comments") return "xx";
  if(s=="EXTRANET") return "xx";
  if(s=="EXT") return "xx";
  if(s=="EXTRANETS") return "EXTRANÄT";
  if(s=="extranet") return "xx";
  if(s=="any extranet or no extranet") return "xx";
  if(s=="any extranet") return "xx";
  if(s=="no extranet") return "xx";
  if(s=="sorting language") return "xx";
  if(s=="Create mutual cross-references") return "xx";
  if(s=="Remove mutual cross-references") return "xx";
  if(s=="Merge into a single entry") return "xx";
  if(s=="SEE ALSO") return "xx";
  if(s=="add to worklist") return "xx";
  if(s=="Domains") return "Domäner";
  if(s=="Part-of-speech labels") return "Ordklassetiketter";
  if(s=="Inflection labels") return "Böjningsetiketter";
  if(s=="Acceptability labels") return "Acceptansangivelser";
  if(s=="Sources") return "Källor";
  if(s=="Collections") return "Samlingar";
  if(s=="Tags") return "xx";
  if(s=="Extranets") return "Extranät";
  if(s=="Name and blurb") return "Namn och förlagstext";
  if(s=="Features") return "xx";
  if(s=="Languages") return "Språk";
  if(s=="Publishing") return "Publicering";
  if(s=="Change the termbase's URL") return "Ändra termbankens URL";
  if(s=="Delete the termbase") return "Radera termbanken";
  if(s=="TITLE") return "xx";
  if(s=="SUBDOMAINS") return "xx";
  if(s=="abbreviation") return "xx";
  if(s=="LANGUAGES") return "SPRÅK";
  if(s=="select all") return "xx";
  if(s=="unselect all") return "xx";
  if(s=="PRIORITY") return "xx";
  if(s=="high") return "xx";
  if(s=="medium") return "xx";
  if(s=="low") return "xx";
  if(s=="USERS") return "ANVÄNDARE";
  if(s=="e-mail address") return "xx";
  if(s=="user") return "xx";
  if(s=="Alphabetical order") return "Alfabetisk sorteringsordning";
  if(s=="Similar terms (click to insert)") return "xx";
  if(s=="Other entries that share this term") return "xx";
  if(s=="stop sharing") return "xx";
  if(s=="Change checking status to") return "xx";
  if(s=="Change publishing status to") return "xx";
  if(s=="Add to extranet") return "xx";
  if(s=="Remove from extranet") return "xx";
  if(s=="checked") return "kontrollerad";
  if(s=="not checked") return "inte kontrollerad";
  if(s=="publishable") return "publiceringsbar";
  if(s=="hidden") return "dold";
  if(s=="CHECKED") return "xx";
  if(s=="NOT CHECKED") return "INTE KONTROLLERAD";
  if(s=="PUBLISHABLE") return "PUBLICERBAR";
  if(s=="HIDDEN") return "xx";
  if(s=="non-essential") return "xx";
  if(s=="STATUS") return "xx";
  if(s=="live") return "xx";
  if(s=="not live") return "xx";
  if(s=="any clarification or no clarification") return "xx";
  if(s=="any clarification") return "xx";
  if(s=="no clarification") return "xx";
  if(s=="clarification containing...") return "xx";
  if(s=="any intro or no intro") return "xx";
  if(s=="any intro") return "xx";
  if(s=="no intro") return "xx";
  if(s=="intro containing...") return "xx";
  if(s=="any definition or no definition") return "xx";
  if(s=="any definition") return "xx";
  if(s=="no definition") return "xx";
  if(s=="definition containing...") return "xx";
  if(s=="any example or no example") return "xx";
  if(s=="any example") return "xx";
  if(s=="no example") return "xx";
  if(s=="example containing...") return "xx";
  if(s=="Automatic changes") return "Automatiska ändringar";
  if(s=="NAME") return "xx";
  if(s=="BLURB") return "xx";
  if(s=="level") return "xx";
  if(s=="reader") return "xx";
  if(s=="editor") return "xx";
  if(s=="creator") return "xx";
  if(s=="administrator") return "xx";
  if(s=="configurator") return "xx";
  if(s=="no change") return "ingen ändring";
  if(s=="change to 'not checked'") return "ändra till ”inte kontrollerad”";
  if(s=="change to 'hidden'") return "ändra till ”dold”";
  if(s=="change to 'not checked' and 'hidden'") return "ändra till ”inte kontrollerad” och ”dold”";
  if(s=="LAST SEEN") return "xx";
  if(s=="NEVER") return "xx";
  if(s=="No termbases") return "xx";
  if(s=="language") return "xx";
  if(s=="major") return "xx";
  if(s=="minor") return "xx";
  if(s=="role") return "xx";
  if(s=="title") return "xx";
  if(s=="ACCESS LEVEL") return "xx";
  if(s=="LICENCE") return "xx";
  if(s=="private") return "xx";
  if(s=="public") return "xx";
  if(s=="trigger_dateStampChange") return "datum ändrat";
  if(s=="trigger_domainAdd") return "domän tillagd"; 
  if(s=="trigger_domainRemove") return "domän borttagen";
  if(s=="trigger_domainReorder") return "domäner omsorterade";
  if(s=="trigger_domainChange") return "domän ändrad";
  if(s=="trigger_subdomainChange") return "underdomän ändrad";
  if(s=="trigger_desigAdd") return "term tillagd";
  if(s=="trigger_desigRemove") return "term borttagen";
  if(s=="trigger_desigReorder") return "termer omsorterade";
  if(s=="trigger_desigClarifChange") return "förtydligande tillagt";
  if(s=="trigger_desigAcceptChange") return "acceptans tillagd";
  if(s=="trigger_termLangChange") return "termens språk tillagt";
  if(s=="trigger_termWordingChange") return "termformulering tillagd";
  if(s=="trigger_termInflectAdd") return "böjningsform tillagd";
  if(s=="trigger_termInflectRemove") return "böjningsform borttagen";
  if(s=="trigger_termInflectReorder") return "böjningsformer omsorterade";
  if(s=="trigger_termInflectLabelChange") return "angivelse av böjningsform ändrad"; 
  if(s=="trigger_termInflectTextChange") return "formulering av böjningsform ändrad";
  if(s=="trigger_termAnnotAdd") return "termannotering tillagd";
  if(s=="trigger_termAnnotRemove") return "termannotering borttagen";
  if(s=="trigger_termAnnotReorder") return "termannoteringar omsorterade";
  if(s=="trigger_termAnnotPositionChange") return "position för termannoering ändrad";
  if(s=="trigger_termAnnotLabelChange") return "termannotateringsetikett ändrad";
  if(s=="trigger_introChange") return "intro ändrat";
  if(s=="trigger_definitionAdd") return "definition tillagd";
  if(s=="trigger_definitionRemove") return "definition borttagen";
  if(s=="trigger_definitionReorder") return "definitioner omsorterade";
  if(s=="trigger_definitionTextChange") return "definitionen omformulerad";
  if(s=="trigger_exampleAdd") return "exempel tillagt";
  if(s=="trigger_exampleRemove") return "exempel borttaget";
  if(s=="trigger_exampleReorder") return "exempel omsorterade";
  if(s=="trigger_exampleTextAdd") return "exempelmening tillagd";
  if(s=="trigger_exampleTextRemove") return "exempelmening borttagen";
  if(s=="trigger_exampleTextReorder") return "exempelmeningar omsorterade";
  if(s=="trigger_exampleTextChange") return "exempelmening omformulerad";
  if(s=="trigger_collectionAdd") return "samling tillagd";
  if(s=="trigger_collectionRemove") return "samling borttagen";
  if(s=="trigger_collectionReorder") return "samlingar omsorterade";
  if(s=="trigger_collectionChange") return "samling ändrad";
  if(s=="trigger_extranetAdd") return "extranät tillagt";
  if(s=="trigger_extranetRemove") return "extranät borttaget";
  if(s=="trigger_extranetReorder") return "extranät omsorterade";
  if(s=="trigger_extranetChange") return "extranät ändrat";
  if(s=="trigger_sourceAdd") return "källa tillagd";
  if(s=="trigger_sourceRemove") return "källa borttagen";
  if(s=="trigger_sourceReorder") return "källor omsorterade";
  if(s=="trigger_sourceChange") return "källa ändrad";
  if(s=="trigger_nonessentialChange") return "synlighet ändrad";
  if(s=="(blank)") return "xx";
  if(s=="Simple Multilingual Termbase") return "xx";
  if(s=="Simple Bilingual Termbase") return "xx";
  if(s=="Simple Monolingual Termbase") return "xx";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "xx";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "xx";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "xx";
  if(s=="Your termbase is ready.") return "xx";
  if(s=="TERM OF THE DAY") return "DAGENS TERM";
  if(s=="set to next available date") return "ange närmast tillgängliga datum";
  if(s=="Display from") return "Visa från";
  if(s=="Display until") return "Visa till";
  if(s=="News and announcements") return "Nyheter och meddelanden";
  if(s=="Create your account") return "xx";
  if(s=="Reset your password") return "xx";
  if(s=="Terminologue signup") return "xx";
  if(s=="Please follow the link below to create your Terminologue account:") return "xx";
  if(s=="Terminologue password reset") return "xx";
  if(s=="Please follow the link below to reset your Terminologue password:") return "xx";
  if(s=="This page is only available in English.") return "xx";
  if(s=="DRAFTING STATUS") return "UTKASTSTATUS";
  if(s=="draft entry") return "utkast till begreppspost";
  if(s=="finished entry") return "färdig begreppspost";
  if(s=="DRAFT") return "xx";
  if(s=="FINISHED") return "KLAR";
  if(s=="any drafting status") return "xx";
  if(s=="Prefabricated comments") return "Färdigförberedda kommentarer";
  if(s=="NOTES") return "xx";
  if(s=="note") return "xx";
  if(s=="NOT") return "xx";
  if(s=="with or without notes") return "xx";
  if(s=="with a note") return "xx";
  if(s=="with a note containing...") return "xx";
  if(s=="without notes") return "xx";
  if(s=="any type") return "xx";
  if(s=="private note, not shown on extranets") return "xx";
  if(s=="private note, shown on extranets") return "xx";
  if(s=="public note") return "xx";
  if(s=="Note types") return "Anmärkningstyper";
  if(s=="LEVEL") return "xx";
  if(s=="with a comment") return "xx";
  if(s=="with a comment contaning...") return "xx";

  if(s=="TBX export") return "TBX-export";
  if(s=="TBX import") return "TBX-import";
  if(s=="Empty the termbase") return "Töm termbanken";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "xx";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "xx";
  if(s=="RELATED TERMS") return "xx";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
