function L(s, gloss){
  if(s=="only") return function(s){
    return "Yalnızca "+s;
  };
  if(s=="READ-ONLY") return "YAZMA KORUMALI";
  if(s=="Editing") return "Düzenleme";
  if(s=="Dublin City University") return "Dublin City University";
  if(s=="Log out") return "Çıkış";
  if(s=="Change your password") return "Şifre değiştir";
  if(s=="Registered user login") return "Kayıtlı kullanıcılar için giriş";
  if(s=="Get an account") return "Hesap oluştur";
  if(s=="Forgot your password?") return "Şifremi unuttum";
  if(s=="E-mail address") return "E-Posta adresi";
  if(s=="Password") return "Şifre";
  if(s=="Log in") return "Giriş";
  if(s=="Your termbases") return "Terim tabanlarınız";
  if(s=="You have no termbases yet.") return "Henüz bir terim tabanınız mevcut değil.";
  if(s=="Create a termbase") return "Terim tabanı oluştur";
  if(s=="Administration") return "Yönetim";
  if(s=="Users") return "Kullanıcılar";
  if(s=="Termbases") return "Terim tabanları";
  if(s=="smart search") return "akıllı arama";
  if(s=="complete term") return "tam sözcük";
  if(s=="start of term") return "sözcük başı";
  if(s=="end of term") return "sözcük sonu";
  if(s=="any part of term") return "sözcük parçası";
  if(s=="any part except start or end") return "baş ve son hariç herhangi bir bölümü";
  if(s=="search in all languages") return "tüm dillerde ara";
  if(s=="Configuration") return "Yapılandırma";
  if(s=="ADMIN") return "YÖNETİM";
  if(s=="TRM") return "TERİM";
  if(s=="DOM") return "ALAN";
  if(s=="DEF") return "TANIM";
  if(s=="XMPL") return "TANIK";
  if(s=="CHECKING STATUS") return "STATÜYÜ KONTROL ET";
  if(s=="PUBLISHING STATUS") return "YAYIN STATÜSÜ";
  if(s=="TERMS") return "TERİMLER";
  if(s=="DOMAINS") return "ALANLAR";
  if(s=="term") return "terim";
  if(s=="clarification") return "açıklama";
  if(s=="acceptability") return "kabul";
  if(s=="source") return "kaynak";
  if(s=="inflected form") return "çekimlenmiş biçim";
  if(s=="annotation") return "açıklama";
  if(s=="domain") return "alan";
  if(s=="part of speech") return "sözcük türü";
  if(s=="inflection") return "çekim";
  if(s=="language of origin") return "köken dil";
  if(s=="symbol") return "sembol";
  if(s=="trademark") return "marka";
  if(s=="registered trademark") return "kayıtlı marka";
  if(s=="proper noun") return "özel ad";
  if(s=="formatting") return "formatlama";
  if(s=="italic") return "eğik";
  if(s=="Created") return "Oluşturuldu";
  if(s=="Changed") return "Değiştirildi";
  if(s=="Deleted") return "Silindi";
  if(s=="Bulk-deleted") return "Hepsi silindi";
  if(s=="while uploading") return "yüklenirken";
  if(s=="By") return "Kim";
  if(s=="When") return "Ne zaman";
  if(s=="any checking status") return "herhangi bir kontrol statüsü";
  if(s=="any publishing status") return "herhangi bir yayın statüsü";
  if(s=="any language") return "herhangi bir dil";
  if(s=="any acceptability or no acceptability") return "herhangi bir kabul veya kabul yok";
  if(s=="any acceptability") return "herhangi bir kabul";
  if(s=="no acceptability") return "kabul edilmiyor";
  if(s=="any domain or no domain") return "herhangi bir konu veya konu yok";
  if(s=="any domain") return "herhangi bir konu";
  if(s=="no domain") return "konu yok";
  if(s=="LAST MAJOR UPDATE") return "SON ÖNEMLİ GÜNCELLEME";
  if(s=="set to today") return "bugünkü tarihe ayarla";
  if(s=="Invalid e-mail address or password.") return "Geçersiz E-Posta adresi veya geçersiz şifre.";
  if(s=="INTR") return "AYRIM";
  if(s=="COLL") return "KOL.";
  if(s=="INTROS") return "AYIRIMLAR";
  if(s=="DEFINITIONS") return "TANIMLAR";
  if(s=="EXAMPLES") return "ÖRNEKLER";
  if(s=="COLLECTIONS") return "KOLEKSİYONLAR";
  if(s=="definition") return "tanım";
  if(s=="example") return "örnek";
  if(s=="sentence") return "tümce";
  if(s=="collection") return "koleksiyon";
  if(s=="any collection or no collection") return "herhangi bir koleksiyon veya koleksiyon yok";
  if(s=="any collection") return "herhangi bir koleksiyon";
  if(s=="no collection") return "koleksiyon yok";
  if(s=="comments") return "yorumlar";
  if(s=="with or without comments") return "yorumlu veya yorumsuz";
  if(s=="with comments") return "yorumlu";
  if(s=="without comments") return "yorumsuz";
  if(s=="my comments") return "yorumlarım";
  if(s=="with or without my comments") return "yorumlarım var veya yok";
  if(s=="with my comments") return "yorumlarım var";
  if(s=="without my comments") return "yorumlarım yok";
  if(s=="other people's comments") return "başkalarının yorumları";
  if(s=="with or without other people's comments") return "başkalarının yorumları var veya yok";
  if(s=="with other people's comments") return "başkalarının yorumları var";
  if(s=="without other people's comments") return "başkalarının yorumları yok";
  if(s=="EXTRANET") return "DIŞ AĞ";
  if(s=="EXT") return "DIŞ";
  if(s=="EXTRANETS") return "DIŞ AĞLAR";
  if(s=="extranet") return "dış ağ";
  if(s=="any extranet or no extranet") return "herhangi bir dış ağ veya dış ağ yok";
  if(s=="any extranet") return "herhangi bir dış ağ";
  if(s=="no extranet") return "dış ağ yok";
  if(s=="sorting language") return "sıralama dili";
  if(s=="Create mutual cross-references") return "Karşılıklı referans oluştur";
  if(s=="Remove mutual cross-references") return "Karşılıklı referansları sil";
  if(s=="Merge into a single entry") return "Tek kayıtta birleştir";
  if(s=="SEE ALSO") return "AYR. BK.";
  if(s=="add to worklist") return "çalışma listesine ekle";
  if(s=="Domains") return "Alanlar";
  if(s=="Part-of-speech labels") return "Sözcük türü etiketleri";
  if(s=="Inflection labels") return "Çekim etiketleri";
  if(s=="Acceptability labels") return "Kabul etiketleri";
  if(s=="Sources") return "Kaynaklar";
  if(s=="Collections") return "Koleksiyonlar";
  if(s=="Tags") return "Etiketler";
  if(s=="Extranets") return "Dış ağlar";
  if(s=="Name and blurb") return "Ad ve tanıtım metni";
  if(s=="Features") return "Özellikler";
  if(s=="Languages") return "Diller";
  if(s=="Publishing") return "Yayınlama";
  if(s=="Change the termbase's URL") return "Terim tabanının URL adresinin değiştir";
  if(s=="Delete the termbase") return "Terim tabanını sil";
  if(s=="TITLE") return "BAŞLIK";
  if(s=="abbreviation") return "kısaltma";
  if(s=="LANGUAGES") return "DİLLER";
  if(s=="select all") return "Hepsini seç";
  if(s=="unselect all") return "Hepsini seçme";
  if(s=="PRIORITY") return "ÖNCELİK";
  if(s=="high") return "yüksek";
  if(s=="medium") return "orta";
  if(s=="low") return "düşük";
  if(s=="USERS") return "KULLANICI";
  if(s=="e-mail address") return "E-Posta adresi";
  if(s=="user") return "kullanıcı";
  if(s=="Alphabetical order") return "Alfabetik sıralama";
  if(s=="Similar terms (click to insert)") return "Benzer kavramlar (eklemek için tıklayın)";
  if(s=="Other entries that share this term") return "Bu kavramı paylaşan diğer kayıtlar";
  if(s=="stop sharing") return "Paylaşımı sonlandır";
  if(s=="Change checking status to") return "Kontrol statüsünü değiştir:";
  if(s=="Change publishing status to") return "Yayın statüsünü değiştir:";
  if(s=="Add to extranet") return "Dış ağa ekle";
  if(s=="Remove from extranet") return "Dış ağdan çıkar";
  if(s=="checked") return "kontrol edildi";
  if(s=="not checked") return "kontrol edilmedi";
  if(s=="publishable") return "yayınlanabilir";
  if(s=="hidden") return "gizli";
  if(s=="CHECKED") return "KONTROL EDİLDİ";
  if(s=="NOT CHECKED") return "KONTROL EDİLMEDİ";
  if(s=="PUBLISHABLE") return "YAYINLANABİLİR";
  if(s=="HIDDEN") return "GİZLİ";
  if(s=="non-essential") return "gerekli değil";
  if(s=="STATUS") return "STATÜSÜ";
  if(s=="live") return "canlı";
  if(s=="not live") return "canlı değil";
  if(s=="any clarification or no clarification") return "herhangi bir açıklama veya açıklama yok";
  if(s=="any clarification") return "herhangi bir açıklama";
  if(s=="no clarification") return "açıklama yok";
  if(s=="clarification containing...") return "açıklama şunları içeriyor:";
  if(s=="any intro or no intro") return "herhangi bir ayrım veya ayrım yok";
  if(s=="any intro") return "herhangi bir ayrım";
  if(s=="no intro") return "ayrım yok";
  if(s=="intro containing...") return "ayrım şunları içeriyor:";
  if(s=="any definition or no definition") return "herhangi bir tanım veya tanım yok";
  if(s=="any definition") return "herhangi bir tanım";
  if(s=="no definition") return "tanım yok";
  if(s=="definition containing...") return "tanım şunları içeriyor:";
  if(s=="any example or no example") return "herhangi bir örnek veya örnek yok";
  if(s=="any example") return "herhangi bir örnek";
  if(s=="no example") return "örnek yok";
  if(s=="example containing...") return "örnek şunları içeriyor:";
  if(s=="Automatic changes") return "Otomatik değişiklikler";
  if(s=="NAME") return "ADI";
  if(s=="BLURB") return "TANITIM METNİ";
  if(s=="level") return "düzey";
  if(s=="reader") return "okur";
  if(s=="editor") return "editör";
  if(s=="creator") return "oluşturucu";
  if(s=="administrator") return "yönetici";
  if(s=="configurator") return "düzenleyici";
  if(s=="no change") return "değişiklik yok";
  if(s=="change to 'not checked'") return "'kontrol edilmedi' değişikliği";
  if(s=="change to 'hidden'") return "'gizli' değişikliği";
  if(s=="change to 'not checked' and 'hidden'") return "'kontrol edilmedi' ve 'gizli' değişikliği";
  if(s=="LAST SEEN") return "SON GİRİŞ";
  if(s=="NEVER") return "HİÇBİR ZAMAN";
  if(s=="No termbases") return "Terim bankası yok";
  if(s=="language") return "dil";
  if(s=="major") return "önemli";
  if(s=="minor") return "önemsiz";
  if(s=="role") return "rol";
  if(s=="title") return "başlık";
  if(s=="ACCESS LEVEL") return "ERİŞİM DÜZEYİ";
  if(s=="LICENCE") return "LİSANS";
  if(s=="private") return "özel";
  if(s=="public") return "genel";
  if(s=="trigger_dateStampChange") return "tarih değiştirildi";
  if(s=="trigger_domainAdd") return "konu eklendi";
  if(s=="trigger_domainRemove") return "konu çıkarıldı";
  if(s=="trigger_domainReorder") return "konu yeniden sıralandı";
  if(s=="trigger_domainChange") return "konu değiştirildi";
  if(s=="trigger_desigAdd") return "kavram eklendi";
  if(s=="trigger_desigRemove") return "kavram silindi";
  if(s=="trigger_desigReorder") return "kavramlar yeniden sıralandı";
  if(s=="trigger_desigClarifChange") return "açıklama değiştirildi";
  if(s=="trigger_desigAcceptChange") return "kabul değiştirildi";
  if(s=="trigger_termLangChange") return "kavram dili değiştirildi";
  if(s=="trigger_termWordingChange") return "kavramın belirtimi değiştirildi";
  if(s=="trigger_termInflectAdd") return "çekimli biçim eklendi";
  if(s=="trigger_termInflectRemove") return "çekimli biçim silindi";
  if(s=="trigger_termInflectReorder") return "çekimli biçimler yeniden sıralandı";
  if(s=="trigger_termInflectLabelChange") return "çekimli biçimlerin etiketi değiştirildi";
  if(s=="trigger_termInflectTextChange") return "çekimli biçimlerin metni değiştirildi";
  if(s=="trigger_termAnnotAdd") return "Kavrama ilişkin not değiştirildi";
  if(s=="trigger_termAnnotRemove") return "Kavrama ilişkin not silindi";
  if(s=="trigger_termAnnotReorder") return "Kavrama ilişkin notlar yeniden sıralandı";
  if(s=="trigger_termAnnotPositionChange") return "Kavrama ilişkin notun yeri değiştirildi";
  if(s=="trigger_termAnnotLabelChange") return "Kavrama ilişkin notun etiketi değiştirildi";
  if(s=="trigger_introChange") return "ayrım değiştirildi";
  if(s=="trigger_definitionAdd") return "tanım eklendi";
  if(s=="trigger_definitionRemove") return "tanım silindi";
  if(s=="trigger_definitionReorder") return "tanımlar yeniden sıralandı";
  if(s=="trigger_definitionTextChange") return "tanım metni değiştirildi";
  if(s=="trigger_exampleAdd") return "örnek eklendi";
  if(s=="trigger_exampleRemove") return "örnek silindi";
  if(s=="trigger_exampleReorder") return "örnekler yeniden sıralandı";
  if(s=="trigger_exampleTextAdd") return "örnek tümce eklendi";
  if(s=="trigger_exampleTextRemove") return "örnek tümce silindi";
  if(s=="trigger_exampleTextReorder") return "örnek tümceler yeniden sıralandı";
  if(s=="trigger_exampleTextChange") return "örnek cümlenin biçimi değiştirildi";
  if(s=="trigger_collectionAdd") return "koleksiyon eklendi";
  if(s=="trigger_collectionRemove") return "koleksiyon değiştirildi";
  if(s=="trigger_collectionReorder") return "koleksiyonlar yeniden sıralandı";
  if(s=="trigger_collectionChange") return "koleksiyon değiştirildi";
  if(s=="trigger_extranetAdd") return "dış ağ eklendi";
  if(s=="trigger_extranetRemove") return "dış ağ silindi";
  if(s=="trigger_extranetReorder") return "dış ağlar yeniden sıralandı";
  if(s=="trigger_extranetChange") return "dış ağ değiştirildi";
  if(s=="trigger_sourceAdd") return "kaynak eklendi";
  if(s=="trigger_sourceRemove") return "kaynak silindi";
  if(s=="trigger_sourceReorder") return "kaynaklar yeniden sıralandı";
  if(s=="trigger_sourceChange") return "kaynak değiştirildi";
  if(s=="trigger_nonessentialChange") return "önemsiz değişiklik yapıldı";
  if(s=="(blank)") return "(boş)";
  if(s=="Simple Multilingual Termbase") return "Basit Çok Dilli Terim Tabanı";
  if(s=="Simple Bilingual Termbase") return "Basit İki Dilli Terim Tabanı";
  if(s=="Simple Monolingual Termbase") return "Basit Tek Dilli Terim Tabanı";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "Örneğin \"Spor Terimleri Sözlüğü\" gibi insanlar tarafından kolayca okunabilecek bir başlık girin. Bunu daha sonra değiştirebilirsiniz.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "Bu sizin terim tabanınızın Internet üzerindeki adresidir. Bu adresi daha sonra da değiştirebilirsiniz.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "Başlangıç için buradan bir şablon seçebilirsiniz. Şablonlar birkaç örnek kayıtla birlikte gelir. Bunları değiştirebilir veya silebilir ve şablonu özelleştirebilirsiniz.";
  if(s=="Your termbase is ready.") return "Terim tabanınız şimdi hazır.";
  if(s=="TERM OF THE DAY") return "GÜNÜN TERİMİ";
  if(s=="set to next available date") return "ilk boş güne ayarla";
  if(s=="Display from") return "Şunda itibaren";
  if(s=="Display until") return "Şuna kadar";
  if(s=="News and announcements") return "Duyuruları ve bildirimleri göster";
  if(s=="Create your account") return "Hesap oluştur";
  if(s=="Reset your password") return "Şifrenizi sıfırlayın";
  if(s=="Terminologue signup") return "Terminologue'a giriş yapın";
  if(s=="Please follow the link below to create your Terminologue account:") return "Terminologue üzerinde hesap açmak için lütfen şu bağlantıyı izleyin:";
  if(s=="Terminologue password reset") return "Terminologue şifresini sıfırlayın";
  if(s=="Please follow the link below to reset your Terminologue password:") return "Terminologue şifrenizi sıfırlamak için lütfen şu bağlantıyı izleyin:";
  if(s=="This page is only available in English.") return "Su sayfa yalnızca İngilizce mevcut.";
  if(s=="DRAFTING STATUS") return "TASLAK STATÜSÜ";
  if(s=="draft entry") return "bir kayıt taslağı";
  if(s=="finished entry") return "tamamlanmış kayıt";
  if(s=="DRAFT") return "TASLAK";
  if(s=="FINISHED") return "TAMAMLANMIŞ";
  if(s=="any drafting status") return "herhangi bir taslak statüsü";
  if(s=="Prefabricated comments") return "Hazır yorumlar";
  if(s=="NOTES") return "NOTLAR";
  if(s=="note") return "not";
  if(s=="NOT") return "NOT";
  if(s=="with or without notes") return "notlu veya notsuz";
  if(s=="with a note") return "bir notla birlikte";
  if(s=="with a note containing...") return "not şöyle:";
  if(s=="without notes") return "not yok";
  if(s=="any type") return "herhangi bir tür";
  if(s=="private note, not shown on extranets") return "kişiye özel, dış ağlarda görülmeyecek not";
  if(s=="private note, shown on extranets") return "kişiye özel, dış ağlarda görülecek not";
  if(s=="public note") return "kamuya açık not";
  if(s=="Note types") return "Not türleri";
  if(s=="LEVEL") return "DÜZEY";
  if(s=="with a comment") return "bir yorumla birlikte";
  if(s=="with a comment containing...") return "yorum şöyle:";
  if(s=="TBX export") return "TBX dışa aktarma";
  if(s=="TBX import") return "TBX içe aktarma";
  if(s=="Empty the termbase") return "Terim tabanını boşalt";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "Şimdi çok dikkatli olun! Terim bankasını silmek üzeresiniz. Bu işlemin geri alınması mümkün değildir.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "Şimdi çok dikkatli olun! Tüm kayıtları ve bunların geçmişini silmek üzeresiniz. Bu işlemin geri alınması mümkün değildir.";
  if(s=="RELATED TERMS") return "İLİŞKİLİ TERİMLER";
  if(s=="Your termbase at a glance") return "Terim tabanınızın özeti";
  if(s=="Number of entries") return "Kayıt sayısı";
  if(s=="Number of items in history log") return "Geçmiş günlüğündeki öğe sayısı";
  if(s=="Your termbase is stored in the file %F") return "Terim bankanız %F adlı dosyada kayıtlıdır";
  if(s=="File size") return "Dosya büyüklüğü";
  if(s=="Download %F") return "%F indir";
  if(s=="Upload %F") return "%F yükle";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "Yüklediğiniz dosyanın geçerli bir Terminologue terim tabanı olduğundan emin olun. Başka bir şey yüklerseniz terim tabanınıza onarılamaz bir zarar verirsiniz.";
  if(s=="PARENT") return "PAYDAŞ";
  if(s=="no parent") return "paydaş değil";
  if(s=="excluding subdomains") return "alt alanlar yok";
  if(s=="including subdomains") return "alt alanlar dâhil";
  if(s=="the entry has this domain") return "kayıt bu konuya sahip";
  if(s=="the entry has only this domain") return "kayıt yalnızca bu konuya sahip";
  if(s=="the entry has not only this domain") return "kayıt yalnızca bu konuya sahip değil";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "Dikkat! Terim tabanından çıkarsınız erişiminizi kaybedersiniz.";
  if(s=="Leave this termbase") return "Terim tabanından ayrıl";
  if(s=="IMG") return "GÖR.";
  if(s=="IMAGES") return "GÖRÜNTÜLER";
  if(s=="image") return "görüntü";
  if(s=="credits") return "yazar/kaynak";
  if(s=="link to source") return "kaynağa bağlantı";
  if(s=="The file is too large. The maximum allowed size is $1 bytes.") return "Bu dosya çok büyük. En büyük dosya en çok $1 Byte olabilir.";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
