function L(s, gloss){
  if(s=="only") return function(s){
    return "僅"+s;
  };
  if(s=="READ-ONLY") return "唯讀";
  if(s=="Editing") return "編輯";
  if(s=="Dublin City University") return "都柏林城市大學";
  if(s=="Log out") return "登出";
  if(s=="Change your password") return "變更密碼";
  if(s=="Registered user login") return "已建立帳號的使用者登入";
  if(s=="Get an account") return "取得帳號";
  if(s=="Forgot your password?") return "忘記密碼？";
  if(s=="E-mail address") return "電子郵件地址";
  if(s=="Password") return "密碼";
  if(s=="Log in") return "登入";
  if(s=="Your termbases") return "您的術語庫";
  if(s=="You have no termbases yet.") return "您目前沒有術語庫";
  if(s=="Create a termbase") return "創建術語庫";
  if(s=="Administration") return "管理";
  if(s=="Users") return "使用者";
  if(s=="Termbases") return "術語庫";
  if(s=="smart search") return "智慧搜尋";
  if(s=="complete term") return "完整術語";
  if(s=="start of term") return "術語起頭";
  if(s=="end of term") return "術語結尾";
  if(s=="any part of term") return "術語任何部分";
  if(s=="any part except start or end") return "除了起頭或結尾";
  if(s=="search in all languages") return "搜尋所有語言";
  if(s=="Configuration") return "配置";
  if(s=="ADMIN") return "管理";
  if(s=="TRM") return "術語";
  if(s=="DOM") return "語域";
  if(s=="DEF") return "定義";
  if(s=="XMPL") return "範例";
  if(s=="CHECKING STATUS") return "查核狀態";
  if(s=="PUBLISHING STATUS") return "發布狀態";
  if(s=="TERMS") return "術語";
  if(s=="DOMAINS") return "語域";
  if(s=="term") return "術語";
  if(s=="clarification") return "說明";
  if(s=="acceptability") return "接受度";
  if(s=="source") return "來源";
  if(s=="inflected form") return "屈折形式";
  if(s=="annotation") return "標註";
  if(s=="domain") return "語域";
  if(s=="part of speech") return "詞性";
  if(s=="inflection") return "屈折";
  if(s=="language of origin") return "語言發源";
  if(s=="symbol") return "符號 標記象徵";
  if(s=="trademark") return "商標";
  if(s=="registered trademark") return "註冊商標";
  if(s=="proper noun") return "專有名詞";
  if(s=="formatting") return "格式化";
  if(s=="italic") return "斜體";
  if(s=="Created") return "已建立";
  if(s=="Changed") return "已變更";
  if(s=="Deleted") return "已刪除";
  if(s=="Bulk-deleted") return "大量刪除";
  if(s=="while uploading") return "上傳中";
  if(s=="By") return "在此之前：";
  if(s=="When") return "這個時候：";
  if(s=="any checking status") return "任何查核狀態";
  if(s=="any publishing status") return "任何發布狀態";
  if(s=="any language") return "任何語言";
  if(s=="any acceptability or no acceptability") return "任何接受度或無接受度";
  if(s=="any acceptability") return "任何接受度";
  if(s=="no acceptability") return "無接受度";
  if(s=="any domain or no domain") return "任何語域或無語域";
  if(s=="any domain") return "任何語域";
  if(s=="no domain") return "無語域";
  if(s=="LAST MAJOR UPDATE") return "上次重大更新";
  if(s=="set to today") return "設為今天";
  if(s=="Invalid e-mail address or password.") return "無效的電子郵件地址或密碼";
  if(s=="INTR") return "介紹";
  if(s=="COLL") return "集合";
  if(s=="INTROS") return "介紹";
  if(s=="DEFINITIONS") return "定義";
  if(s=="EXAMPLES") return "範例";
  if(s=="COLLECTIONS") return "集合";
  if(s=="definition") return "定義";
  if(s=="example") return "範例";
  if(s=="sentence") return "語句";
  if(s=="collection") return "集合";
  if(s=="any collection or no collection") return "任何集合或無集合";
  if(s=="any collection") return "任何集合";
  if(s=="no collection") return "無集合";
  if(s=="comments") return "註釋";
  if(s=="with or without comments") return "有無註釋";
  if(s=="with comments") return "有註釋";
  if(s=="without comments") return "無註釋";
  if(s=="my comments") return "我的註釋";
  if(s=="with or without my comments") return "有無我的註釋";
  if(s=="with my comments") return "有我的註釋";
  if(s=="without my comments") return "沒有我的註釋";
  if(s=="other people's comments") return "別人的註釋";
  if(s=="with or without other people's comments") return "有無別人的註釋";
  if(s=="with other people's comments") return "有別人的註釋";
  if(s=="without other people's comments") return "沒有別人的註釋";
  if(s=="EXTRANET") return "外部網路";
  if(s=="EXT") return "外部網路";
  if(s=="EXTRANETS") return "外部網路";
  if(s=="extranet") return "外部網路";
  if(s=="any extranet or no extranet") return "任何外部網路或無外部網路";
  if(s=="any extranet") return "任何外部網路";
  if(s=="no extranet") return "無外部網路";
  if(s=="sorting language") return "排序語言中";
  if(s=="Create mutual cross-references") return "建立相互交叉參考";
  if(s=="Remove mutual cross-references") return "移除相互交叉參考";
  if(s=="Merge into a single entry") return "合併為一個條目";
  if(s=="SEE ALSO") return "參見";
  if(s=="add to worklist") return "加進工作清單";
  if(s=="Domains") return "無語";
  if(s=="Part-of-speech labels") return "詞性標籤";
  if(s=="Inflection labels") return "屈折標籤";
  if(s=="Acceptability labels") return "接受度標籤";
  if(s=="Sources") return "來源";
  if(s=="Collections") return "集合";
  if(s=="Tags") return "標籤";
  if(s=="Extranets") return "外部網路";
  if(s=="Name and blurb") return "名稱與簡介";
  if(s=="Features") return "功能";
  if(s=="Languages") return "語言";
  if(s=="Publishing") return "發布";
  if(s=="Change the termbase's URL") return "變更術語庫URL";
  if(s=="Delete the termbase") return "刪除術語庫";
  if(s=="TITLE") return "標題";
  if(s=="abbreviation") return "縮寫";
  if(s=="LANGUAGES") return "語言";
  if(s=="select all") return "全部選取";
  if(s=="unselect all") return "全部取消選取";
  if(s=="PRIORITY") return "重要性";
  if(s=="high") return "高";
  if(s=="medium") return "中";
  if(s=="low") return "低";
  if(s=="USERS") return "使用者";
  if(s=="e-mail address") return "電子郵件地址";
  if(s=="user") return "使用者";
  if(s=="Alphabetical order") return "依字母順序";
  if(s=="Similar terms (click to insert)") return "類似術語（點選插入）";
  if(s=="Other entries that share this term") return "共用此術語的其他條目";
  if(s=="stop sharing") return "停止共用";
  if(s=="Change checking status to") return "變更查核狀態為";
  if(s=="Change publishing status to") return "變更發布狀態為";
  if(s=="Add to extranet") return "新增至外部網路";
  if(s=="Remove from extranet") return "從外部網路移除";
  if(s=="checked") return "已查核";
  if(s=="not checked") return "未查核";
  if(s=="publishable") return "可發布";
  if(s=="hidden") return "隱藏";
  if(s=="CHECKED") return "已查核";
  if(s=="NOT CHECKED") return "未查核";
  if(s=="PUBLISHABLE") return "可發布";
  if(s=="HIDDEN") return "隱藏";
  if(s=="non-essential") return "非必要";
  if(s=="STATUS") return "狀態";
  if(s=="live") return "啟用";
  if(s=="not live") return "停用";
  if(s=="any clarification or no clarification") return "任何說明或無說明";
  if(s=="any clarification") return "任何說明";
  if(s=="no clarification") return "無說明";
  if(s=="clarification containing...") return "說明包含...";
  if(s=="any intro or no intro") return "任何介紹或無介紹";
  if(s=="any intro") return "任何介紹";
  if(s=="no intro") return "無介紹";
  if(s=="intro containing...") return "介紹包含...";
  if(s=="any definition or no definition") return "任何定義或無定義";
  if(s=="any definition") return "任何定義";
  if(s=="no definition") return "無定義";
  if(s=="definition containing...") return "定義包含...";
  if(s=="any example or no example") return "任何範例或無範例";
  if(s=="any example") return "任何範例";
  if(s=="no example") return "無範例";
  if(s=="example containing...") return "範例包含...";
  if(s=="Automatic changes") return "自動變更";
  if(s=="NAME") return "名稱";
  if(s=="BLURB") return "簡介";
  if(s=="level") return "等級";
  if(s=="reader") return "檢視者";
  if(s=="editor") return "編輯者";
  if(s=="creator") return "建立者";
  if(s=="administrator") return "管理者";
  if(s=="configurator") return "配置設定者";
  if(s=="no change") return "無變更";
  if(s=="change to 'not checked'") return "變更為「未查核」";
  if(s=="change to 'hidden'") return "變更為「隱藏」";
  if(s=="change to 'not checked' and 'hidden'") return "變更為「未查核」且「隱藏」";
  if(s=="LAST SEEN") return "最後上線時間";
  if(s=="NEVER") return "從未";
  if(s=="No termbases") return "無術語庫";
  if(s=="language") return "語言";
  if(s=="major") return "主要";
  if(s=="minor") return "次要";
  if(s=="role") return "角色";
  if(s=="title") return "標題";
  if(s=="ACCESS LEVEL") return "存取等級";
  if(s=="LICENCE") return "執照";
  if(s=="private") return "私人";
  if(s=="public") return "公開";
  if(s=="trigger_dateStampChange") return "日期已變更";
  if(s=="trigger_domainAdd") return "語域已新增";
  if(s=="trigger_domainRemove") return "語域已移除";
  if(s=="trigger_domainReorder") return "語域已重新排序";
  if(s=="trigger_domainChange") return "語域已變更";
  if(s=="trigger_desigAdd") return "術語已新增";
  if(s=="trigger_desigRemove") return "術語已移除";
  if(s=="trigger_desigReorder") return "術語已重新排序";
  if(s=="trigger_desigClarifChange") return "分類已變更";
  if(s=="trigger_desigAcceptChange") return "接受度已變更";
  if(s=="trigger_termLangChange") return "術語語言已變更";
  if(s=="trigger_termWordingChange") return "術語措辭已變更";
  if(s=="trigger_termInflectAdd") return "屈折形式已新增";
  if(s=="trigger_termInflectRemove") return "屈折形式已移除";
  if(s=="trigger_termInflectReorder") return "屈折形式已重新排序";
  if(s=="trigger_termInflectLabelChange") return "屈折形式標籤已變更";
  if(s=="trigger_termInflectTextChange") return "屈折形式措辭已變更";
  if(s=="trigger_termAnnotAdd") return "術語標註已新增";
  if(s=="trigger_termAnnotRemove") return "術語標註已移除";
  if(s=="trigger_termAnnotReorder") return "術語標註已重新排序";
  if(s=="trigger_termAnnotPositionChange") return "術語標註位置已新增";
  if(s=="trigger_termAnnotLabelChange") return "術語標註標籤已新增";
  if(s=="trigger_introChange") return "介紹已變更";
  if(s=="trigger_definitionAdd") return "定義已新增";
  if(s=="trigger_definitionRemove") return "定義已移除";
  if(s=="trigger_definitionReorder") return "定義已重新排序";
  if(s=="trigger_definitionTextChange") return "定義文字已變更";
  if(s=="trigger_exampleAdd") return "範例已新增";
  if(s=="trigger_exampleRemove") return "範例已移除";
  if(s=="trigger_exampleReorder") return "範例已重新排序";
  if(s=="trigger_exampleTextAdd") return "例句已新增";
  if(s=="trigger_exampleTextRemove") return "例句已移除";
  if(s=="trigger_exampleTextReorder") return "例句已重新排序";
  if(s=="trigger_exampleTextChange") return "例句措辭已變更";
  if(s=="trigger_collectionAdd") return "集合已新增";
  if(s=="trigger_collectionRemove") return "集合已移除";
  if(s=="trigger_collectionReorder") return "集合已重新排序";
  if(s=="trigger_collectionChange") return "集合已變更";
  if(s=="trigger_extranetAdd") return "外部網路已新增";
  if(s=="trigger_extranetRemove") return "外部網路已移除";
  if(s=="trigger_extranetReorder") return "外部網路已重新排序";
  if(s=="trigger_extranetChange") return "外部網路已變更";
  if(s=="trigger_sourceAdd") return "來源已新增";
  if(s=="trigger_sourceRemove") return "來源已移除";
  if(s=="trigger_sourceReorder") return "來源已重新排序";
  if(s=="trigger_sourceChange") return "來源已變更";
  if(s=="trigger_nonessentialChange") return "非必要性已變更";
  if(s=="(blank)") return "（空白）";
  if(s=="Simple Multilingual Termbase") return "簡易多語術語庫";
  if(s=="Simple Bilingual Termbase") return "簡易雙語術語庫";
  if(s=="Simple Monolingual Termbase") return "簡易單語術語庫";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "輸入人類可讀的標題，例如\"My Dictionary of Sports Terms\"。您可以稍後再變更此設定。";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "這將是您的術語庫在網路上的位址。您可以稍後再變更此設定。";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "您可以在此處選擇一個模板來開始。各個模板都配有一些預設的範例條目。您可以稍後再變更或刪除範例條目並自訂模板。";
  if(s=="Your termbase is ready.") return "您的術語庫已準備就緒。";
  if(s=="TERM OF THE DAY") return "今日術語";
  if(s=="set to next available date") return "設為下一個可用日期";
  if(s=="Display from") return "顯示從";
  if(s=="Display until") return "顯示到";
  if(s=="News and announcements") return "新消息與公告";
  if(s=="Create your account") return "建立您的帳號";
  if(s=="Reset your password") return "重設您的密碼";
  if(s=="Terminologue signup") return "註冊Terminologue";
  if(s=="Please follow the link below to create your Terminologue account:") return "請依下列連結來建立您的Terminologue帳號：";
  if(s=="Terminologue password reset") return "Terminologue密碼已重設";
  if(s=="Please follow the link below to reset your Terminologue password:") return "請依下列連結來重設您的Terminologue密碼：";
  if(s=="This page is only available in English.") return "此頁面僅提供英文版本";
  if(s=="DRAFTING STATUS") return "草稿狀態";
  if(s=="draft entry") return "草稿條目";
  if(s=="finished entry") return "完成條目";
  if(s=="DRAFT") return "草稿";
  if(s=="FINISHED") return "完成";
  if(s=="any drafting status") return "任何草稿狀態";
  if(s=="Prefabricated comments") return "預設註釋";
  if(s=="NOTES") return "筆記";
  if(s=="note") return "筆記";
  if(s=="NOT") return "筆記";
  if(s=="with or without notes") return "有無筆記";
  if(s=="with a note") return "有筆記";
  if(s=="with a note containing...") return "筆記包含...";
  if(s=="without notes") return "無筆記";
  if(s=="any type") return "任何類型";
  if(s=="private note, not shown on extranets") return "私人筆記，不在外部網路顯示";
  if(s=="private note, shown on extranets") return "私人筆記，在外部網路顯示";
  if(s=="public note") return "公開筆記";
  if(s=="Note types") return "筆記類型";
  if(s=="LEVEL") return "等級";
  if(s=="with a comment") return "有評論";
  if(s=="with a comment containing...") return "評論包含...";
  if(s=="TBX export") return "匯出TBX";
  if(s=="TBX import") return "匯入TBX";
  if(s=="Empty the termbase") return "清空術語庫";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "注意！您即將刪除此術語庫。刪除將無法復原。";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "注意！您即將刪除所有條目與其歷史紀錄。刪除將無法復原。";
  if(s=="RELATED TERMS") return "相關術語";
  if(s=="Your termbase at a glance") return "術語庫一覽";
  if(s=="Number of entries") return "條目數量";
  if(s=="Number of items in history log") return "歷史紀錄項目數量";
  if(s=="Your termbase is stored in the file %F") return "您的術語庫存放於檔案%F";
  if(s=="File size") return "檔案大小";
  if(s=="Download %F") return "下載%F";
  if(s=="Upload %F") return "上傳%F";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "請確保您上傳的檔案是有效的Terminologue術語庫。若您上傳其他東西，會對您的術語庫造成無法修復的損害。";
  if(s=="PARENT") return "上代";
  if(s=="no parent") return "無上代";
  if(s=="excluding subdomains") return "排除次語域";
  if(s=="including subdomains") return "包括次語域";
  if(s=="the entry has this domain") return "條目有此語域";
  if(s=="the entry has only this domain") return "條目僅有此語域";
  if(s=="the entry has not only this domain") return "條目不僅有此語域";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "注意！若您將自己從此術語庫移除，您將失去存取此術語庫的權限。";
  if(s=="Leave this termbase") return "離開此術語庫";
  if(s=="IMG") return "圖像";
  if(s=="IMAGES") return "圖像";
  if(s=="image") return "圖像";
  if(s=="credits") return "貢獻";
  if(s=="link to source") return "來源連結";
  if(s=="The file is too large. The maximum allowed size is $1 bytes.") return "檔案過大。最大容許為$1 bytes。";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
